### ISSUE TITLE
[suggestion] Remove tslint as a peer dependency

### ISSUE THREAD

**Issue by danthegoodman** [TypeStrong/fork-ts-checker-webpack-plugin#102]
I like that the project supports tslint, but I don't think it should require it to be a peer dependency or even be a regular dependency. 

npm doesn't support having optionalPeerDependencies at this time, and I don't think it's necessary to nag the users of this library with unmet peer dependency warnings. My suggestion is to remove it from the peer dependency list.

This is just a suggestion. If you disagree, feel free to close the issue and I'll just deal with having the warning popup in my projects from time to time.

---
Related: [npm/npm#3066 - Optional Peer Dependencies](https://github.com/npm/npm/issues/3066)

**Comment by johnnyreilly** [comment]
I don't feel that strongly but others clearly do! Fine with me...

**Comment by johnnyreilly** [comment]
@piotr-oles what do you think?

**Comment by nickserv** [comment]
I agree that an optionalPeerDependencies field would be ideal, so npm wouldn't force us to have warnings when tslint isn't installed. However, it was mentioned in that thread that peerDependencies are already optional, which seems to be why npm isn't prioritizing this feature.

peerDependencies still seems to be the best way to check if the dependency exists for me. Sure it may be annoying to have warnings about tslint when you don't need it, but if we removed the peer dependency, the user might end up with a config for an old version of TSLint (like 3) which isn't compatible with this package, but would appear to work at install time. Even though it doesn't have the best user experience yet, keeping a peer dependency is safest, and we can mention TSLint is optional in the readme if anyone gets confused.

**Comment by danielkcz** [comment]
Just my two cents here. There are so many packages rather abusing `peerDependencies` and putting there anything they think might be useful. I've kinda decided to ignore those warning altogether because it's an endless battle of figuring out what is missing where and then explaining why this and that shouldn't be there.

**Comment by nickserv** [comment]
That's incorrect, the package manager requires those to be in peerDependencies. If the package has two many dependencies, some of them can be removed.

**Comment by marcofugaro** [comment]
This issue was resolved in #201
