### ISSUE TITLE
fork-ts-checker not despawning it's services

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/fork-ts-checker-webpack-plugin#11]
Hello!

It looks like there may be a problem with fork-ts-checker not despawning its services.  It's been discussed here: https://github.com/amireh/happypack/pull/167

Do you have any idea what might be causing this?

**Comment by piotr-oles** [comment]
Plugin freezes process because of chokidar - but it shouldn't be turned on on 'build' mode - a source of the problem was misleading configuration. I've fixed it with v2.0.0 release :) #12
