### ISSUE TITLE
(feature) Support overriding compilerOptions settings and tslint config

### ISSUE THREAD

**Issue by LKay** [TypeStrong/fork-ts-checker-webpack-plugin#112]
I would be very helpful if there was a way to override and extend the `compilerOptions` for typescript compiles and tslint options that are by default imported form `tsconfig.json` and `tslint.json` respectively.

This is especially useful for development only webpack configurations when in most cases there is no need for strict checking of some rules/flags such as `noUnusedLocals` for typescript or setting `defaultSeverity` for tslint.

**Comment by piotr-oles** [comment]
@LKay
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)
