### ISSUE TITLE
INFO: NPM Access

### ISSUE THREAD

**Issue by etienne-dldc** [TypeStrong/fork-ts-checker-webpack-plugin#114]
Hi ✋ 

This issue just to inform you that we have change access on realytics org on NPM.

@piotr-oles you now have read/write access on `fork-ts-checker-webpack-plugin`.

I think current token is still working but can you please generate your own token and use it instead of the current token.

**Comment by piotr-oles** [comment]
Thank you for the update, I've changed this token - hope it will work :)
