### ISSUE TITLE
Support multiple typescript configurations in one project

### ISSUE THREAD

**Issue by cprass** [TypeStrong/fork-ts-checker-webpack-plugin#115]
I have a project that has two tsconfig files. One for the main index file and one for a webworker that needs the webworker lib to be included.

~~Typescript itself works just fine~~ (Not really, I just set the ts-loader to transpile-only mode), the ts-checker-plugin is still trying to parse the /workers folder even tho it is excluded in the main tsconfig.json.

~~Shouldn't the plugin use Typescript's module resolution?~~
I noticed that I import the worker via the workerize-loader with webpack, so Typescript is going to include the worker file even tho it is part of the exclude config.

Is it possible to specify a second tsconfig for the plugin or can I just add the plugin twice to my webpack config?

**Comment by Ty026** [comment]
So there is no solution for this?  I have the same problem.

**Comment by piotr-oles** [comment]
Currently, the only solution is to add the plugin twice with different tsconfigs. I'm not sure if this will work with the version 4 of the plugin but should work with the version 5 alpha. The drawback is that you will see double messages like "Waiting for issues...". Maybe we will implement this in the future but it's not planned for the version 5 stable release so the solution will not be soon.
