### ISSUE TITLE
Sometimes runs even though no files changed

### ISSUE THREAD

**Issue by eramdam** [TypeStrong/fork-ts-checker-webpack-plugin#117]
I've noticed that in watch/serve mode, the plugin will run the type checking randomly even when no files have changed at all.

Any ideas as to why this would happen? Happy to provide details to help debugging.

**Comment by johnnyreilly** [comment]
Sounds super weird. Haven't seen that myself... A minimal repro repo would be cool

**Comment by eramdam** [comment]
I may have spoken too soon. I'm using this plugin with https://react-styleguidist.js.org/ and it seems that the issue I'm describing only happens when running `react-styleguidist` and not inside a "vanilla" webpack configuration.

So I feel like the issue is on styleguidist's side.
I'll investigate a bit more and close if needed, sorry 😅

**Comment by johnnyreilly** [comment]
No bother!

**Comment by eramdam** [comment]
So I ran a bunch of tests and fork-ts-checker-webpack-plugin is the reason this happens. I'll close the issue.
