### ISSUE TITLE
Ship barebone typings.

### ISSUE THREAD

**Issue by SimonSchick** [TypeStrong/fork-ts-checker-webpack-plugin#137]
Ironically this package doesn't seem to be shipping it's typings, could they be added?

**Comment by johnnyreilly** [comment]
Sure - would you like to send a PR? You probably just need to make same changes we made for ts-loader; see https://github.com/TypeStrong/ts-loader/blob/master/src/tsconfig.json and https://github.com/TypeStrong/ts-loader/blob/master/package.json

Also https://github.com/TypeStrong/ts-loader/pull/790 and https://github.com/TypeStrong/ts-loader/pull/788

cc @Hotell in case he's any advice

**Comment by johnnyreilly** [comment]
Shipped with 0.4.5 https://github.com/Realytics/fork-ts-checker-webpack-plugin/releases/tag/0.4.5
