### ISSUE TITLE
cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by superlbr** [TypeStrong/fork-ts-checker-webpack-plugin#150]
in some env., os.cpus is undefined, such as turmux-app.
https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/db649e320e9350a098c7b854a1db35c9306d407c/src/index.ts#L69

**Comment by johnnyreilly** [comment]
Do you want to submit a PR that tests for the existence of `cpus` before reading then?

**Comment by superlbr** [comment]
> static ALL_CPUS = os.cpus() ? os.cpus().length : 1;

Well, since cpus is not defined in os, os.cpus() will still throw an error, I guess.Why not

`static ALL_CPUS = os.cpus ? os.cpus().length : 1;`

**Comment by johnnyreilly** [comment]
Sure - submit a PR!
