### ISSUE TITLE
Run ts-checker for specific directory and ignore derived directory from tsconfig.json

### ISSUE THREAD

**Issue by KenilDomadia** [TypeStrong/fork-ts-checker-webpack-plugin#155]
It is more of a question than an issue.

I want to run ForkTsCheckerWebpackPlugin for a specific directory. I looked at the `options` configuration but it doesn't seem to allow specifying context directory. Currently, all errors from directory containing `tsconfig.json` file are emitted.

`watch` options allows to specify directories or files to watch by service which improves performance 
 by reducing number of `fs.stat` calls.

I am more sort of looking for `context` option - where path specified in `context` should be treated as a tsc directory to emit errors from.

Is there any way currently to accomplish this?

**Comment by piotr-oles** [comment]
Sorry that I respond a few months later - you can set up a specific directory in tsconfig.json. The goal of this plugin is to emit the same errors as you could get in your IDE or another tool - that's why `tsconfig.json` is a source of truth for this plugin.
