### ISSUE TITLE
Cannot import when running webpack with ts-node

### ISSUE THREAD

**Issue by septagram** [TypeStrong/fork-ts-checker-webpack-plugin#158]
I'm having a very odd issue: when I'm trying to import this plugin, it seems to resolve as `/lib/types/index.d.ts` instead of `lib/index.js`, so I receive `undefined` on import.

I've created a [minimal test case](https://github.com/septagram/fork-ts-no-import) to reproduce. Please help me figure out if this is the `fork-ts-checker-webpack-plugin` issue, or an issue with my configuration.

I have no issue with import in general, other plugins are being imported just fine.

```
$ node --version && npm --version
v10.11.0
6.3.0
```

**Comment by piotr-oles** [comment]
Tested with version 1.0.0 with import * as ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin'; - works :)
