### ISSUE TITLE
Not compatible with non-flattened (pnpm) node_modules

### ISSUE THREAD

**Issue by IlyaSemenov** [TypeStrong/fork-ts-checker-webpack-plugin#164]
If a project uses non-flattened node_modules (such as created by `pnpm`), `fork-ts-checker-webpack-plugin` fails to load typings of nested dependencies.

## Steps to reproduce

Clone https://github.com/IlyaSemenov/fork-ts-checker-webpack-plugin-pnpm-reproduction, then:

```bash
npm install
npx webpack
```

Make sure the compilation succeeds, then:

```bash
rm -rf node_modules
npm i -g pnpm
pnpm install
npx webpack
```

The type checks will fail.

## Actual result

```
❯ npx webpack
Starting type checking service...
Using 1 worker with 2048MB memory limit
Hash: 34452b84502b638c21f7
Version: webpack 4.20.2
Time: 2868ms
Built at: 10/06/2018 5:00:49 PM
  Asset      Size  Chunks             Chunk Names
main.js  3.76 KiB    main  [emitted]  main
Entrypoint main = main.js
[./app.js] 21 bytes {main} [built]

ERROR in /Users/semenov/tmp/fts/node_modules/.registry.npmjs.org/@types/koa/2.0.46/node_modules/@types/cookies/index.d.ts
ERROR in /Users/semenov/tmp/fts/node_modules/.registry.npmjs.org/@types/koa/2.0.46/node_modules/@types/cookies/index.d.ts(12,26):
TS2307: Cannot find module 'express'.

ERROR in /Users/semenov/tmp/fts/node_modules/.registry.npmjs.org/@types/koa/2.0.46/node_modules/@types/cookies/index.d.ts
ERROR in /Users/semenov/tmp/fts/node_modules/.registry.npmjs.org/@types/koa/2.0.46/node_modules/@types/cookies/index.d.ts(13,26):
TS2307: Cannot find module 'connect'.

ERROR in /Users/semenov/tmp/fts/node_modules/fork-ts-checker-webpack-plugin/lib/types/index.d.ts
ERROR in /Users/semenov/tmp/fts/node_modules/fork-ts-checker-webpack-plugin/lib/types/index.d.ts(3,23):
TS2307: Cannot find module 'chalk'.

ERROR in /Users/semenov/tmp/fts/node_modules/fork-ts-checker-webpack-plugin/lib/types/NormalizedMessage.d.ts
ERROR in /Users/semenov/tmp/fts/node_modules/fork-ts-checker-webpack-plugin/lib/types/NormalizedMessage.d.ts(2,30):
TS2307: Cannot find module 'tslint'.
```

## Expected result

1) Type checks within non-flattened `node_modules` work fine (same as they do with `tsc`, `ts-node`, `tslint` etc.)
2) Honestly, I would expect `fork-ts-checker-webpack-plugin` not to descend into each and every module in `node_modules` until it's used by webpack compilation. However there are probably reasons for it to do that? Like reading all global augmentations?

**Comment by IlyaSemenov** [comment]
UPDATE: while checking the instructions above, I noticed that the last error (`Cannot find module 'tslint'`) shows even with `npm`.

**Comment by johnnyreilly** [comment]
Is the problem related to symbolic links?

I know we had to make changes to ts-loader to support this: https://github.com/TypeStrong/ts-loader/pull/774

Perhaps similar need to be applied to this plugin?

**Comment by IlyaSemenov** [comment]
Honestly I have not a slightest clue what could be the reason. 🤷‍♂️ I never examined *how* this library worked.

**Comment by johnnyreilly** [comment]
Now's your chance :wink:
