### ISSUE TITLE
Change how TypeScript dependency is handled

### ISSUE THREAD

**Issue by brunolemos** [TypeStrong/fork-ts-checker-webpack-plugin#165]
We are trying to add [TypeScript support to create-react-app](https://github.com/facebook/create-react-app/pull/4837), but there is currently one pending blocker: The maintainers don't want to add the typescript dependency to their repository directly, they want the users to add them on a project basis, allowing people to specify the version they want.

The problem is when I remove the `typescript` dependency from `create-react-app` `react-scripts` package (or even try to add it to `peerDependencies`), `fork-ts-checker-webpack-plugin` fails with the following error:

```shell
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/brunolemos/Projects/packages/create-react-app/node_modules/fork-ts-checker-webpack-plugin/lib/CancellationToken.js:6:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Any help is appreciated so we can merge https://github.com/facebook/create-react-app/pull/4837. 

I see there is #109 but I don't believe that will be enough to fix the issue.
The error points to this line: https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/237b1fd96fe5cd9450c8189a5c6f62bc5d119ba0/src/CancellationToken.ts#L5

**Comment by Timer** [comment]
Just to add, the `tslint` dependency would be great to go as well. We don't want unnecessary peer dependency warnings.

**Comment by johnnyreilly** [comment]
If we can help, we will! But since fork-ts-checker-webpack-plugin needs TypeScript to work I'm not sure what to suggest... Do you have an idea? PRs are gratefully received.

With regards peerDependencies, I suspect they are here to stay because of Yarn Plug'n'Play: https://github.com/TypeStrong/ts-loader/pull/841

**Comment by brunolemos** [comment]
We have found a [solution on create-react-app's end](https://github.com/facebook/create-react-app/blob/befafb3fceafb7cfe9f1e16e00436571637bcfc1/packages/react-scripts/config/webpack.config.dev.js#L415-L419), so no need to make changes here. 
Thanks @johnnyreilly.

**Comment by johnnyreilly** [comment]
Really pleased to hear it! Well done @brunolemos !

**Comment by Timer** [comment]
Hi, we actually decided against the work around above (mentioned by @brunolemos) and ended up needing to make changes to `fork-ts-checker-webpack-plugin`.

We're using a fork in Create React App for now and in the next few days I'll probably open a pull request with a proposal to change this behavior.
