### ISSUE TITLE
find property `tsconfig.json` file like ts-loader

### ISSUE THREAD

**Issue by JounQin** [TypeStrong/fork-ts-checker-webpack-plugin#168]
https://github.com/TypeStrong/ts-loader#configfile-string-defaulttsconfigjson

Use case:
I'm using [assemblyscript](https://github.com/AssemblyScript/assemblyscript) in my own project, it uses a independent [tsconfig.json](https://github.com/JounQin/wasm-study/blob/master/asms/tsconfig.json) to build `.wasm` files, so I have three `tsconfig.json` files.

But `fork-ts-checker-webpack-plugin` can not find them independently.

I have to ignore specific TypeScript error then: https://github.com/JounQin/wasm-study/blob/master/webpack.config.ts#L50

**Comment by johnnyreilly** [comment]
Would you like to submit as PR?
