### ISSUE TITLE
No type errors in browser console

### ISSUE THREAD

**Issue by Izzaki** [TypeStrong/fork-ts-checker-webpack-plugin#180]
There is no type errors in browser console.
Is this possible to display them?

**Comment by johnnyreilly** [comment]
If you look at how create-react-app-typescript uses the plugin it displays in an error overlay in the screen. Perhaps that would meet your needs?

**Comment by ypresto** [comment]
You need `async: false` option for plugin to make webpack-dev-server's `overlay: true` option work.

FYI I created plugin to enable error overlay for `async: true` (default) configuration by a little hacky way.
https://github.com/ypresto/fork-ts-checker-async-overlay-webpack-plugin

**Comment by piotr-oles** [comment]
@Izzaki , @ypresto
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which shows errors in the async mode in the webpack-dev-server 🚀

Huge thanks to the @ypresto - your implementation of the https://github.com/ypresto/fork-ts-checker-async-overlay-webpack-plugin helped me a lot 👏

I will close this issue to clean-up the backlog :)
