### ISSUE TITLE
Use TSLint language plugin instead of TSLint itself

### ISSUE THREAD

**Issue by deftomat** [TypeStrong/fork-ts-checker-webpack-plugin#184]
I'm wondering if it is possible to use [`typescript-tslint-plugin`](https://github.com/Microsoft/typescript-tslint-plugin) instead of a standalone TSLint.

I'm assuming that performance can be better. Also, this could provide users a way, how to enable TSLint  without touching the build configuration. A good example is `create-react-app`, which recently got a TS support. However, to be able to enable TSLint, one must change the build configuration. 

With this plugin, it should be easy to enable TSLint just by editing the `tsconfig` file.

I already tried to add this plugin to `tsconfig` and omit the tslint property in `fork-ts-checker-webpack-plugin` options but I cannot see any tslint warnings so I'm not sure if it is even possible to use language plugins with `fork-ts-checker-webpack-plugin`.

**Comment by harrysolovay** [comment]
Hi @deftomat, check out [Rescripts](https://github.com/rescripts/rescripts) if you're using CRA. There's a [use-tslint-config](https://github.com/rescripts/rescripts/tree/master/packages/rescripts/use-tslint-config) rescript, which I think is what you're looking for :)

**Comment by deftomat** [comment]
@harrysolovay Thanks, it looks good.

However, I'm more interested in typescript language plugin as we have a custom CRA fork with TSLint enabled and CRA team is also considering to include TSLint but it is not ready right now.

What I find out is that TypeScript is ignoring the language plugins in type-checks and it is using them only when you start a language-server itself.

So, I just wanted to know, if it is possible to use TSLint as a TS plugin right now or not.

**Comment by harrysolovay** [comment]
@deftomat I don't know about using it as a TS plugin –– sorry about that :(

I'd love to float something by you though: if you're using a custom CRA fork, you're likely either keeping it in sync with the upstream via a service like Backstroke, or you're manually updating it?

Neither of these approaches feel great; you end up dealing with more code than you need to, and updating `react-scripts` isn't nearly as seamless. I just released [Rescripts](https://github.com/rescripts/rescripts) to solve these problems, and would love to help you get set up if you're willing to give it a go. Please let me know what your needs are and I'll see if I can make a "rescript" (like a plugin) for it. I think Rescripts could make handling configuration much easier for you and your team. I'd love to hear your thoughts!

**Comment by deftomat** [comment]
@harrysolovay 

Rewiring the `react-scripts` is not enough for us, we have a custom `react-dev-utils` too. 

Anyway, it's not related to this issue. If you want to talk about it, please contact me through the email or create an issue in your repo and mention me.

**Comment by harrysolovay** [comment]
@deftomat  gotcha. Thought it might be helpful. Sorry that it was not.

**Comment by 0xorial** [comment]
> I already tried to add this plugin to tsconfig and omit the tslint property in fork-ts-checker-webpack-plugin options but I cannot see any tslint warnings

I tried with `webpack` and with 'bare' `tsc` and had no success at all - seems like TypeScript compiler silently ignored passed plugins o_O
Idea overall seems awesome though.

**Comment by 0xorial** [comment]
Oops, silly me:
[TypeScript Language Service Plugins ("plugins") are for changing the editing experience only.](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#whats-a-language-service-plugin)

**Comment by deftomat** [comment]
@0xorial Yes, it is not possible as TypeScript is ignoring it. I totally forgot that I created this issue.

Looks like I can close it as it is a limitation of TypeScript and there is nothing which we can do in this repo about it 😞
