### ISSUE TITLE
Plugin doesn't run for project references

### ISSUE THREAD

**Issue by MLoughry** [TypeStrong/fork-ts-checker-webpack-plugin#187]
Much like `tslint` and (to an extent) `ts-loader`, it seems this project doesn't yet fully support Typescript>=3.0.0 style project references. If I introduce an error into a dependent project, `fork-ts-checker-webpack-plugin` doesn't find the error.

**Comment by johnnyreilly** [comment]
If you'd like to have a crack at adding support you'd be most welcome! cc @andrewbranch - author of project reference support in ts-loader in case he has any thoughts 🌻♥️

See also: https://blog.johnnyreilly.com/2018/09/ts-loader-project-references-first-blood.html

**Comment by MLoughry** [comment]
I believe that, like TypeStrong/ts-loader#851, this ultimately requires the new Typescript APIs yet to be implemented and tracked by Microsoft/Typescript#28640.

I may look into making such a contribution once the APIs are available, to learn them for my own needs; but I don't think it's worthwhile to do so before then.

**Comment by noahm** [comment]
The new API was added in https://github.com/microsoft/TypeScript/pull/31432 and has been released in Typescript v3.6 so this should be unblocked now. Unfortunately, I don't know enough about how this plugin or the typescript API works to really tackle this myself yet.

**Comment by sikloidz** [comment]
There is any update on this feature? Currently my build it's ok with ts-loader but would be nice to be able to speed the compilation time by forking the type checking

**Comment by piotr-oles** [comment]
We are working on the major refactor of the plugin internals as a 5.0.0 release. The new implementation should support project references out of the box :)

**Comment by Ivaylo-Lafchiev** [comment]
Is there any updates on this? Would like to be able to use this & ts-loader with projectReferences.

**Comment by piotr-oles** [comment]
Currently, I'm focusing on refactoring and I hope I will release an alpha version in the next month. It's a huge task and I have limited time to work on it :)

**Comment by johnnyreilly** [comment]
Hey all,

The amazing @sheetalkamat is busy improving the  project references support in `ts-loader` in https://github.com/TypeStrong/ts-loader/pull/1076

Part of the discussion is around how `transpileOnly` should work alongside `fork-ts-checker-webpack-plugin`. Feel free to be part of the discussion 🌻🥰

**Comment by piotr-oles** [comment]
@MLoughry , @noahm , @sikloidz , @Ivaylo-Lafchiev
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which supports project references 🚀
I will close this issue to clean-up the backlog :)
