### ISSUE TITLE
Option tslintAutoFix is broken for vue file 

### ISSUE THREAD

**Issue by mortyccp** [TypeStrong/fork-ts-checker-webpack-plugin#191]
# Step to reproduce
1. `git clone https://github.com/mortyccp/reproduces`
1. `cd reproduces`
1. `git checkout fork-ts-checker-autofix-vue`
1. Follow instruction defined in the readme in the cloned repo.

**Comment by Bosee** [comment]
same issue too, all vue files was broken when tslint auto-fix enabled

**Comment by johnnyreilly** [comment]
If someone could take a look at this that'd be great!

Perhaps @ajainarayanan could advise? I'm not a Vue user I'm afraid.

**Comment by ajainarayanan** [comment]
I have not worked with vue before. But enabling `tslintAutoFix` literally just passes on the `--autofix` flag to tslint. I don't think this error is related to `fork-ts-checker-webpack-plugin`

BTW @mortyccp I tried cloning your repo and ran `yarn serve` setting the `tslintAutoFix` to both true and false in `vue.config.js`. Either ways I am getting the same error in the console. Are you sure if this was working before you changed the `tslintAutoFix` flag?

**Comment by mortyccp** [comment]
@ajainarayanan Sorry, I mistakenly commit the files in after state. You can just `git diff HEAD~` to see the change on those files then.  
I have pushed a commit and it should be able to reproduce now.
The `src/App.vue` contins code, `import Vue from "vue";` , violating  the quotemark rule and trigger the auto fix.
