### ISSUE TITLE
is there a way to suppress the initial console output if workers are more than 1?

### ISSUE THREAD

**Issue by kelly-tock** [TypeStrong/fork-ts-checker-webpack-plugin#193]
I see this when workers is not the default value:

```
Starting type checking and linting service...
Using 3 workers with 4096MB memory limit
Watching: /Users/kelly/tock/admin/dashboard/src
```

is there an option to suppress this sort of stuff and only log out any TS or TSLint errors?

**Comment by johnnyreilly** [comment]
Have you tried using `silent`?

**Comment by kelly-tock** [comment]
silent disabled all logging of errors. I want the errors to be displayed, just not the other stuff. maybe a log_level setting or something would be nice?

**Comment by johnnyreilly** [comment]
Yeah possibly - ts-loader has similar. Would you consider putting together a PR?

**Comment by kelly-tock** [comment]
Will take a look.
