### ISSUE TITLE
[docs question] `watch` option

### ISSUE THREAD

**Issue by Andarist** [TypeStrong/fork-ts-checker-webpack-plugin#200]
According to the docs the option is not required - but from what i see in the source code is that it's mapped to `watchPaths` which are later used to start chokidar (watcher), therefore if the option is not used then no files are being watched.

Or maybe they are watched because of some other lines that I have not found and I only observe some other problem on my side?

If my suspicion is true - should we just change docs or should we fix the plugin's behaviour?

**Comment by johnnyreilly** [comment]
> Or maybe they are watched because of some other lines that I have not found and I only observe some other problem on my side?

AFAIK this is optional. Can you create a repro that demonstrates this is not the case?

**Comment by Andarist** [comment]
Ok, so I've tried to reproduce the issue - but seems like everything is working, but for reasons I don't quite understand.

It works because the webpack's compilation hook triggers the service and thus IncrementalChecker. 

I don't understand the purpose of FilesWatcher class though, what is its job? (I can confirm that it is not watching the source files if I don't specify `watch` option - but I have no idea what kind of impact does it have)

**Comment by johnnyreilly** [comment]
Perhaps @piotr-oles can advise?
