### ISSUE TITLE
Improve error message for mismatched `vue`, `vue-template-compiler`

### ISSUE THREAD

**Issue by fastfedora** [TypeStrong/fork-ts-checker-webpack-plugin#209]
When the version of the `vue-template-compiler` does not match the version of `vue`, the following error is thrown ([code](https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/src/VueProgram.ts#L273)):

```
node_modules/fork-ts-checker-webpack-plugin/lib/VueProgram.js:183
            throw new Error('When you use `vue` option, make sure to install `vue-template-compiler`.');
            ^
Error: When you use `vue` option, make sure to install `vue-template-compiler`.
```

In this case `vue-template-compiler` is already installed; it's just that there is a version number mismatch. It would be helpful if the following text was added: 

> If `vue-template-compiler` is already installed as a dependency, ensure it has the same version number as the `vue` dependency.

Alternatively, printing the underlying error thrown from `vue-template-compiler` would help make the root cause of the error clearer.

**Comment by xinbenlv** [comment]
+10000000000

**Comment by xinbenlv** [comment]
@fastfedora you want to update your link to code to https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/4537c161e26a4961663236e208644ddd3d84a9ca/src/VueProgram.ts#L273 (permlink)

**Comment by johnnyreilly** [comment]
Sounds good. Would you like to submit a PR?

**Comment by fastfedora** [comment]
I no longer am on the project I was using Vue for, so have no easy way to test the code for a PR. But a decent fix would be to change [lines 313-317](https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/dfd8933f23da7ca72aa3a864e5811725146323d4/src/VueProgram.ts#L313-L317) from: 

```
    } catch (err) {
      throw new Error(
        'When you use `vue` option, make sure to install `vue-template-compiler`.'
      );
    }
```

To:

```
    } catch (err) {
      throw new Error(
        `Could not initialize 'vue-template-compiler'. When you use 'vue' option, make 
sure to install 'vue-template-compiler' and that the version matches that of 'vue'. 
Error details: ${err.message}`;
      );
    }
```

**Comment by piotr-oles** [comment]
@fastfedora , @xinbenlv 
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog :)
