### ISSUE TITLE
silent option silences errors and warnings

### ISSUE THREAD

**Issue by lizzzp1** [TypeStrong/fork-ts-checker-webpack-plugin#212]
I'm trying to silence only `WARNINGS` from tslint. Adding `silent` true will silence errors as well. Is there a way to specify only silencing warnings and not errors?

Thanks.

**Comment by johnnyreilly** [comment]
Hey @lizzzp1

There's `ignoreLints` but that requires you specify the lints you want to ignore. It seems like a potentially useful feature though; do you fancy submitting a PR?

**Comment by lizzzp1** [comment]
@johnnyreilly yeah, I can give it a shot! - Thanks for the quick reply.

**Comment by lizzzp1** [comment]
@johnnyreilly what is the preferred api/option for this?

**Comment by johnnyreilly** [comment]
Maybe a new option called `ignoreLintWarnings`? Default value of `false`. Try it out - see how it feels.
