### ISSUE TITLE
Fail CI build on TSLint warning / Support tslintEmitErrors config

### ISSUE THREAD

**Issue by jprince** [TypeStrong/fork-ts-checker-webpack-plugin#216]
I'm looking for a way to configure my CI build to fail if TSLint warnings are emitted. The ts-checker-webpack-plugin supports this via a `tslintEmitErrors` configuration:
> Report all TSLint failures as webpack errors regardless of the rule severity.

https://github.com/zinserjan/ts-checker-webpack-plugin/pull/32

Is there a similar configuration for this library?

**Comment by johnnyreilly** [comment]
Doesn't this get triggered by running this with `async: false`?

**Comment by jprince** [comment]
It does not appear to. It sounds like `async: false` waits for the linter to add _errors_ but perhaps it doesn't work for warnings? Looking at the commit linked above, they seem to use the flag to override the default TSLint severity and treat warnings like errors:

https://github.com/zinserjan/ts-checker-webpack-plugin/pull/32/files#diff-5d35cfb719cbb7207843d4209131df48R32

**Comment by johnnyreilly** [comment]
We'd be open to PRs on this I think

**Comment by piotr-oles** [comment]
I'm closing this issue as we no longer support TSLint :)
