### ISSUE TITLE
Allow to trigger a typecheck for "virtual files" from outside?

### ISSUE THREAD

**Issue by phryneas** [TypeStrong/fork-ts-checker-webpack-plugin#224]
Hi there!

I'm trying to find a way to trigger a typecheck for `.mdx` files. Those files have to be transpiled to js/ts first using `mdx-loader`. After that, I would like to typecheck the generated source code.

My idea was to put a loader behind `mdx-loader` and from there somehow signal `fork-ts-checker-webpack-plugin` to check the transpiled source code.

Is this somehow possible?

Currently I'm doing that typecheck in a self-written loader, but as I don't really know a lot about webpack and tsc, this is very inefficient.

(I also opened an issue in the docz project, because that would be the other side of what I want to do. In the end, docz's .mdx-files could be typesafe: https://github.com/pedronauck/docz/issues/664 )

**Comment by johnnyreilly** [comment]
Wow that's an unexpected request!

I expect that you could do worse than look at how we handle Vue files. It's not exactly the same use case but there's some similar work at play

**Comment by phryneas** [comment]
@johnnyreilly Thanks for the pointer - I didn't think about looking at the vue-specific-code. We have slackday on friday, so I'll try and spend that day trying to figure out how everything works.

One thing though: could you give me a few hints on how fork-ts-checker works in general? That could save me a few hours - I don't really know how the plugin knows which files to validate. Does it start working from the webpack entry points, or does is monitor which files are opened by webpack somehow? 
Stuff like that - every little bit helps, no need to be too extensive :)

**Comment by johnnyreilly** [comment]
Sure. For speed reasons the plugin doesn't get triggered by webpack. A file change should trigger a change. There's 2 ways the plugin can work:

1. File watching mode - watches files and triggers compilation (`useTypescriptIncrementalApi: false`).

2.  Using TypeScripts watch API (`useTypescriptIncrementalApi: false`).

If experimenting I'd start with approach 1. As it's probably easier to get going with

**Comment by phryneas** [comment]
Thanks :)
