### ISSUE TITLE
secret api key in travis.yml?

### ISSUE THREAD

**Issue by phryneas** [TypeStrong/fork-ts-checker-webpack-plugin#226]
Umm... are you aware that there is a secret npm api key in https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/.travis.yml ?

Obviously, I did NOT test it, so sorry if that is an old revoked api key.

**Comment by johnnyreilly** [comment]
You mean the `secure: ` key? That's for publishing the package. It's encrypted - if you tried to use it it wouldn't succeed. Thanks for having our back though 😄❤️

**Comment by phryneas** [comment]
Phew, okay :)
