### ISSUE TITLE
Does not work with Webpack Multiple Target Configuration

### ISSUE THREAD

**Issue by kube** [TypeStrong/fork-ts-checker-webpack-plugin#229]
When using [Webpack Multiple Target Configuration](https://webpack.js.org/concepts/targets/#multiple-targets), e.g.

```js
module.exports = [
  configLibrary,
  configWebApp,
  configNodeCli,
  configDenoCli,
]
```

Here if all of these Webpack configurations use `fork-ts-checker-webpack-plugin`, only the first one will be compiled.

**Comment by kube** [comment]
https://webpack.js.org/concepts/targets/#multiple-targets

**Comment by johnnyreilly** [comment]
Interesting. It's not been a use case of mine so I haven't considered it. Feel free to experiment and submit PRs 😀

**Comment by IIIristraM** [comment]
Looks like right now workaround is

```js
const tsFork = new ForkTsCheckerWebpackPlugin({...});

for (const comp of compiler.compilers) {
    tsFork.apply(comp);
}
```

It works, but has at least one negative effect like multiple same messages on start, nevertheless in my case with fifteen configs it's more acceptable than fifteen services.

Important note is that in my case all configs build parts of one app, so I can just run checker with tsconfig that includes all corresponding folders, add apply is a way to trigger check if any parts changed.

**Comment by piotr-oles** [comment]
@kube , @IIIristraM
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)
