### ISSUE TITLE
ESLint: "fork-ts-checker-webpack-plugin" is not published. (node/no-unpublished-require)

### ISSUE THREAD

**Issue by davidmpaz** [TypeStrong/fork-ts-checker-webpack-plugin#23]
Hi,

I am trying to use this plugin into [Encore](https://github.com/symfony/webpack-encore) but I am getting this ESLint error. 

I have read the [rule docs](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md) but not sure whats need to be done.

thanks in advance

**Comment by piotr-oles** [comment]
Hi!
Thanks for reporting :) 
This error occurs because there is no `"files"` field in `package.json`. I will fix it soon :)

**Comment by piotr-oles** [comment]
#24

**Comment by piotr-oles** [comment]
Should be fixed with #24 - I will publish it as `0.2.4`

**Comment by davidmpaz** [comment]
Hey, thanks!!

**Comment by piotr-oles** [comment]
Published - please let me know if it fixes issue :)

**Comment by davidmpaz** [comment]
Yeap! :+1:  Thanks again.

Cheers
