### ISSUE TITLE
Emitting .d.ts files while type checking 

### ISSUE THREAD

**Issue by rogerlucena** [TypeStrong/fork-ts-checker-webpack-plugin#230]
In our project we are working with TypeScript, Webpack and Babel 7. 

To deal with the TypeScript files we were using the awesome-typescript-loader but there were happening a lot of problems when the generated .js files were taken by Babel. Then, we decided not to use the awesome-typescript-loader anymore, but instead stick to Babel and, since Babel does not do type checking for TypeScript, we decided to do it by using your plug-in fork-ts-checker-webpack-plugin, and we are enjoying a lot the experience. 

The only problem now is that, for our application, we need to generate the .d.ts files so that the imports from one Project to another will be done properly.

We observed that your project is missing only the "emit" step for fixing the problem above.

We want to make a contribution to your project by following the steps bellow and your opinion would be very welcome.

In service.ts, inside the "run" function we will do the "getDiagnostics" for the type checking as it is done now but we will also "emit" to generate the d.ts files.

In order to not affect the other users the "emit" phase should be optional. Thus we are creating a new field in the plug-ins Options interface called "ignoreEmit" with default value of "true".

**Comment by johnnyreilly** [comment]
I'm really glad you're enjoying using the plugin!

I'm afraid I have got very mixed feelings about what you're suggesting though.  The fork-ts-checker-webpack-plugin has always been intended to be a checker - not something that generates TS code in any way. 

Classically code generation has been the responsibility of ts-loader which is typically what people use alongside the fork-ts-checker-webpack-plugin. (There are examples of how you can use them together: https://github.com/TypeStrong/ts-loader/tree/master/examples/fork-ts-checker-webpack-plugin - which reminds me; I must update them now fork-ts-checker-webpack-plugin has 1 point oh-ed)

I see you're using Babel - that's cool. (It's only relatively recently that this has become possible - super cool!) 

If you wanted to switch to use ts-loader and try and add the functionality there then I'd be happy to help make that happen. The switch should be relatively simple. I think there's a need for what you're trying to do.

Alternatively if you wanted to roll your own plugin which plays well alongside the fork-ts-checker-webpack-plugin that's a great idea too. There's already examples of this such as the https://github.com/dividab/tsconfig-paths-webpack-plugin

What do you think?

**Comment by piotr-oles** [comment]
I'm closing this issue as there no further comments :)
