### ISSUE TITLE
utilize ts 3.4 build cache to improve startup time

### ISSUE THREAD

**Issue by kelly-tock** [TypeStrong/fork-ts-checker-webpack-plugin#238]
TS 3.4 just came out, and i'm wondering if it is possible to use this to speed things up?

I have set the incremental flag in my tsconfig, but don't see the build info being generated when going through webpack, only through the `tsc` command. 

is it possible to utilize this within the context of this plugin?

**Comment by johnnyreilly** [comment]
It's possible changes may need to be made to accommodate this. We're open to PRs on that front. This may be useful context: https://github.com/TypeStrong/ts-loader/issues/913

**Comment by Bessonov** [comment]
@johnnyreilly linked issue seem to be resolved. Any news on this one?

**Comment by johnnyreilly** [comment]
I'm not working on this myself; I'm not sure if anyone else is

**Comment by piotr-oles** [comment]
@kelly-tock , @Bessonov
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which supports incremental building 🚀(note that it won't generate `.tsbuildinfo` file but will consume it if present)
I will close this issue to clean-up the backlog :)
