### ISSUE TITLE
Incomplete error format when async: false

### ISSUE THREAD

**Issue by jesantana** [TypeStrong/fork-ts-checker-webpack-plugin#239]
I have a project with the following karma.conf.js

```
                {
                        test : /\.ts$/,
                        exclude: /bootstrap.ts/,
                        use: [
                            {
                                loader: 'thread-loader',
                                options: {
                                    workers: require('os').cpus().length - 1,
                                },
                            },
                            {
                                loader: 'ts-loader',
                                options: {
                                    configFile: path.resolve(process.cwd(), 'tsconfig.test.json'),
                                    happyPackMode: true
                                }
                            },
                            'angular2-template-loader'
                        ]
                    },
.....

           plugins : [
				new WebpackKarmaDieHardPlugin(),
                new ForkTsCheckerNotifierWebpackPlugin({ excludeWarnings: true }),
                new ForkTsCheckerWebpackPlugin({
                    checkSyntacticErrors: true,
                    tsconfig: path.resolve(process.cwd(), 'tsconfig.test.json'),
                    async: false
                }),
                new webpack.ContextReplacementPlugin(
                    /angular(\\|\/)core(\\|\/)@angular/,
                    __dirname
                ),
                new webpack.SourceMapDevToolPlugin({
                    filename : null,
                    test : /\.(ts|js)($|\?)/i
                }),
                new webpack.LoaderOptionsPlugin({})
            ],

```

When I introduce a compilation error in typescript, I can't see the source file but just the lines and type of error 

`(12,9): Type '"2"' is not assignable to type 'number'.
(12,9): 'i' is declared but never used.`

I tried adding 
`formatter: ((message, useColors) => JSON.stringify(message))` to the plugin but didn't achieve anything.

Any help pointing in which direction i should look for the problem will be highly appreciated

**Comment by jesantana** [comment]
Ok, I found that fork-ts-checker-webpack-plugin when configured with async = false is emmitting errors to webpack for it to log them once it regained the control of execution.

The code that create the errors is like this:

```
var formatted = {
        rawMessage: (message.getSeverity().toUpperCase() + ' ' + message.getFormattedCode() + ': ' + message.getContent()),
        message: '(' + message.getLine() + ',' + message.getCharacter() + '): ' + message.getContent(),
        location: {
                    line: message.getLine(),
                    character: message.getCharacter()
                },
        file: message.getFile()
};
compilation.errors.push(formatted);
```

and the output message that I am getting matches with the field `formatted.message`. Is it ok that the default field with error message send back to webpack doesn't contain the file name. If you agree that this can be changed I can create a pull request. Otherwise, is there a workaround in webpack to change the default error logging behavior to be more explicit and output the rest of the received message? I play with stats but couldn't get any result.

**Comment by johnnyreilly** [comment]
Are you saying that the formatter *isn't* used when in `async: false` mode? Can you supply a link to the part of the codebase you're looking at please?

**Comment by jesantana** [comment]
Rigth. In `async: false` when there is compilation error, the `createEmitCallback()` function execute the code I sent before around line 786 (not calling the formatter but returning an error object), and I guess that since the emit phase ended wrongly, webpack output part of the error messages and execution is finished.

On the other hand, if I change to async: true, the formatter (only called in `createDoneCallback()`) is used and the message is written as expected.

Resuming,  when `async: false` the callback for done phase of the plugin is never invoked. I think is not completely incorrect to not call the formatter when returning the errors after the emit phase because webpack api might expect something more than a string in the error the plugins return back to it, and a string is what the formatter provides. But maybe this format could be more complete.

Just for more details, I am using the following versions:

```
webpack: 2.4.1
karma-webpack: 2.0.1
fork-ts-checker-webpack-plugin: 0.4.1

```

**Comment by johnnyreilly** [comment]
Could you upgrade the versions of webpack / fork-ts-checker-webpack-plugin you're using please? I'm keen to know whether this is a current issue.

It might be easier if you raise a PR to illustrate the suggestion you have in mind. Feel free to do that initially without tests whilst we talk this through.

If we want to go ahead with this we can discuss tests then

**Comment by jesantana** [comment]
My bad, on latest is not reproducible. I totally thought I was running on it but I wasn't.

The problem seems to be fixed by this pull requests:

[https://github.com/Realytics/fork-ts-checker-webpack-plugin/commit/fa466c688b747e06e4e955acbf1ec6cc9870f88e](https://github.com/Realytics/fork-ts-checker-webpack-plugin/commit/fa466c688b747e06e4e955acbf1ec6cc9870f88e
)

I guess this issue can be closed. Thanks a lot for your support!
