### ISSUE TITLE
Run times have a sharp increase after upgrade to packages.

### ISSUE THREAD

**Issue by GeorgiosP** [TypeStrong/fork-ts-checker-webpack-plugin#242]
running into an issue when upgrade my react app compile time has gone from ~4000ms to over ~70,000ms+ seems to be directly linked to `fork-ts-checker-webpack-plugin`

[Webpack Profiler](https://cl.ly/64a4fe495836)
[After emitting finishes](https://cl.ly/a1ff57671567)

### tsconfig
```{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es6",
    "lib": ["es2017", "dom"],
    "sourceMap": true,
    "allowJs": true, 
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "skipLibCheck": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "config",
    "cypress",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

### webpack
```
    new ForkTsCheckerWebpackPlugin({
      async: false,
      watch: paths.appSrc,
      tsconfig: paths.appTsConfig,
      tslint: paths.appTsLint,
    }),
```

**Comment by johnnyreilly** [comment]
If you could investigate what's causing that, it would be very helpful @GeorgiosP 😊

By the way, having `async: false` rather than `async: true` will mean you have a slower experience.

**Comment by GeorgiosP** [comment]
I'll give that a shot, and when I have some free time I'll do some more investigating 😄

**Comment by GeorgiosP** [comment]
hey @johnnyreilly I haven't forgot about this just been super busy sorry. update: I can't seem to decipher the issue here I know not super helpful but if I end up finding something will pass it along.
