### ISSUE TITLE
`compilerOptions.paths` not taken into account without the `vue` flag

### ISSUE THREAD

**Issue by alexkirsz** [TypeStrong/fork-ts-checker-webpack-plugin#254]
## Current behavior

My `tsconfig.json` features the following code:

```js
{
  // ...
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    // ...
  },
  // ...
}
```

But when I run my webpack compilation, the plugin repeatedly complains that it cannot find modules prefixed with `"@/"`, i.e.:

```js
// ...
import darkTheme from "@/themes/darkTheme";
```

Results in:

```
ERROR in /Users/alex/dev/frontend/src/Theme.tsx
ERROR in /Users/alex/dev/frontend/src/Theme.tsx(4,23):
TS2307: Cannot find module '@/themes/darkTheme'.
```

However, passing the flag `vue: true` to the plugin's options fixes the issue.

## Expected behavior

The `compilerOptions.paths` option should always be taken into account.

## Steps to reproduce the issue

Add an entry to the `compilerOptions.paths` field to your `tsconfig.json`, don't set the `vue` flag in the plugin options, and try to import a file using the aforementioned entry.

## Environment
 - **fork-ts-checker-webpack-plugin**: "^1.1.0"
 - **typescript**: "^3.3.3333"
 - **tslint**: "^5.14.0"
 - **webpack**: "^4.29.6"
 - **os**: "macOS 10.14.4"

**Comment by johnnyreilly** [comment]
I think you're missing the https://www.npmjs.com/package/tsconfig-paths-webpack-plugin - details here:

https://github.com/TypeStrong/ts-loader/blob/master/README.md#baseurl--paths-module-resolution
