### ISSUE TITLE
karma-webpack causes false-positive "watch" mode which causes ForkTSCheckerWebpackPlugin to never exit

### ISSUE THREAD

**Issue by trash** [TypeStrong/fork-ts-checker-webpack-plugin#27]
We use karma-webpack to run our tests. It accepts a `singleRun` argument in its options object but even when set to true it uses `webpack-dev-middleware` which always starts webpack via a call to `watch()`. This produces a false-positive where [this line](https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/lib/index.js#L132) thinks webpack is watching (because the `watch-run` event *is* emitted) when it's effectively not. The end result is even after the tests are finished ForkTSCheckerWebpackPlugin stays open because it ignores the `done` event and never receives an `exit` event.

Now, I think the clean solution is that that `singleRun` argument for karma-webpack should *not* end up making a call to `watch()` for webpack. That being said, that sounds like a fairly intensive refactor to some fairly frequently used code. Would it be possible to have a `singleRun` option that's accepted by ForkTsCheckerWebpackPlugin that either A) ignores the `isWatching` flag if `singleRun: true` or B) causes the `isWatching` flag to always stay `false` when `singleRun` is `true`? I can get a PR together really shortly if this is amenable as this is basically a 2 line change either way.

Love the plugin so far as it's improved the speed of our build a ton. Thanks!

**Comment by johnnyreilly** [comment]
I think I may have been affected by this also - I'd be interested to see a PR!

**Comment by piotr-oles** [comment]
Sure, it's good idea to add this flag :) Waiting for the PR ;)

**Comment by johnnyreilly** [comment]
Yup - I'm pretty sure this is what's been tripping up my CI. Looking forward to seeing the PR!

**Comment by trash** [comment]
After working on the PR I attempted to write some tests and was having some difficulty. Digging a little deeper after that, it looks like webpack [emits a "watch-close" event for plugins](https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L154). Throwing a callback that calls `killService` after that seems to solve this issue as well and I think ends up being a lot more coherent of a solution. Working on some tests and then I should have a PR shortly.

**Comment by trash** [comment]
OK so it looks like the `watch-close` event wasn't added until the 2.3.0 release of webpack. I assume that's probably fine. You can either authoritatively say that this plugin requires webpack 2.3.0+ or just that this bug (that's not even caused by this plugin) is fixed by updating webpack.
