### ISSUE TITLE
Equivalent for ts-loader's context

### ISSUE THREAD

**Issue by stavalfi** [TypeStrong/fork-ts-checker-webpack-plugin#297]
## Feature motivation
https://github.com/TypeStrong/ts-loader#context-string-defaultundefined
This is a killer feature in complex projects.

In my specific use-case, I moved all my build related files (including tsconfig.json) to a different package (something like create-react-app is doing but in much more flexible way) in my mono-repo and everything is working great. it's just that i'm fighting to use this KILLER plugin!

-----
* as a workaround, I could override all the relevant tsconfig.json proeprties inside this plugin's options, but I can't override include and exclude properties :(
---

Thanks again for you amazing work!!!

**Comment by johnnyreilly** [comment]
Heya! Thanks for the complements! Maintainer of both ts-loader and fork-ts-checker-webpack-plugin here. It would be great to understand more about your use case. Could you go into some more details please?

Also, would you consider working on a PR?

**Comment by stavalfi** [comment]
hihihi!

I'm working on a super Lerna-starter that pretty much includes everything there is to include. I'm not even close to finishing but anyways, here is a taste: https://github.com/stavalfi/lerna-starter  (just run `yarn` and you are good to go).

as part of my work, I found out that a lot of the sub packages (workspaces in yarn) has 90% of their build strategy in common. for example, packages that generate js to be used by other packages, like react/angular/... and packages that generate webapps/websites/... for each group of packages, most of the build files are the same so I moved **all** of them to a dedicated sub-package under "build". you can look it out your self, it's working great with all the 3rd party packages that I'm using like webpack, eslint and more. 

actually, I lied... I moved all of them except a single build file: "tsconfig.json". I need that in each package from any type for 2 reasons: webstorm-typescript integration AND this plugin.

for the first reason, I can use a tsconfig.json that is in the main folder (where .git folder is). for the second reason, I need your help so I can move it from there and I will get a complete 100% free-build-files packages.

**Comment by johnnyreilly** [comment]
Sorry I think I missed this reply! This sounds like a potentially interesting feature; do you want to submit a PR?

**Comment by stavalfi** [comment]
I have no idea where to start lol.. let me investigate a little bit..

**Comment by u8sand** [comment]
I would also be interested in this capability--my use case is building opinionated reusable webpack build scripts--tsconfig.json is defined in the build scripts project but it will be utilized to build typescript in a separate project. When context is not set, the include paths don't check in the right location (instead it checks in the same place as tsconfig.json).

**Comment by stavalfi** [comment]
@u8sand we have the same use case :) you can have a look at what I did here: https://github.com/stavalfi/flow under packages/build.

I also have a starter-project that is the non-up-to-date-copy of this project: https://github.com/stavalfi/lerna-starter

@johnnyreilly I didn't start working on it yet. so if someone else want to investigate, it would be great.

**Comment by joebnb** [comment]
![image](https://user-images.githubusercontent.com/1646883/82301267-92a67180-99ea-11ea-9123-b732a5f725dd.png)

**Comment by piotr-oles** [comment]
@stavalfi I'm just wondering - maybe you could use `process.cwd()` in the `tsconfig.json` file path? Or you could even use it for the webpack's `context` field? Then, you can use a path for the `tsconfig.json` that is relative to the webpack's context.

Also, please check out the `alpha` version which supports _Project References_ - it can be useful in the monorepo :)

**Comment by shayke** [comment]
Anyone has a workaround?
I'm also using a `tsconfig.json` file inside an npm package and getting:
`ERROR in ERROR in undefined(undefined,undefined):`

**Comment by stavalfi** [comment]
> @stavalfi I'm just wondering - maybe you could use `process.cwd()` in the `tsconfig.json` file path? Or you could even use it for the webpack's `context` field? Then, you can use a path for the `tsconfig.json` that is relative to the webpack's context.
> 
> Also, please check out the `alpha` version which supports _Project References_ - it can be useful in the monorepo :)

Sory, it was a while ago and I stopped working with webpack. I'm not working on the same project so I don't have the time to contribute to this conversation. 

Best of luck guys

**Comment by piotr-oles** [comment]
@shayke , @joebnb , @u8sand 
I will create a PR soon :)
