### ISSUE TITLE
Add docs for Yarn PnP usage

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/fork-ts-checker-webpack-plugin#298]
This is a reminder for me to add docs to the project detailing how you can use `fork-ts-checker-webpack-plugin` with Yarn PnP.  (See: https://github.com/arcanis/pnp-webpack-plugin/pull/10#issuecomment-499367457 )

I've written a blog post: https://blog.johnnyreilly.com/2019/06/typescript-webpack-you-down-with-pnp.html

For now I've just put a link in the `fork-ts-checker-webpack-plugin` GitHub page to that post.  But a docs addition would be clearer / better.

**Comment by piotr-oles** [comment]
Solved in the alpha release :)
