### ISSUE TITLE
Cannot read property 'compiler' of undefined in v1.3.6

### ISSUE THREAD

**Issue by Kamahl19** [TypeStrong/fork-ts-checker-webpack-plugin#300]
## Current behavior
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'compiler' of undefined
```

## Environment
 - **fork-ts-checker-webpack-plugin**: v1.3.6

The bug was introduced in this commit https://github.com/Realytics/fork-ts-checker-webpack-plugin/commit/489dc89b1d4b043128837c8588d2c3c9ad6dd4ec

**Comment by phryneas** [comment]
Thanks!
This has already been reported in https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/299#issuecomment-501731332 - I'll publish a fix this evening.
