### ISSUE TITLE
Is there a way to cache typechecking (like via cache-loader)?

### ISSUE THREAD

**Issue by deser** [TypeStrong/fork-ts-checker-webpack-plugin#302]
I used ts-loader along with cache loader and seems it helped pretty much. But now with ForkTsCheckerWebpackPlugin I seems unable to do that. Is there a way to cache results of ForkTsCheckerWebpackPlugin?

**Comment by phryneas** [comment]
As they are working very differently, unfortunately not.

(loaders only get one input file and compile that - that can be cached. fork-ts-checker-webpack-plugin checks types for all files in your sources and then watches to only check for differences from there on - that can't be cached by any other loader)
