### ISSUE TITLE
Welcome in the TypeStrong organization

### ISSUE THREAD

**Issue by piotr-oles** [TypeStrong/fork-ts-checker-webpack-plugin#307]
Hello!
I've just transferred this repository from [Realytics](https://github.com/Realytics) to [TypeStrong](https://github.com/TypeStrong) organization 🎉
I hope this will secure the future of this plugin and make it more trustworthy. Please update your origin in local repositories. 

@johnnyreilly @phryneas

**Comment by johnnyreilly** [comment]
That's awesome - great job @piotr-oles!
