### ISSUE TITLE
Error if process.env.WATCH is not defined

### ISSUE THREAD

**Issue by pamls** [TypeStrong/fork-ts-checker-webpack-plugin#309]
## Error
```
\node_modules\fork-ts-checker-webpack-plugin\lib\service.js:49
    : new IncrementalChecker_1.IncrementalChecker(typescript, exports.createNormalizedMessageFromDiagnostic, exports.createNormalizedMessageFromRuleFailure, process.env.TSCONFIG, JSON.parse(process.env.COMPILER_OPTIONS), process.env.CONTEXT, process.env.TSLINT === 'true' ? true : process.env.TSLINT || false, process.env.TSLINTAUTOFIX === 'true', process.env.WATCH === '' ? [] : process.env.WATCH.split('|'), parseInt(process.env.WORK_NUMBER, 10) || 0, parseInt(process.env.WORK_DIVISION, 10) || 1, process.env.CHECK_SYNTACTIC_ERRORS === 'true', process.env.VUE === 'true', resolveModuleName, resolveTypeReferenceDirective);

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (\node_modules\fork-ts-checker-webpack-plugin\lib\service.js:49:399)
    at Module._compile (module.js:635:30)
```

## Expected behavior
It could be good to check if `process.env.WATCH` is defined

## Steps to reproduce the issue
I used an hello world example of Nuxt.js with nuxt-i18n

## Environment
 - **fork-ts-checker-webpack-plugin**: 1.3.7
 - **typescript**: 3.5.3
 - **tslint**: 5.18.0
 - **webpack**: 4.34.0
 - **os**: Windows 10

**Comment by johnnyreilly** [comment]
Would you like to submit a PR? I'm afraid your reproduction isn't plug and play enough for me to look at; we'd need a reproduction repo

**Comment by phryneas** [comment]
We are setting `WATCH` in https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/0c934557928d58e2c10f866dfe0ad9352ee12f13/src/index.ts#L599 before calling the `service.ts`.

The only way this behaviour makes sense to me would be if Windows 10 would delete environment variables with an empty string instead of keeping them. And that would have many more implications.
@johnnyreilly, if I remember correctly you're using Windows for development, right? Could you test that?

**Comment by johnnyreilly** [comment]
I am a Windows user yes - will try and check that when I get some time. (Lots going on right now 😁)

**Comment by piotr-oles** [comment]
@pamls 
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)
