### ISSUE TITLE
Less Verbose Incremental Build Output?

### ISSUE THREAD

**Issue by phil-lgr** [TypeStrong/fork-ts-checker-webpack-plugin#317]
## Feature motivation

This: 

![image](https://user-images.githubusercontent.com/9644867/61297050-665a0d00-a7a9-11e9-997f-bdbdffe3a45c.png)

## Feature description

What about an option to filter out the incremental build output which is *extremely* verbose and has no value AFAIK?

## Feature implementation

Just want to have people thoughts on this

**Comment by phryneas** [comment]
This is not normal and those logs do not look like they are from `fork-ts-checker-webpack-plugin`, but rather from a dependency. (maybe even TypeScript itself)
Do you have any special environment variables like DEBUG set?

**Comment by phryneas** [comment]
`extendedDiagnostics` in your tsconfig could be causing this, too

**Comment by phil-lgr** [comment]
Sorry for the delay

NO special env set, extendedDiagnostics is not set

**Comment by phil-lgr** [comment]
```
client: new ForkTsCheckerWebpackPlugin({
        tsconfig: configPaths.clientTsConfig,
        watch: [configPaths.clientDir, configPaths.commonDir],
        useTypescriptIncrementalApi: true,
        workers: 1,
        silent: !utilities.isWebpackDevServer(),
        logger: {
            error: function(error) {
                console.log(error);
            },
            warn: function(warn) {
                console.warn(error);
            },
            info: function(info) {}
        }
    })
```

when I put silent I get no output, but silent = false output the mega thing.. 🤔

**Comment by phil-lgr** [comment]
ok you are right this is coming from tsc itself or ts loader... I will keep searching, thanks for the input
