### ISSUE TITLE
Make errors more noticable

### ISSUE THREAD

**Issue by Pajn** [TypeStrong/fork-ts-checker-webpack-plugin#32]
This is a great project, thanks for it!

When using this in a project with unit tests and/or a bigger project with multiple builds it is easy to miss errors as you are likely to be viewing another terminal. While errors from the editor is usually enough it would be nice if the errors from this plugin would be more noticeable.

Some ideas:
1. Console log them in the browser via the dev server.
  I don't know if it's possible to hook into webpacks support for this or if a custom web socket server and client script would need to be added.
2. Growl/libnotify notifications

**Comment by johnnyreilly** [comment]
Hi @Pajn,

I too wanted:

> Growl/libnotify notifications

So I built the [fork-ts-checker-notifier-webpack-plugin](https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin).  This might give you what you need.

@piotr-oles - would it be worth mentioning the notifier in the readme of fork-ts-checker-webpack-plugin?

**Comment by Pajn** [comment]
Awesome, that totally solves number 2.

There is not a big need for both but I will keep the issue open for discussion about 1 but feel free to close if it's not interesting.

**Comment by piotr-oles** [comment]
@johnnyreilly - yes, of course, please create pr with modified readme :)

**Comment by piotr-oles** [comment]
@Pajn I cannot find any method in webpack dev server and webpack dev middleware api that could make this possible. Maybe there is a way to hack into webpack dev server internals but it's not an option for the library - there is no guarantee that internals will be backward compatible in next releases :/

Websocket server could be a solution - you could make it as another package and use plugin hooks (like  [fork-ts-checker-notifier-webpack-plugin](https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin) did)
