### ISSUE TITLE
How can add the --fix option to eslint?

### ISSUE THREAD

**Issue by f-jost** [TypeStrong/fork-ts-checker-webpack-plugin#323]
For tslint we can enable the fix option with `tslintAutoFix` but how use the `fix` option for eslint?

**Comment by johnnyreilly** [comment]
Is it possible to to pass an option to `eslintOptions` to trigger this? https://eslint.org/docs/1.0.0/developer-guide/nodejs-api#cliengine

Or can it be driven from `.eslintrc.js` at all?

**Comment by viljark** [comment]
At the moment it is possible to pass fix option to eslint: https://eslint.org/docs/developer-guide/nodejs-api#cliengine

But as the docs state: 

> Files on disk are never changed regardless of the value of fix. To persist changes to disk, call outputFixes().

Which is not implemented in the codebase yet.

**Comment by johnnyreilly** [comment]
So there's no way to do it right now?

**Comment by viljark** [comment]
What I meant is that this is not implemented in `fork-ts-checker-webpack-plugin` codebase.
For my use case I patched the createEslinter.js with patch-package until official support:
```
diff --git a/node_modules/fork-ts-checker-webpack-plugin/lib/createEslinter.js b/node_modules/fork-ts-checker-webpack-plugin/lib/createEslinter.js
index bb6c1f9..6b8a2f6 100644
--- a/node_modules/fork-ts-checker-webpack-plugin/lib/createEslinter.js
+++ b/node_modules/fork-ts-checker-webpack-plugin/lib/createEslinter.js
@@ -19,6 +19,9 @@ function createEslinter(eslintOptions) {
                 return undefined;
             }
             const lints = eslinter.executeOnFiles([filepath]);
+            if (eslintOptions && eslintOptions.fix) {
+                eslint.CLIEngine.outputFixes(lints);
+            }
             return lints;
         }
         catch (e) {

```

**Comment by johnnyreilly** [comment]
Would you consider sending a PR and we could add that support officially?

**Comment by viljark** [comment]
> Would you consider sending a PR and we could add that support officially?

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/342
