### ISSUE TITLE
Webpack compilation does not halt even when errors are present

### ISSUE THREAD

**Issue by ankita240796** [TypeStrong/fork-ts-checker-webpack-plugin#324]
I am using this plugin to check for typescript type errors. The errors are listed on terminal when compiling webpack but the compilation continues and I was not able to find a way to halt the compilation when there are errors. Is there any way to do this?

**Comment by phryneas** [comment]
The whole point of it is that you can transpile indenpendently from the typechecker (typechecking might take >10s while transpiling might only take 2-3 secs). So, for development mode, I would suggest keeping exactly that behaviour for faster development - it will save you a lot of time.

You _can_ set `async: false` which is what you want, but I'd only do that in production builds.

**Comment by ankita240796** [comment]
Thanks for the help @phryneas!

Also is there any way to write the errors to some output file instead of terminal?

**Comment by phryneas** [comment]
Not that I know of. You could use a custom error formatter that returns an empty string and writes output to a file?

**Comment by johnnyreilly** [comment]
> You can set `async: false` which is what you want, but I'd only do that in production builds

Exactly that. Ideally I'd like the `async` field value to be driven by webpack mode: https://webpack.js.org/configuration/mode/

i.e. `async: mode !== 'production'`

So when `mode` is `'production'` then `async: false` and otherwise `async: true`

Haven't figured out if you can access `mode` in a plugin though...
