### ISSUE TITLE
Error on Module Not Found

### ISSUE THREAD

**Issue by birender** [TypeStrong/fork-ts-checker-webpack-plugin#327]
![error](https://user-images.githubusercontent.com/1873263/62965807-65a5ac80-be23-11e9-92e5-4a8b59d2f08f.png)
Hi All,
Error Throw when I run npm run dev

Please assist me

**Comment by phryneas** [comment]
Do you have any indication that this has anything to do with fork-ts-checker-webpack-plugin?
Without further information on why you think it could have anything to do with your problem, I don't think we can help you.
