### ISSUE TITLE
preserveSymlinks option not honored

### ISSUE THREAD

**Issue by ryedin** [TypeStrong/fork-ts-checker-webpack-plugin#332]
## Current behavior
If you have folders of code that are symlinked into src (very common pattern for monorepo style development), the type checker does not re-trigger when those files are changed. 

## Expected behavior
I should be able to make changes to those symlinked files and have the typechecker correctly re-run checks.

## Steps to reproduce the issue
Setup a basic CRA app with typescript enabled. Have another folder of typescript code sitting as sibling to your project. Create a symlink within the CRA `src` folder to your "shared" folder.
add `"preserveSymlinks": true,` to your `tsconfig.json`.

If you create a typescript error on purpose in the shared code and start the app you will observe the checker does correctly pick up the code and display the error. However, if you fix the error, the checker does not automatically re-check as it would if the file lived natively in the CRA app's `src` dir. 

## Environment
 - **fork-ts-checker-webpack-plugin**: 1.5.0 (from current version of CRA scripts)
 - **typescript**: 3.5.3
 - **tslint**: N/A
 - **webpack**: 4.39.1 (current version in CRA)
 - **os**: Mac 10.13.3 (AND Ubuntu 18.04)

**Comment by johnnyreilly** [comment]
Thanks for the detailed report. I'm afraid I'm not able to look at this myself right now. This is definitely functionality we would want. If you'd like to take a look we're happy to look at PRs and collaborate!

**Comment by gyancse08** [comment]
I think this problem is coming from chokidar, https://github.com/paulmillr/chokidar/issues/696.
They fixed it in the version 3.x. We only need to update the version here.

**Comment by gyancse08** [comment]
> I think this problem is coming from chokidar, [paulmillr/chokidar#696](https://github.com/paulmillr/chokidar/issues/696).
> They fixed it in the version 3.x. We only need to update the version here.

I was trying to create a branch for this fix but I am not able to publish my branch due to access to this repo. Could you please provide me the access?

**Comment by johnnyreilly** [comment]
Hi @gyancse08,

Thanks for looking into this! Please could you fork the fork-ts-checker-webpack-plugin repo, work on that and send a pull that way?

**Comment by gyancse08** [comment]
When I publish my branch I am getting this error: 
"You do not have permission to access this repository". 

only change is following, I will appreciate if someone else fixes the same.

-    "chokidar": "^2.0.4",
+   "chokidar": "^3.2.1",

-    "@types/chokidar": "^1.7.5",
+   "@types/chokidar": "^2.1.3",

**Comment by phryneas** [comment]
You need to fork this project, push the changes to a branch on your fork and then send a pull request, that's the "github workflow". :)
Here's some more information: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by piotr-oles** [comment]
@ryedin
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)

**Comment by J-Rojas** [comment]
@piotr-oles Hi, the v5.0.0@beta fixed the problem for me within my npm@7 workspace project. However, the v6 master branch detects a change, but it continues to compile with the previous file contents of the symlinked file, not the new contents. Have these commits been merged into the latest master?
