### ISSUE TITLE
.tsx files are not type checked

### ISSUE THREAD

**Issue by jeffijoe** [TypeStrong/fork-ts-checker-webpack-plugin#338]
## Current behavior
`.tsx` files are not type checked. This can be fixed in userland with a `reportFiles` option.

## Expected behavior
Since `ts-loader` is configured for `.tsx`, I thought it would also check `.tsx` files.

## Steps to reproduce the issue
Use the `README` config, then add a `.tsx` file with a type error in it.

## Environment
 - **fork-ts-checker-webpack-plugin**: 1.5.0
 - **typescript**: 3.5.2
 - **tslint**: 5.18.0
 - **webpack**: 4.38.0
 - **os**: macOS Mojave

**Comment by phryneas** [comment]
The `fork-ts-checker-webpack-plugin` uses the `files`/`include`/`exclude` rules of your `tsconfig.json` - are you maybe missing `tsx`files there?

**Comment by jeffijoe** [comment]
I didn't use `includes` as `ts-loader` doesn't seem to care about it. But that makes sense!

**Comment by johnnyreilly** [comment]
Might be worth comparing your setup to this: https://github.com/TypeStrong/ts-loader/tree/master/examples/fork-ts-checker-webpack-plugin

I can say for sure that the checker checks tsx. 😁

**Comment by jeffijoe** [comment]
Well damn it, reverted my changes and now it works. Classic. 😂

Sorry about the false positive! No idea why it didn't work before, but I swear I'm not crazy. 😅
