### ISSUE TITLE
ESLint: "fork-ts-checker-webpack-plugin" is not published. (node/no-unpublished-require) for devDependencies

### ISSUE THREAD

**Issue by davidmpaz** [TypeStrong/fork-ts-checker-webpack-plugin#34]
Hi, 

i think this issue is related to #23.

the difference is that when adding plugin as `devDependencies` linter complains.

Is there something that could be done for avoiding this one too?

many thanks in advance

**Comment by piotr-oles** [comment]
Please checkout description of https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md :)

> Then this rule warns require() expressions in *published* files if the require() expression imports *unpublished* files **or the packages of devDependencies**

**Comment by davidmpaz** [comment]
Sorry for reporting this then. I think i did not understood right since begining
