### ISSUE TITLE
Add a custom hook before checker run

### ISSUE THREAD

**Issue by inori1707** [TypeStrong/fork-ts-checker-webpack-plugin#341]
## Feature motivation

Sometime we want to delay type checking until some tasks done. In my case, it should wait for CSS module type definition files generated. It can be done with `serviceBeforeStart` hook in production build, but not for watch mode because this plugin use single checker service in watch mode and `serviceBeforeStart` hook triggered only in initial build.

## Feature description

Call a custom hook before type checker run

## Feature implementation

Just like `serviceBeforeStart` hook but called when type checker is about to be run

**Comment by johnnyreilly** [comment]
Would you like to try something out and raise a prospective PR?

**Comment by inori1707** [comment]
Sorry about my misunderstanding, the `serviceBeforeStart` hook should work as expected.
