### ISSUE TITLE
Logging To stderr Breaks VSTS Builds

### ISSUE THREAD

**Issue by johnbouma** [TypeStrong/fork-ts-checker-webpack-plugin#349]
## Current behavior
The change fixing #321 breaks our automated build system (VSTS) which relies on stderr to determine if any errors have occurred during the build process.  

## Expected behavior
I would expected *errors* to be written to stderr and other logging to be written to stdout.

## Steps to reproduce the issue
Define a build process that properly utilizes stderr to provide error logging for each step, a build using this package will execute properly for version 1.5.0 and will break for version 1.5.1.

## Environment
 - **fork-ts-checker-webpack-plugin**: [1.5.1]
 - **typescript**: [3.6.4]
 - **webpack**: [4.41.2]

**Comment by johnnyreilly** [comment]
Ah - https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/345#merged-event which reverted this was never published as the commit didn't have a `fix:` prefix... See https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/CONTRIBUTING.md#examples

Would you like to send an "empty" PR (just add a line break to the readme or similar) with a `fix: ` prefix on the commit? I'll merge it and trigger a release.

**Comment by johnbouma** [comment]
Can do once I get to the office

**Comment by johnnyreilly** [comment]
Don't worry - #334 should handle this
