### ISSUE TITLE
INTERNAL ERROR: Cannot read property 'fileNames' of undefined

### ISSUE THREAD

**Issue by TokugawaTakeshi** [TypeStrong/fork-ts-checker-webpack-plugin#350]
## Current behavior
INTERNAL ERROR: Cannot read property 'fileNames' of undefined when use `fork-ts-checker-webpack-plugin` instead of build-in TypeScript type checker

## Expected behavior
No this error

## Steps to reproduce the issue
1. I'll share to you [my project](https://github.com/TokugawaTakesi/issue-fork_ts_checker_webpack_plugin-1) during this issue is being opened. Please clone or download it.
2. In project directory, execute `npm i && npm run developmentBuild`. Once dependencies will be installed, webpack build will start.
3. You will see `INTERNAL ERROR: Cannot read property 'fileNames' of undefined` in your console.

![image](https://user-images.githubusercontent.com/41653501/67458673-c77b6180-f671-11e9-83bf-675f809288b8.png)

4. Make sure that this error will not occur without your plugin. Comment out line 48 (`transpileOnly: true`), and also rows 73-76 in `webpack.config.js`. 

5. Re-run ` npm run developmentBuild`. This time console will be clean:

![image](https://user-images.githubusercontent.com/41653501/67458903-47a1c700-f672-11e9-85ad-6a04479506aa.png)

6. If make somewhere the mistake intentionally, (e. g. write `const a;`) and save the file, you will see the errors casted by build-in TypeScript type checker:

![image](https://user-images.githubusercontent.com/41653501/67458975-6ef89400-f672-11e9-901e-566a4b0c15b8.png)

## Environment
 - **fork-ts-checker-webpack-plugin**: 1.6.0 (newest)
 - **typescript**: 3.6.3
 - **tslint**: 5.20.0 (but it is not integrated in webpack config, just for IDE highlight)
 - **webpack**: 4.40.2
 - **os**: Windows 10 Pro

**Comment by johnnyreilly** [comment]
Thanks for the repo. It's quite large and so that doesn't make diagnosis easy. Would you be able to confirm if your issue presents with fork-ts-checker-webpack-plugin@1.5.0 ? I'm curious as to whether there's a regression or if this might be user error

**Comment by TokugawaTakeshi** [comment]
Thank you for the quick response.

Unfortunately, nothing changed with `fork-ts-checker-webpack-plugin@1.5.0 `.

> It's quite large and so that doesn't make diagnosis easy.

This bug occurred also in my other smaller project. You can use [this project](https://github.com/TokugawaTakesi/issue-fork_ts_checker_webpack_plugin-2) for investigations instead. This time npm command is long, so please use copy-paste to execute it:
```
npm run SourceCodeCompilingAndBunding:DevelopmentBuild
```

**Comment by phryneas** [comment]
Okay, this took me too long to debug. No it's not a bug.
In your webpack config, you have to set the whole path to the tsconfig, including the filename, not just the folder:

```
 new ForkTsCheckerWebpackPlugin({
          tsconfig: Path.resolve(__dirname)
        })
```

this is wrong.

**Comment by TokugawaTakeshi** [comment]
@phryneas,

You right, my mistake. Thank you for the investigation.
Well, this is not a bug, but could I call it "non-accurate error message"?
Could you please to determine the error like this in the future and output the error "Incorrect file path to 'tsconfig.json'"?
