### ISSUE TITLE
upgrade chokidar version

### ISSUE THREAD

**Issue by lygstate** [TypeStrong/fork-ts-checker-webpack-plugin#360]
## Environment
 - **fork-ts-checker-webpack-plugin**: [version from the `package.json`]
 - **typescript**: [version from the `package.json`]
 - **tslint**: [version from the `package.json`]
 - **webpack**: [version from the `package.json`]
 - **os**: [e.g. Ubuntu 19.04]

**Comment by ianschmitz** [comment]
This can be closed it looks like?

**Comment by johnnyreilly** [comment]
Done! It shipped with version 3.1.1
