### ISSUE TITLE
Take v4 from beta to released!

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/fork-ts-checker-webpack-plugin#375]
Hey @piotr-oles,

What do you think about releasing v4.0.0?  I've been testing with them in some projects of mine since Christmas and have had a great experience so far.

I think this could be ready to release!

**Comment by piotr-oles** [comment]
Hi @johnnyreilly , I think it's a good idea  🚀

**Comment by piotr-oles** [comment]
It seems that semantic-release finally published a stable version 16. Maybe it's worth to update it before releasing v4.0.0?

**Comment by johnnyreilly** [comment]
Go for it!
