### ISSUE TITLE
Memory leak: service.js process is running after node heap out of memory crash

### ISSUE THREAD

**Issue by vlamitin** [TypeStrong/fork-ts-checker-webpack-plugin#387]
## Current behavior

Every time [node falls with Heap out of memory](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/271), the `<project>/node_modules/fork-ts-checker-webpack-plugin/lib/service.js` is still running, causing memory leak. The more crashes: the more service.js processes causing leak

## Expected behavior

Proper shutdown of all running services

## Steps to reproduce the issue

- run `node --max-old-space-size=256 ./node_modules/.bin/webpack-dev-server` on any mid-size webpack+typescript+react project
- wait node `Heap out of memory` crash
- `ps aux | grep fork-ts-checker`

## Environment
 - **fork-ts-checker-webpack-plugin**: 4.0.4
 - **typescript**: 3.7.4
 - **tslint**: 5.11.0
 - **webpack**: 4.19.1
 - **os**: linux mint 19.1

**Comment by piotr-oles** [comment]
@vlamitin
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version which should resolve this issue 🚀
I will close this issue to clean-up the backlog. If this release didn't solve the issue, we can re-open this :)

**Comment by IanVS** [comment]
Was the alpha released to the 4.x branch?  It seems to not exist anymore, and I am getting out of memory errors using 4.1.6.  I'm unable to upgrade to version 5 for now, because I am stuck on Node 8.

**Comment by piotr-oles** [comment]
Unfortunately, the alpha was released on the 5.x branch
