### ISSUE TITLE
4.0.0 should have release notes

### ISSUE THREAD

**Issue by IronSean** [TypeStrong/fork-ts-checker-webpack-plugin#388]
This is more a minor documentation ask:

Release 4.0.0 currently has no release notes, they all appear to be scattered among several beta releases. But as a user of the library who didn't use the beta releases, I would rather have the breaking changes collated with the actual release, rather than having to pick through beta releases and figure out if the changes are cumulative, or if some invalidate other beta changes, etc.

**Comment by piotr-oles** [comment]
Thanks for reporting - I didn't notice. There was an issue with the `semantic-release` process and because of that, release notes haven't been generated. I did it manually: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v4.0.0
