### ISSUE TITLE
allow override `include` and `exclude` of  `tsconfig` in options

### ISSUE THREAD

**Issue by aprilandjan** [TypeStrong/fork-ts-checker-webpack-plugin#391]
## Feature motivation

I have a project which mixed js and ts files, using webpack/babel7/ts to compile all files. I need to manually make webpack ts-check-plugin check less files(only include `ts` `tsx`), but still keep the actual `tsconfig` in project root including all `ts` `tsx` `js` `jsx` files(for vsc support & eslint validation purposes).

## Feature description

Currently the plugin support override tsconfig `compilerOptions` object, not including `include` `exclude`. And when using `useTypescriptIncrementalApi: true `,  it seems there's no way to reduce watched files(see https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/303)

If we can override `include` `exclude` of `tsconfig`, then users have more confidence over the processed files. 

## Feature implementation

Provide extra config option `include` `exclude` for plugin constructor. When defined, merge these options into loaded `tsconfig` and pass it to tsc.

**Comment by piotr-oles** [comment]
Hi :) You can create a separate `tsconfig.only-ts.json` file that will extend from `tsconfig.json` and use that file in the `ForkTsCheckerWebpackPlugin` by specifying `tsconfig` option

**Comment by aprilandjan** [comment]
@piotr-oles your solution is good, I didn't really thought of that. Thanks!

**Comment by joebnb** [comment]
same problem i have,did this issue has any plan in future?

**Comment by joebnb** [comment]
in my case,i need take tsconfig.json out of project,and it seems no context ,in ts loader it was works well 
![image](https://user-images.githubusercontent.com/1646883/82293579-5c172980-99df-11ea-9379-80fd3d8712ce.png)
