### ISSUE TITLE
Build stops after 40% in node js project with npm serve command

### ISSUE THREAD

**Issue by bitquality** [TypeStrong/fork-ts-checker-webpack-plugin#407]
## Current behavior
Build stops after 40% in node js project with npm serve comand

## Expected behavior
Output errors and stop from hanging.

## Steps to reproduce the issue
   setup vue cli project and below configuration

`Starting type checking service...
Using 1 worker with 2048MB memory limit
40% building 220/229 modules 9 active usr\abc\node_modules\querystring-   es3\encode.js`

I used below vue.config.ts to disable it but doesnt stop it from whats it doing

`
// in vue.config.js
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = {
  configureWebpack: (config) => {
    // Skip Typechecking on serve
    if (process.env.NODE_ENV === 'development') {
      config.plugins = config.plugins.filter((p) => !(p instanceof ForkTsCheckerWebpackPlugin));
    }
  },
};
`

**Comment by piotr-oles** [comment]
Hi!

> I used below vue.config.ts to disable it but doesnt stop it from whats it doing

Maybe this issue is not related to this plugin directly? Could you provide a reproduction repository?

**Comment by piotr-oles** [comment]
I'm closing as there is not enough information to reproduce the issue :)
