### ISSUE TITLE
Bump babel dependency to @babel/code-frame

### ISSUE THREAD

**Issue by andyrooger** [TypeStrong/fork-ts-checker-webpack-plugin#408]
## Feature motivation

I have a large project that's having issues with conflicting versions of `chalk` being installed. Wrong versions are being picked up in places (which is the individual package's fault).

`fork-ts-checker-webpack-plugin` has a dependency on `babel-code-frame` which in turn pulls in `chalk@1`. For me this is the only package that uses `chalk@1` so I'd like to be able to update it.

Looks like the babel package has now been renamed to `@babel/code-frame` which is where any updates are being published. That depends on `chalk@2` so allows me to update and hopefully drop the conflict.

## Feature description

Reference the new `@babel/code-frame` package in package.json to allow users to upgrade it

**Comment by johnnyreilly** [comment]
I believe that @piotr-oles has already done the upgrade in the beta he's working on.... I don't know how far away from shipping that is. If it's going to be a while then I suspect we'd be open to a PR 🤗

**Comment by piotr-oles** [comment]
The stable version of the plugin will not be released very soon - it's a major rewrite with breaking changes. We will release alpha and beta versions first. So if you don't want to wait, feel free to open a PR :)

**Comment by andyrooger** [comment]
I'll get on it!
