### ISSUE TITLE
process env is not passed to child process

### ISSUE THREAD

**Issue by pranava** [TypeStrong/fork-ts-checker-webpack-plugin#41]
https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/46fe4212840d028341cd70a1164f069b8d03e35d/lib/index.js#L245-L251

The parent process' env variables such as NODE_PATH are not passed to the child process; hence if you have a localized build env with non standard library paths, the child process' won't be able to load dependencies such as typescript.

A simple fix is to just add a NODE_PATH: process.env.NODE_PATH field here. A more catch all solution would be to merge this local set of params with process.env and pass the result to the child process. Thoughts? Thanks!

**Comment by piotr-oles** [comment]
Thank you for reporting and PR :)
