### ISSUE TITLE
[bug]webpack will hang out and not break progress if set bail=true

### ISSUE THREAD

**Issue by Sara2009** [TypeStrong/fork-ts-checker-webpack-plugin#411]
"webpack": "^4.41.5"
"fork-ts-checker-webpack-plugin": "^4.1.3"

```js
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
module.exports = {
    ...
    bail: true,
    plugins: [
        new ForkTsCheckerWebpackPlugin({
            async: true,
        }),
        ...
    ],
    ...
}
```
![image](https://user-images.githubusercontent.com/9332442/82724336-e923f080-9d07-11ea-9675-94cc957c4ce2.png)

**Comment by piotr-oles** [comment]
Hi! Could you provide a minimal reproduction repository?

**Comment by Sara2009** [comment]
> Hi! Could you provide a minimal reproduction repository?

https://github.com/Sara2009/bug-fork-ts-checker-webpack-plugin

run `npm run build`

`src/js/index.tsx` has an error `import App from './apps'`. The filename `apps` is wrong. I set bail=true in webapck.confg.js. The progress will hang on. If i remove the fork-ts-checker-webpack-plugin. Webpack will break.

**Comment by piotr-oles** [comment]
Thank you for this repository. I found the bug and I will create PR soon :)
