### ISSUE TITLE
5.0.0-alpha.2: ESLint support only seems to work on initial compile, not on changes

### ISSUE THREAD

**Issue by eamodio** [TypeStrong/fork-ts-checker-webpack-plugin#414]
## Current behavior

ESLint seems to only run on the initial compile, not on recompile (watch) after changes

## Expected behavior

ESLint should run in both scenarios

## Steps to reproduce the issue

Enable ESlint, have no ESLint issues on initial watch, then add an ESLint error

## Environment
 - **fork-ts-checker-webpack-plugin**: [5.0.0-alpha.2]
 - **typescript**: [3.9.3]
 - **eslint**: [7.1.0]
 - **@typescript-eslint/eslint-plugin**: [3.0.0]
 - **webpack**: [4.43.0]
 - **os**: [Windows 10]

**Comment by piotr-oles** [comment]
Could you send a `webpack.config.js` file?

**Comment by eamodio** [comment]
https://github.com/eamodio/vscode-gitlens/blob/develop/webpack.config.js

**Comment by eamodio** [comment]
Looks great -- thanks!
