### ISSUE TITLE
Plugin and base Typescript works different

### ISSUE THREAD

**Issue by inomdzhon** [TypeStrong/fork-ts-checker-webpack-plugin#434]
## Current behavior
1. Doesn't know about `// @ts-expect-error`.
2. (please, look **Steps to reproduce the issue** section)

## Expected behavior
1. Know about `// @ts-expect-error`.
2. (please, look **Steps to reproduce the issue** section)

## Steps to reproduce the issue

1. Set `// @ts-expect-error` to somewhere.
![image](https://user-images.githubusercontent.com/5850354/83447357-fd2ec700-a458-11ea-9e1a-3a60edc200ac.png)
Maybe because ts-expect-error it's [new feature](https://github.com/microsoft/vscode/pull/92093).

2. Base Typescript checker say it's fine (**it's expected**)
![image](https://user-images.githubusercontent.com/5850354/83447588-5a2a7d00-a459-11ea-9031-5f050d8464fb.png)
`fork-ts-checker-webpack-plugin` doesn't
![image](https://user-images.githubusercontent.com/5850354/83447618-66163f00-a459-11ea-9f66-337d1a674907.png)

## Other context
My config
```
new ForkTsCheckerWebpackPlugin({
  async: false,
  typescript: {
    tsconfig: path.resolve('./tsconfig'),
    mode: 'write-references', // Because we use babel-loader.
    diagnosticOptions: {
      syntactic: false,
      semantic: true,
      declaration: false,
      global: false,
    },
  },
}),
```
## Environment
 - **fork-ts-checker-webpack-plugin**: 5.0.0-alpha.14
 - **typescript**: 3.9.3
 - **eslint**: -
 - **webpack**: 4.41.6
 - **os**: MacOS Catalina 10.15.5

**Comment by piotr-oles** [comment]
Thank you for reporting this issue.
Could you check if `./node_modules/.bin/tsc -p tsconfig.json --watch` also doesn't report an error?

**Comment by inomdzhon** [comment]
@piotr-oles ohhh 😲 It does!

My tsconfig is
```
// @toolchain/typescript/tsconfig.json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "esnext",
    "newLine": "lf",
    "declaration": true,
    "strict": true,
    "importHelpers": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true
  }
}
```

```
// tsconfig.json
{
  "extends": "@toolchain/typescript/tsconfig.json",
  "compilerOptions": {
    "baseUrl": "js",
    "jsx": "react",
    "allowJs": false,
    "skipLibCheck": true,
    "declaration": false,
    "typeRoots": ["./node_modules/@types"]
  },
  "exclude": ["node_modules"],
  "include": ["./js/**/*.ts", "./js/**/*.tsx"]
}
```

Can you guess where the problem is?

**Comment by phryneas** [comment]
Probably your IDE does not use the TypeScript version of your repository. If it's VSCode, click on the version number in the bottom right corner and in the menu that pops up choose "Use Workspace Version".

**Comment by inomdzhon** [comment]
Oops...sorry guys...it turns out I have two versions of tsc 😅 One is version 3.7.5 and other 3.9.3.
What's option for set custom tsc compiler in fork-ts-checker-webpack-plugin version 5.0.0-alpha.14? I couldn't find in docs for [alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha)

**Comment by piotr-oles** [comment]
There is no such option in the `alpha` version. Why do you have two versions of tsc? :)

**Comment by inomdzhon** [comment]
Now I try to explain :D 

We use monorepo and have next structure:
- `/packages`
- `/src` – exactly should be /projects in the future
  - `/js` – here some `*.ts` files
  - config.local.js – provide configs for `fork-ts-webpack-plugin` in `toolchain/webpack`
  - `tsconfig.json`
- /toolchain
  - /typecsript – here is typescript is version 3.9.3
  - /webpack
- package.json – here is we have some dependencies which have typescript version 3.7 in required dependencies :(

In major version do you add option for set custom path to typescript?

**Comment by piotr-oles** [comment]
I don't have plans to implement it as it will complicate the source code and make it harder to maintain. If you want to use a different version of typescript, you can install the plugin in the `toolchain` directory and then import it from this directory 
```js
const ForkTsCheckerWebpackPlugin = require('../toolchain/node_modules/fork-ts-checker-webpack-plugin');
``` 
Based on the node modules resolution algorithm, it should use typescript 3.9.3.

**Comment by inomdzhon** [comment]
It's a pity 😔

Anyway all works! I back to version 4 and use custom path to typescript

Thanks u folks 😀
