### ISSUE TITLE
Type checking errors on Windows OS only, due to pnpapi case sensitivity.

### ISSUE THREAD

**Issue by dalinarkholin** [TypeStrong/fork-ts-checker-webpack-plugin#447]
## Current behavior

When using Yarn 2 with PNP enabled(it is by default) we get unexpected type errors we don't see in a Linux like environment.

## Expected behavior

Same results across environments when PNP is in the equation. When using PNP it expects case sensitivity to be true.

forcing this line to true resolves the problem
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/4cf0b7d4c0227e6e128c56fd4ec589383f880811/src/typescript-reporter/reporter/ControlledTypeScriptSystem.ts#L50

## Solutions

@arcanis what have you been recommending for solutions to pnp incompatibility? optional args/options? some sort of process.env check?

## Environment
 - **fork-ts-checker-webpack-plugin**: npm:5.0.0-beta.7
 - **typescript**: 3.9.5

**Comment by arcanis** [comment]
Can you share a repro and the error logs?

One note: on Windows, `ts.sys.useCaseSensitivityFileNames` should be `true` when using PnP (we [enforce this](https://github.com/microsoft/TypeScript/pull/35206/files#diff-cc0eed295cd2bad794329f871b2669fd)). This is expected, because the PnP API is case sensitive.

**Comment by dalinarkholin** [comment]
@arcanis yeah you are right. I am not seeing this issue in a minimal project with just webpack, typescript, and fork-ts-checker-webpack-plugin . `ts.sys.useCaseSensitivityFileNames` must be getting overwritten from another module in our projects webpack configuration. I'll open up something similar once I track down the actual culprit. Thanks!
