### ISSUE TITLE
Port to TypeScript?

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/fork-ts-checker-webpack-plugin#45]
Hello!

I've always wondered why this isn't actually written in TypeScript (given that's what it provides checking for).  I'm currently hacking locally on porting this to TypeScript.  For the most part I just want to see how hard it would be to do (not hard I suspect).  

Would you be interested in a PR for this assuming all goes well?

**Comment by johnnyreilly** [comment]
Also, there might me a minor perf gains as I can kill some `bind`s (notoriously slow)

**Comment by piotr-oles** [comment]
I wrote it in a pure javascript to keep things simple :) It's easier to debug and develop small plugin in javascript :) But as it becomes bigger and currently is stable (I think), rewriting it to TypeScript could be a good step forward to maintain growing complexity of the plugin :)
