### ISSUE TITLE
customize typescript path

### ISSUE THREAD

**Issue by shaodahong** [TypeStrong/fork-ts-checker-webpack-plugin#451]
## Current behavior

Before `5.0.0` version, typescript support customize path resolve, like `{ typescript: require.resolve(path) }`, but after `5.0.0` version, i don't set this

In my project, typescript is optional, so I don't want to install ts when create

## Environment
 - **fork-ts-checker-webpack-plugin**: [`5.0.1`]
 - **typescript**: [version from the `package.json`]
 - **eslint**: [version from the `package.json`]
 - **webpack**: [`4.43.0`]
 - **os**: [e.g. Ubuntu 19.04]

**Comment by piotr-oles** [comment]
You can use `typescript: { enabled: false }` to disable typescript support. Is it something that solves your issue?

**Comment by shaodahong** [comment]
No, I want to set a special ts path to resolve

**Comment by piotr-oles** [comment]
Then it's not possible to do starting from 5.0.0. It was removed to simplify the codebase and therefore make it easier to maintain.
I don't understand the reason why you would like to set a custom path of the typescript. Could you elaborate a little bit more about your use-case? Maybe I could help you or you could convince me to add support for this feature in version 5 :)

**Comment by shaodahong** [comment]
Example project

```
├── toolChain(Build tool)
│   ├── node_modules
│   ├── bin
├── project
│   ├── node_modules
│   ├── ├──typescript
│   ├── ├──toolChain (symbol link)
```

when I run `webpack dev`, has error `Error: Cannot find module 'typescript'`

**Comment by piotr-oles** [comment]
Sorry, but we don't have a plan to support this setup in next versions :) I think that this plugin should not fix issues with node_modules resolution

**Comment by shaodahong** [comment]
It's ok, thanks for your quick replay
