### ISSUE TITLE
Typo in README 

### ISSUE THREAD

**Issue by JoshRobertson** [TypeStrong/fork-ts-checker-webpack-plugin#455]
`infastructure` in `logger` default value should be `infrastructure` I assume?

**Comment by piotr-oles** [comment]
No, the default configuration is to not log infrastructure logs at all :)

**Comment by JoshRobertson** [comment]
> No, the default configuration is to not log infrastructure logs at all :)

My comment is just that the word is spelled wrong on the README. it is written as `infastructure` which is incorrect. Normally I wouldn't comment but because it's a code snippet someone might copy and paste, it could be annoying.

**Comment by piotr-oles** [comment]
Ah, ok :) Would you like to create a PR?

**Comment by JoshRobertson** [comment]
Another typo:

`diagnosticsOptions` is wrong. the field in the code is `diagnosticOptions`
