### ISSUE TITLE
Fail build on ESLint warnings

### ISSUE THREAD

**Issue by amanmahajan7** [TypeStrong/fork-ts-checker-webpack-plugin#465]
## Feature motivation

Currently we are using `eslint-loader` that provides a `failOnWarning` flag that causes the module build to fail if there are any warnings. 
https://github.com/webpack-contrib/eslint-loader#failonwarning

I tried setting `max-warnings: 0` but it does not affect the build. 

## Feature description

Probably add a new ESLint option
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#eslint-options

**Comment by piotr-oles** [comment]
I think it's outside of the scope of this plugin. The webpack is responsible for that behavior and if you would like to have an option to fail on warnings, you could:
 * create PR on webpack to add `failOnWarning` option or something similar,
 * use existing webpack plugin or create your own to fail on warning
 * map issues from warning to error using hook exposed by this plugin
