### ISSUE TITLE
Getting `TypeError: dirent.isDirectory is not a function` on startup

### ISSUE THREAD

**Issue by bwesner** [TypeStrong/fork-ts-checker-webpack-plugin#469]
## Current behavior
Getting this error on a basic startup.

## Expected behavior
To not get this error.

## Steps to reproduce the issue
Copy the files in this example locally: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/ad0eac9ed09701cd0369f7ccc3579742c22be63f/examples/ts-loader

Then, run `npm install`. Then, run `npm run dev`. The error will present itself at this time.

## Issue reproduction repository
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/ad0eac9ed09701cd0369f7ccc3579742c22be63f/examples/ts-loader

## Environment
all npm modules straight from that example. You can also upgrade `fork-ts-checker-webpack-plugin` to the latest version and still get it. My OS is MacOS Mojave 10.14.6

**Comment by piotr-oles** [comment]
Hi!
Thanks for reporting this issue. Unfortunately, I wasn't able to reproduce it. I was following the steps, but I didn't encounter any issues. Could you try to create a docker file or virtual machine image in which this problem exists?

**Comment by bwesner** [comment]
I tried again and wasn't able to reproduce. I'm not 100% sure but I think it was my node version, i might have been on v10 before.

Thanks anyway.
