### ISSUE TITLE
Add "typescript" option from v4 back in some form

### ISSUE THREAD

**Issue by onigoetz** [TypeStrong/fork-ts-checker-webpack-plugin#474]
## Feature motivation
Hi, In v4 there was a "typescript" option which did

> typescript string: If supplied this is a custom path where typescript can be found. Defaults to require.resolve('typescript').

This option was especially useful in the case of multi-module projects or projects that bundle webpack and its configuration in a separate dependency for reusability (I'm the maintainer of https://github.com/swissquote/crafty, one of such tools).

Would you accept a Pull Request that adds this feature back ?

## Feature description

Add an option `typescriptPath` ( I'm open to propositions for the name :) )
That defaults to `require.resolve("typescript")` and allows to be changed with the path to another TypeScript module if needed.

## Feature implementation

* Add option to schema
* Load instance on configuration init
* Change all references to the import in `TypeScriptReporterConfiguration`, `TypeScriptIssueFactory`, `TypeScriptPerformance`, `ControlledTypeScriptSystem`, `ControlledWatchCompilerHost`, `TypeScriptConfigurationParser` and `TypeScriptReporter` with references to the instance loaded from the configuration

**Comment by johnnyreilly** [comment]
Hey @onigoetz!

I suspect this would be good to add back - @piotr-oles what are your thoughts?
