### ISSUE TITLE
checkSyntacticErrors option missing

### ISSUE THREAD

**Issue by ansf** [TypeStrong/fork-ts-checker-webpack-plugin#477]
ts-loader recommends enabling the checkSyntacticErrors option when using happyPackMode in order to also catch syntax errors (see https://github.com/TypeStrong/ts-loader#happypackmode).

However it seems like this option is not available anymore. This is the error I get:

```
ForkTsCheckerWebpackPlugin Invalid Options

options should NOT have additional properties

ValidationError: ForkTsCheckerWebpackPlugin Invalid Options
    at Object.validateOptions [as default] (./node_modules/schema-utils/src/validateOptions.js:32:11)
```

I could not find anything related in the changelog. Should we use eslint now to catch that kind of issues?

## Environment
 - **fork-ts-checker-webpack-plugin**: [5.7.0]
 - **typescript**: [3.9.5]
 - **eslint**: [7.3.1]
 - **webpack**: [4.43.0]
 - **os**: [macOS 10.15.5]

**Comment by johnnyreilly** [comment]
I wouldn't recommend using happypack anymore; `fork-ts-checker-webpack-plugin` by itself should be enough. (Maintainer of ts-loader here)

**Comment by ansf** [comment]
I tried to use happyPack because I wanted to use thread-loader, but the build time improvements are actually small compared to just using `transpileOnly` without thread-loader. So I am fine with not using happyPack. However I think it would be nice if we could clarify the readme of ts-loader.

What do you mean by `fork-ts-checker-webpack-plugin` by itself should be enough? Without any options it does not catch syntax errors e.g. `const a = [{} {}]`.

**Comment by piotr-oles** [comment]
You can use same settings as for babel-loader: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/examples/babel-loader/webpack.config.js :)

**Comment by johnnyreilly** [comment]
I'm suggesting not using happypack mode essentially

https://blog.johnnyreilly.com/2018/12/you-might-not-need-thread-loader.html

**Comment by johnnyreilly** [comment]
> I tried to use happyPack because I wanted to use thread-loader, but the build time improvements are actually small compared to just using transpileOnly without thread-loader. So I am fine with not using happyPack. However I think it would be nice if we could clarify the readme of ts-loader.

Sure - if you'd like to submit a docs PR I'll happily take a look!

**Comment by ansf** [comment]
thank you for all your input. i will make a PR to update the ts-loader readme.
