### ISSUE TITLE
Emit and bundle the definitions?

### ISSUE THREAD

**Issue by JasonKleban** [TypeStrong/fork-ts-checker-webpack-plugin#49]
I'm using webpack 3, ts-loader, and `transpileOnly: true` along with this fork-ts-checker-webpack-plugin.  

My `ts-config.json` has `"declaration": true`, but I don't think I'm getting the type definitions because of `transpileOnly: true` which makes sense to me, since I didn't allow ts-loader to perform the computation of the types.  

If that's the true cause, is there a way to output the definitions computed during this ts-checker phase?  And is there a way to further bundle those definitions as webpack already does for the output .js file?

Thanks!

**Comment by johnnyreilly** [comment]
Personally I've never used webpack in combination with `"declaration": true` and so I may not be fully understanding your setup.  but Would it work if you had a separate process that generated the type definitions.  So, another npm script that you used to just run `tsc` against to generate `*.d.ts` files?  Just a thought... (not necessarily a useful one)

**Comment by piotr-oles** [comment]
I've just checked `typescript.d.ts` and there is a method:
```
emit(targetSourceFile?: SourceFile, writeFile?: WriteFileCallback, cancellationToken?: CancellationToken, emitOnlyDtsFiles?: boolean, customTransformers?: CustomTransformers): EmitResult;
```
on `Program` class.
The fourth argument called `emitOnlyDtsFiles` might be something you are interested in. I don't have a time to implement this in near future so PR's are welcome :)

**Comment by severen** [comment]
This also affects people who are using Webpack programmatically as part of a larger tool which is written in TypeScript, such as me. Currently I have to write my own definitions, which is a bit silly as this project is written in TypeScript itself.
