### ISSUE TITLE
Upgrade to a newer version trouble for VueJS projects

### ISSUE THREAD

**Issue by StfBauer** [TypeStrong/fork-ts-checker-webpack-plugin#500]
## Current behavior

Back in the past it was running perfectly on a Vue 2.x project but now it doesn't.
```javascript
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
    const forkTsPlugin = new ForkTsCheckerWebpackPlugin({
        vue: true,
        tslint: true,
        formatter: 'codeframe',
        checkSyntacticErrors: false,
        watch: '/src/**/*.vue'
    });
```

## Environment
 - **fork-ts-checker-webpack-plugin**: 5.0.7
 - **typescript**: 3.9
 - **eslint**: N/A
 - **webpack**: 4.35.3
 - **os**: MacOS

Thank you for your help.

**Comment by piotr-oles** [comment]
Hi! Please update your config - with version 5 the config schema has been changed :)

**Comment by StfBauer** [comment]
Thought about that do you have any reference documentation available what has changed? ;)

Thank you.
