### ISSUE TITLE
Files that provide only type dependencies for main entry and unused files are not being checked for TS errors.

### ISSUE THREAD

**Issue by dmitrysteblyuk** [TypeStrong/fork-ts-checker-webpack-plugin#502]
## Current behavior

If you import only a type (or use the imported object for type definition only) from a file it will be skipped during TS check by the plugin. So will be any unused ts files.

## Expected behavior

All files included in `tsconfig.json` are being checked.
This is exactly same behavior `ts-loader` and `tsc` follow.

## Steps to reproduce the issue

I provided simple repro below.
Just run `yarn && yarn build` to observe that no errors are triggered.
Change `transpileOnly` to `false` in `webpack.config.js` or just run `npx tsc` and see that both `ts-loader` and `tsc` do not ignore TS errors.

## Issue reproduction repository

https://github.com/dmitrysteblyuk/fork-ts-checker-bug-repro

## Environment
 - **fork-ts-checker-webpack-plugin**: ^5.1.0 (last known working version - `1.5.0`)
 - **typescript**: 3.9.7
 - **eslint**: -
 - **webpack**: ^4.44.1
 - **os**: Mac OS X 10.15.5

**Comment by piotr-oles** [comment]
Duplicate: #36 . It's an old issue, I hope I will be able to solve it soon.

**Comment by dmitrysteblyuk** [comment]
> It's an old issue, I hope I will be able to solve it soon.

Thanks! that would be really great!

Maybe you should consider changing the title of #36. I saw this issue, but since the bug itself was not actually about _triggering_ the rebuild, I thought it actually could be a different issue, and reported a new one.
