### ISSUE TITLE
Non-incremental build 85% slower with V5 

### ISSUE THREAD

**Issue by belaczek** [TypeStrong/fork-ts-checker-webpack-plugin#506]
## Current behavior
I experience a major increase in production build time after upgrading the library from 4.1.6 to 5.1.0. The project is quite large (~250k LOC) and since our CI doesn't preserve generated cache files between builds, we have omitted incremental build options.

Following is a comparison of configurations and compilation times between 4.1.6 and 5.1.0. 

#### Configuration

```typescript
new ForkTsCheckerWebpackPlugin({
      tsconfig: PROJECT_PATHS.tsConfig,
      async: false,
      useTypescriptIncrementalApi: false,
      measureCompilationTime: true,
    }),
```

`Compilation took: 47112.32 ms.`

#### Configuration

```typescript
 new ForkTsCheckerWebpackPlugin({
      typescript: {
        configFile: PROJECT_PATHS.tsConfig,
        configOverwrite: {
          compilerOptions: {
            sourceMap: false,
            skipLibCheck: true,
            inlineSourceMap: false,
            declarationMap: false,
            noEmit: true,
            incremental: false,
          },
        },
        profile: true,
      },
      async: false,
    }),
```

#### Build profile

```
Parse Configuration:                  0.18 s
Create Watch Compiler Host:           0.00 s
I/O Read:                             1.28 s
Parse:                                3.39 s
ResolveTypeReference:                 0.20 s
ResolveModule:                        9.99 s
Program:                             15.57 s
Bind:                                 2.70 s
Check:                               23.12 s
transformTime:                      274.49 s
Emit:                               276.41 s
Semantic Diagnostics:               301.70 s
Create Watch Program:               321.36 s
Poll And Invoke Created Or Deleted:   0.06 s
Queued Tasks:                         0.00 s
```

From the build profile of V5 it seems like the emitting phase takes a lot of time even though `noEmit` is set to true.
I suspect this might be related to https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/499.

## Expected behavior
There isn't any significant performance decrease with the latest version of the library.

## Steps to reproduce the issue
Run production build using the configuration above.

## Environment
 - **fork-ts-checker-webpack-plugin**: 5.1.0
 - **typescript**: 4.0.2
 - **webpack**: 4.44.1
 - **os**: MacOS + Jenkins CI build running some linux based docker image

**Comment by piotr-oles** [comment]
Sorry for the late response - could you provide a reproduction repository?

**Comment by zlk89** [comment]
Also seeing this issue, it becomes really slow on `after seal` step

**Comment by piotr-oles** [comment]
@belaczek The latest TypeScript Beta version contains a fix that could potentially fix this issue. Could you test it?

**Comment by belaczek** [comment]
Thanks! From brief testing, it looks like the performance really did improve with the latest beta. Especially while having the incremental mode turned on. 👍
