### ISSUE TITLE
Disable Cache?

### ISSUE THREAD

**Issue by breezewish** [TypeStrong/fork-ts-checker-webpack-plugin#508]
## Feature motivation

I have a mono project that contains multiple workspace bundles like library-a, library-b, library-c, app-a, app-b. Each bundle is written in TypeScript and they may depend on each other. For easier understanding, suppose that library-c depends on library-b, and library-b depends on library-a, and app-X depends on all libraries (library-a, library-b and library-c), as below:

```
library-a  <-- library-b <-- library-c <-- appX
            \             \
             \             app-X
              \ 
               app-X
```

I'm using esbuild / babel-loader in development process, so that `.d.ts` is not available. During building process, library-a will build a development js bundle first, which is then used by library-b and app-X. Since the dependency of library-b is changed, it is rebuilt as well, result in a new library-b bundle, which then cause library-c to rebuild, etc. Each library is marked as an external, and they are not bundled together.

To make type checks work, I added `tsconfig` alias, like:

```json
{
  "compilerOptions": {
    "paths": {
      "@foo/library-a": ["packages/library-a/index.ts"],
      "@foo/library-b": ["packages/library-b/index.ts"],
      ...
    }
  }
}
```

However, for the ForkTs plugin, when library-a is changed, type checks in library-b and appX is outdated and becomes incorrect, since for library-b no `.ts` file is changed, only `.js` is changed.

This can be migrated by adding ts file from library-a to the file watch list of library-b. However, it means whenever there is a change in library-a, library-b will be rebuilt twice (1 for unneeded `.ts`, 1 for updated js bundle file). Similarly, each rebuild in library-b will then cause library-c to rebuild twice. Eventually each appX will be rebuilt number of times for each change in library-a.

## Feature description

I would like to disable ForkTs plugin cache, so that even if no source `.ts` file is changed, type checks are performed correctly based on latest disk contents.

**Comment by piotr-oles** [comment]
Hi! Could you provide a reproduction repository that represents the issue that you would like to solve? There is no cache like you described in the plugin itself so it can be some bug or misconfiguration of the TypeScript

**Comment by breezewish** [comment]
Hi, I bypassed this issue by running another TypeScript check process independently. I would re-open this issue if I move back to this plugin and can produce a reproduction. Thanks!
