### ISSUE TITLE
Read config file from a directory

### ISSUE THREAD

**Issue by liaoliaots** [TypeStrong/fork-ts-checker-webpack-plugin#513]
## Feature motivation
For now, this plugin will read config file from root directory automatically, but some people like place config file to some directory, but this plugin wouldn't load config file automatically.

## Feature description
provide a config option to specify the path of config file.

## Feature implementation
just a config option

**Comment by piotr-oles** [comment]
Hi! :) Do you mean cosmiconfig file?

**Comment by liaoliaots** [comment]
That's it.

**Comment by liaoliaots** [comment]
Like 'postcss-loader', it provide 'config' option to specify config-file path.

**Comment by piotr-oles** [comment]
Would you like to implement this? ;)
