### ISSUE TITLE
Type-check on incremental build seems much slower after upgrading to Webpack 5

### ISSUE THREAD

**Issue by akphi** [TypeStrong/fork-ts-checker-webpack-plugin#518]
Before diving in, I want to file this issue so that anyone who just recently upgrades to Webpack 5 can chime in (or let me know if I'm just the outlier here). Really sorry @piotr-oles since I could not give a good repro repo now. Will find some time to work on it. Meanwhile, I will just post the `profiling` result here (the initial is posted as well as a reference point for the incremental build profile)

## Current behavior
After upgrading to Webpack 5, the initial build time does not change, but the incremental build time increases significantly after making a change in watch mode. `profiling` result:

```
# Initial
Parse Configuration:                0.32 s
Create Watch Compiler Host:         0.00 s
I/O Read:                           1.11 s
Parse:                              3.88 s
ResolveTypeReference:               0.26 s
ResolveModule:                      8.87 s
Program:                            15.12 s
Bind:                               2.97 s
Check:                              33.12 s
transformTime:                      4.93 s
Emit:                               5.70 s
Semantic Diagnostics:               39.10 s
Create Watch Program:               57.99 s
Poll And Invoke Created Or Deleted: 0.08 s

# Incremental
Poll And Invoke Created Or Deleted: 1.90 s
I/O Read:                           0.00 s
Parse:                              0.00 s
ResolveTypeReference:               0.00 s
Program:                            0.01 s
Bind:                               0.02 s
Check:                              18.61 s
transformTime:                      2.93 s
Emit:                               3.07 s
Semantic Diagnostics:               21.78 s
Queued Tasks:                       22.14 s
```

## Expected behavior
Like with Webpack 4, I expect the incremental build type-check time to be minimal. Following is the output for `profiling`

```
# Initial
Parse Configuration:                 0.44 s
Create Watch Compiler Host:          0.00 s
I/O Read:                            1.71 s
Parse:                               6.28 s
ResolveTypeReference:                0.36 s
ResolveModule:                      13.55 s
Program:                            23.12 s
Bind:                                4.12 s
Check:                              44.26 s
transformTime:                       5.38 s
Emit:                                6.26 s
Semantic Diagnostics:               50.86 s
Create Watch Program:               79.02 s
Poll And Invoke Created Or Deleted:  0.16 s
Queued Tasks:                        0.00 s

# Incremental
Poll And Invoke Created Or Deleted: 1.41 s
I/O Read:                           0.00 s
Parse:                              0.02 s
ResolveModule:                      0.00 s
ResolveTypeReference:               0.00 s
Program:                            0.03 s
Bind:                               0.01 s
Check:                              1.61 s
transformTime:                      0.01 s
Emit:                               0.02 s
Semantic Diagnostics:               1.71 s
Queued Tasks:                       2.17 s
```

## Issue reproduction repository
Again, really sorry about this one, I have a rather complicated set up behind a corporate wall, so it might take some time for me to give a minimal reproducible repo.

## Environment
 - **fork-ts-checker-webpack-plugin**: 5.2.0
 - **typescript**: 4.0.3
 - **eslint**: 7.11.0
 - **webpack**: 5.1.3
 - **webpack-cli**: 4.0.0
 - **os**: Windows 10

**Comment by piotr-oles** [comment]
Thanks for reporting it! Looking forward to see the reproduction repository :)

**Comment by moltar** [comment]
I noticed that Webpack 5 is just slower in general in other areas, even without this plugin.

**Comment by akphi** [comment]
@piotr-oles So I could not reproduce the issue I. Perhaps I did something dumb, or in the midst of upgrading various packages to work with webpack@5, there's a combination that makes this happen. Either way, I'm closing this issue now. Sorry for all the trouble.

That aside, I notice that if I make a change in, let say, a TSX file the incremental check is around 4 second, versus 10-20 second if I change a file that is imported by many other files. Take this [repo branch](https://github.com/akphi/legend-studio/tree/test-ts-fork-checker) for example. This is my attempt to reproduce the issue.

When you're running the app, if you change this [line](https://github.com/akphi/legend-studio/blob/test-ts-fork-checker/app/components/editor/side-bar/Explorer.tsx#L463) to

```typescript
<div className="panel__header__title__content side-bar__header__title__content">EXPLORER</div>
```

the incremental build is within 5 seconds.

But if I make a change in this [file](https://github.com/akphi/legend-studio/blob/test-ts-fork-checker/app/stores/EditorConfig.ts#L24) and add an export to it

```typescript
export const dummy = 1;
```

the incremental build takes 10-20 seconds.

@piotr-oles is this very much expected, if not, could be due to any bad config that I have?

**Comment by piotr-oles** [comment]
Thanks for sharing your findings. The check time is proportional to the number of files that depend on a changed file. To illustrate why it's the case, let's imagine that you have the following files:
```
// a.ts
export type X = number;
```
```
// b.ts
import { X } from 'a.ts';

export type Y = {
  x: X;
}
```
```
// c.ts
import { Y } from 'b.ts';

const y: Y = { x: 10 };
```
If you change in `a.ts` `type X = string;` it will create a semantic error in `c.ts`. That's why you have to check all files that depend (directly or indirectly) on the changed file :)
