### ISSUE TITLE
Updating from v4 to v5 causes Gulp tasks not terminate.

### ISSUE THREAD

**Issue by gabrycaos** [TypeStrong/fork-ts-checker-webpack-plugin#529]
## Current behavior
I have a project that manage some lyfecicle task with Gulp. After updating this plugin from v4 to v5 when i start a gulp script, the process executes succesfully all gulp tasks but after not terminate.

## Expected behavior
I expect that gulp process terminates after executing all tasks, like the behavior with v4 version

## Environment
 - **fork-ts-checker-webpack-plugin**: [5.2.1]
 - **typescript**: [3.9.5]
 - **webpack**: [4.43.0]
 - **os**: [macOS Catalina and gitlab pipelines]
 - **gulp**: [4.0.2]

**Comment by gabrycaos** [comment]
Same problem with v6

**Comment by piotr-oles** [comment]
Hi! Could you create a reproduction repository?
