### ISSUE TITLE
alias imports of namespaced types are failing when using ts-loader with fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by alfrescian** [TypeStrong/fork-ts-checker-webpack-plugin#53]
I've created a simple example repository to reproduce the issue:
https://github.com/alfrescian/fork-ts-checker-issue

I've an index.ts that does the following alias import of a type defined in a namespace:
`import foo = myNamespace.foo;`
`const myFoo: foo = {foo: 'foo'};`

when using ts-loader with  fork-ts-checker-webpack-plugin then the output is (run `npm run fork` and check dist/index.js):
`var foo = myNamespace.foo;`
`var myFoo = { foo: 'check' };`

JS runtime will complain about myNamespace is undefined.

when using ts-loader without fork-ts-checker-webpack-plugin then the output is (run `npm run no-fork` and check dist/index.no-fork.js): 
`var myFoo = { foo: 'check' };`

we are heavily using namespaces & these kinds of alias imports in our project & that currently blocks us using fork-ts-checker-webpack-plugin.

it does not make any difference if an ambient or non-ambient namespace is used. (see index.ts in my example)

(issue was created in ts-loader repo but I was informed that's most likely an issue in the plugin: https://github.com/TypeStrong/ts-loader/issues/644#issuecomment-331943542)

**Comment by piotr-oles** [comment]
This plugin has no impact on js output - I think it's not possible to be caused by adding it to the webpack. I guess it's because `transpileOnly: true` mode :)
