### ISSUE TITLE
Only log errors for webpack module bundles

### ISSUE THREAD

**Issue by BregtDeLange** [TypeStrong/fork-ts-checker-webpack-plugin#531]
## Current behavior
I need to setup webpack module bundling in an existing .NET MVC project which currently uses old MVC javascript bundling. Both bundling methods still need to exist next to each other. For the new projects inside this solution, I thus use module bundling via WebPack. I reuse the existing tsconfig but overwrite some properties with ts-loader.

I work in Visual Studio 2019

## Expected behavior
I would like to see only compilation errors in TypeScript files that are related to my webpack entry files. Currently I see all errors in the Typescript files of the project, even if they're not part of the dependency tree starting from my entry files.

Because tsconfig uses a lot of "includes" that I cannot change or overwrite, due to folder structure.

## Steps to reproduce the issue
This is my setup for ts-loader
``` 
// Load all TypeScript through the "ts-loader"
            {
                test: /\.ts?$/,
                use: [
                    {
                        loader: "babel-loader",
                        options: {
                            "presets": [
                                [
                                    "@babel/preset-env",
                                    {
                                        "targets": {
                                            "esmodules": true
                                        }
                                    }
                                ]
                            ]
                        }
                    },
                    {
                        loader: "ts-loader",
                        options: {                            
                            transpileOnly: true, // Disable type checker - we will use it in ForkTsCheckerWebpackPlugin,
                            compilerOptions: {
                                "target": "es6", // Modern JavaScript
                                "sourceMap": false, // Webpack creates this
                            }
                        }
                    }
                ]
            }
```

And my setup for the Fork TS
```
new ForkTsCheckerWebpackPlugin({
            typescript: {
                diagnosticOptions: {
                    semantic: true,
                    syntactic: true,
                },
            },
            issue: {
                scope: 'webpack',
            },
        })
```

tsconfig (I didn't touch this to don't break existing projects inside the solution)
```
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "lib": [ "es2015", "es2015.iterable", "dom" ]
  },
  "compileOnSave": true,
  "include": [
    "Scripts/**/*",
    "Modules/**/*",
  ],
  "exclude": [
    "bin/**/*.*",
    "obj/**/*.*",
    "node_modules/**/*.*",
    "wwwroot/**/*.*",   
  ]
}
```

I have one entry file (webpack-entry.ts) inside the "Modules" folder that contains an error, just to test Fork TS. However, I also see errors unrelated to the entry file or it's imports.

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.0.1
 - **typescript**: 4.0.5,
 - **webpack**: 5.4.0
 - **os**: Windows

**Comment by piotr-oles** [comment]
Hi 👋  Thanks for the report! 
We don't have plan to support this. In version 6 `issue.scope` was removed. 
If you want that behaviour, you can overwrite `include` and `exclude` in the plugin options (`typescript.configOverwrite`).
We have to add files outside default webpack's dependency tree to reload compilation on types-only files change.

**Comment by piotr-oles** [comment]
I'm closing this issue for the maintenance reasons - let me know if you still have an issue - I will reopen then
