### ISSUE TITLE
Question: How to follow Webpack 5 upgrade suggestion to close compiler hooks after done using it?

### ISSUE THREAD

**Issue by akphi** [TypeStrong/fork-ts-checker-webpack-plugin#535]
Hi @piotr-oles, according to the guideline in webpack 5 upgrade, we're supposed to close the compiler hooks after using it - https://webpack.js.org/migrate/5/#cleanup-the-build-code

How will this be done with the plugin hooks example in the [doc](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#plugin-hooks)? Right now, I'm putting it right after calling ```ForkTsCheckerWebpackPlugin.getCompilerHooks(compiler)``` but not too sure if it can cause any harm. I'm not even sure either I understand Webpack [technical doc](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#compiler-idle-and-close) on this part

```javascript
const webpack = require('webpack');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const compiler = webpack({
  // ... webpack config
});

// now get the plugin hooks from compiler
const hooks = ForkTsCheckerWebpackPlugin.getCompilerHooks(compiler);

// I'm calling `close` here
compiler.close(() => {  /* stub */ });  

// say we want to show some message when plugin is waiting for issues results
hooks.waiting.tap('yourListenerName', () => {
  console.log('waiting for issues');
});
```

**Comment by akphi** [comment]
I ended up moving the code as a webpack plugin so the compiler is auto-closed as that is what seems to be the behavior defined in webpack doc.

**Comment by piotr-oles** [comment]
Sorry for not responding to your issue - I forgot about it. Could you share more details how did you implemented it or a code snippet so we could add it to the plugin?

**Comment by akphi** [comment]
@piotr-oles no worries at all! I'm just trying to navigate the `webpack@5` changelog myself and I stumbled across the [instruction](https://webpack.js.org/migrate/5/#cleanup-the-build-code):
```
When using const compiler = webpack(...);, make sure to close the compiler after using it: compiler.close(callback);
```

And since the example on this repo's README shows us a similar use case (i.e. having a start script and get webpack compiler there to attach `fork-ts-checker-webpack-plugin` hook), I thought I might need to manually close the compiler as well, but I didn't know how I should do that.

So what I did instead was to use the plugin form, which is to follow this fairly simple [guide](https://webpack.js.org/contribute/writing-a-plugin/) from `webpack`. You can find my example [here](https://github.com/akphi/config-tester/blob/master/packages/dev-utils/ForkTsCheckerWebpackFormatterPlugin.js). Here I create a `stylish` formatter for our plugin like what I mentioned in https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/119 😄

Anyhow, I'm still not entirely sure if this achieves what they mentioned by `closing the compiler` but since this is the way most `webpack` plugins are written, I suppose so.
