### ISSUE TITLE
why not using webpack infer file as plugin input. Now the plugin will check all files

### ISSUE THREAD

**Issue by yuzhidi** [TypeStrong/fork-ts-checker-webpack-plugin#539]
## Feature motivation

Now plugin will check all files.
But by webpack infer file, some file should not be check.
Different webpack config can determind different file to pack.
So not need check all files.

## Feature description

Can we use webpack infer file as plugin input ?

**Comment by piotr-oles** [comment]
It was always the case that the plugin was checking all files. What changed is that webpack recompiles when you change a file that belongs to the TypeScript project (defined in tsconfig.json). It solves an issue with type-only files. Previously, when you have an error in the type-only file, and you fix it, it would not re-check your project.

I'm closing this issue for the maintenance reasons. Feel free to respond if you disagree, we can re-open it :)

**Comment by eagleliang** [comment]
> It was always the case that the plugin was checking all files. What changed is that webpack recompiles when you change a file that belongs to the TypeScript project (defined in tsconfig.json). It solves an issue with type-only files. Previously, when you have an error in the type-only file, and you fix it, it would not re-check your project.
> 
> I'm closing this issue for the maintenance reasons. Feel free to respond if you disagree, we can re-open it :)

TS loader provides such mechanism [https://github.com/TypeStrong/ts-loader#onlycompilebundledfiles](https://github.com/TypeStrong/ts-loader#onlycompilebundledfiles)，hope fork-ts-checker would implement similar feature: only checked the bundled files

**Comment by piotr-oles** [comment]
@eagleliang  Could you create a feature request for tracking it?

**Comment by eagleliang** [comment]
> @eagleliang Could you create a feature request for tracking it?

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/543 Please check it
