### ISSUE TITLE
incompatibility with built-in webpack watch file system

### ISSUE THREAD

**Issue by alexander-akait** [TypeStrong/fork-ts-checker-webpack-plugin#540]
## Current behavior

ForkTsCheckerWebpackPlugin breaks compatibility with other plugins which uses watching API of webpack, for example - copy-webpack-plugin adds directories for watch using `compilation.contextDependencies.add` (https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L189), but plugin overrides wathing `fs` and it doesn't respect directories https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/src/watch/InclusiveNodeWatchFileSystem.ts#L47 (I don't know why it was done), so watching is not working for directories. Also it breaks many other webpack features, for example `require.context` (I can provide more list). My recommendation - avoid overriding built-in `file system`, it is very dangerous.

Original issue: https://github.com/webpack-contrib/copy-webpack-plugin/issues/557

We do some fixes on `copy-webpack-side`, but directory watching is still broken, only file watching is working

## Expected behavior

Should work

## Steps to reproduce the issue

1. https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/files/5545187/forkplugin.zip
2. npm install
3. npm run start:dev
4. put new file in the `languages` directory

## Issue reproduction repository

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/files/5545187/forkplugin.zip

## Environment
 - **fork-ts-checker-webpack-plugin**: "^6.0.2",
 - **typescript**: "^4.0.5",
 - **eslint**: -
 - **webpack**: "^5.6.0"
 - **os**: Ubuntu 20.10

**Comment by piotr-oles** [comment]
Thanks for reporting this, I will take a look this week :)

**Comment by raldone01** [comment]
Seems like this issue also affects the compression-webpack-plugin. (The `compilation.hooks.processAssets` is undefined.)

**Comment by piotr-oles** [comment]
There should be a new patch version in a few minutes - please check if it solves these issues :)
