### ISSUE TITLE
Help improving tsc speed 

### ISSUE THREAD

**Issue by munerf** [TypeStrong/fork-ts-checker-webpack-plugin#545]
## Current behavior
Type checking takes too long, I need help diagnosing the issue.

## Expected behavior
Faster typechecking. the project is big, but i'm trying to undestand if I can improve it.

```
Create Watch Compiler Host:  0.00 s
I/O Read:                    0.44 s
Parse:                       1.81 s
ResolveModule:               4.37 s
ResolveTypeReference:        0.13 s
Program:                     7.00 s
Bind:                        0.93 s
Syntactic Diagnostics:       0.00 s
Global Diagnostics:          0.02 s
Check:                      15.98 s
transformTime:               0.80 s
Emit:                        1.00 s
Semantic Diagnostics:       17.16 s
Declaration Diagnostics:     0.31 s
Create Watch Program:       25.63 s
Queued Tasks:                0.00 s
Hash: 48df546ff827c1f170af
Version: webpack 4.39.1
Time: 34157ms
Built at: 12/02/2020 4:25:31 PM
```

What is the "Create Watch Program" that takes 25s? Do I need it? How can I disable it? 

## Environment
windows 10

```
 "dependencies": {
        "@teamsupercell/typings-for-css-modules-loader": "^2.1.0",
        "cache-loader": "^4.1.0",
        "css-loader": "^3.2.0",
        "dts-generator": "^3.0.0",
        "file-loader": "^4.2.0",
        "fork-ts-checker-webpack-plugin": "^6.0.4",
        "fs-extra": "^8.1.0",
        "glob": "^7.1.4",
        "mini-css-extract-plugin": "^0.8.0",
        "node-sass": "^4.12.0",
        "resolve-url-loader": "^3.1.0",
        "sass-loader": "^7.1.0",
        "thread-loader": "^2.1.3",
        "ts-loader": "^6.0.4",
        "typescript": "^4.1.2",
        "webpack": "^4.39.1",
        "webpack-cli": "^3.3.6",
        "webpack-dev-server": "^3.10.3",
        "webpack-manifest-plugin": "^2.0.4"
    },
```

**Comment by munerf** [comment]
running tsc  I get this result:

```
Files:              770
Lines:           169503
Nodes:           606745
Identifiers:     207674
Symbols:         250416
Types:            89087
Instantiations:  235979
Memory used:    328038K
I/O read:         0.21s
I/O write:        0.77s
Parse time:       3.01s
Bind time:        0.82s
Check time:      14.32s
Emit time:        2.47s
Total time:      20.63s
```

So my main question is, how can I use this plugin to run just the "check" phase!

Thank you!

**Comment by piotr-oles** [comment]
You should compare with `tsc --watch` :) Do you want to have faster single build? (not in watch mode)

**Comment by munerf** [comment]
hi, thanks for the reply,

yes, I just want to have a faster build without watch mode.

tsc --watch --noEmit --diagnostics
```
Files:              770
Lines:           169503
Nodes:           606745
Identifiers:     207674
Symbols:         250417
Types:            89089
Instantiations:  235979
Memory used:    352571K
I/O read:         0.51s
I/O write:        0.00s
Parse time:       4.96s
Bind time:        0.94s
Check time:      15.54s
Emit time:        1.00s
Total time:      22.44s
```

it still seems faster than with the plugin, i'm confused here...

**Comment by piotr-oles** [comment]
Could you use `logger: { infrastructure: 'console' }` option to get total time from the plugin perspective? I think I should improve `profile: true` output. It's misleading because some numbers don't add up. For example `Create Watch Program` is a plugin time metric which includes all other metrics (because creating watch program triggers parse, bind check and emit).

**Comment by munerf** [comment]
Where should I add that? i've added to the typescript object, and to the plugin params but i'm not seeing anything different

**Comment by piotr-oles** [comment]
It should be added to [the plugin options](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#options). It should then report additional timing information :) (total time that plugin spent on type-checking)

**Comment by munerf** [comment]
that's what I tried, I only get an extra line saying:

Calling reporter service for single check.

Settings:
```
typescript: {
                    profile: true
                },
logger: { infrastructure: 'console' }
```

**Comment by piotr-oles** [comment]
You can try the alpha version of the plugin which uses simple CompilerHost instead of WatchCompilerHost for a single compilation. Install using `yarn add --dev fork-ts-checker-webpack-plugin@alpha`

**Comment by munerf** [comment]
thanks!

I did some testing with the alpha version. I've noticed that incremental building stopped working with the alpha version, the `tsconfig.tsbuildinfo` file is not generated anymore. So I would say I got almost the same results but incremental builds lost cache..  

I still don't understand how these numbers add up. I'm using `time` for the total execution time.

Here are the benchmarks:

```
I/O Read: 0.13 s
Parse: 1.76 s
ResolveModule: 2.94 s
ResolveTypeReference: 0.08 s
Program: 5.05 s
Syntactic Diagnostics: 0.00 s
Bind: 0.96 s
Check: 14.74 s
Semantic Diagnostics: 15.74 s
Queued Tasks: 0.00 s
2202 modules

Execution time: 23.537 s
```

latest:

```
Create Watch Compiler Host:  0.00 s
I/O Read:                    0.26 s
Parse:                       1.79 s
ResolveModule:               3.12 s
ResolveTypeReference:        0.07 s
Program:                     5.48 s
Bind:                        1.20 s
Syntactic Diagnostics:       0.00 s
Check:                      15.19 s
transformTime:               0.50 s
Emit:                        1.04 s
Semantic Diagnostics:       16.32 s
I/O Write:                   0.01 s
Create Watch Program:       23.34 s
Queued Tasks:                0.00 s
   2202 modules

Execution time: 26.036 s
```

Next execution without changes uses cache and takes 16s

**Comment by piotr-oles** [comment]
These numbers don't add up - some of them include others. It's not perfect, but it's enough to get some understanding of time distribution. In your case, it takes ~16 s for type-checking but before doing that, TypeScript needs to resolve modules (3.12 s), parse (1.79 s), and build a program (5.48 s). Create Watch Program contains these times. 

I don't think I can help you, because these times are very similar to `tsc`, and we will not get it faster because this plugin runs in parallel with webpack.

**Comment by munerf** [comment]
Thank you!
