### ISSUE TITLE
cannot find module css for generate dynamic css.d.ts 

### ISSUE THREAD

**Issue by monic-shixi** [TypeStrong/fork-ts-checker-webpack-plugin#553]
## Current behavior

I had use a package to typing module for css module, it's generate `d.ts` file by dynamic. `fork-ts-checker-webpack-plugin` will throw  error for css import.(Cannot find module  './index.css').

## Expected behavior

Ts check after generate d.ts finished.

## other
I had notice https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/40 , released https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/44 as 0.2.8. And in 4.1.6 version, i used [serviceBeforeStart hooks](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/v4.1.6#plugin-hooks) to delay, but not work.

```js
//DelayForChecker.js
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')
const pluginName = 'DelayForChecker'

class DelayForChecker {
  // eslint-disable-next-line class-methods-use-this
  apply(compiler) {
    compiler.hooks.run.tap(pluginName, () => {
      new ForkTsCheckerWebpackPlugin({
        async: false
      }).apply(compiler)
      console.log('The webpack build process is starting!!!')
      const tsCheckerHooks = ForkTsCheckerWebpackPlugin.getCompilerHooks(compiler)
      tsCheckerHooks.serviceBeforeStart.tap(pluginName, () => {
        console.log('this to delay!!')
      })
    })
  }
}

module.exports = DelayForChecker
```

```js
// webpack config js
{
  plugins: [
     //...
     new DelayForChecker()
  ]
}
```

In https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/v4.1.6/src/index.ts#L277, if `new ForkTsCheckerWebpackPlugin({
        async: false
      }).apply(compiler)` apply(compiler) will run, so serviceBeforeStart not work?

## Environment
 - **fork-ts-checker-webpack-plugin**: 4.1.6
 - **typescript**: 3.8.3
 - **eslint**: 7.14
 - **webpack**: 4.43.0
 - **os**: max

**Comment by piotr-oles** [comment]
Sorry for the late reply. Did you try with a newer version of the plugin?

**Comment by monic-shixi** [comment]
> Sorry for the late reply. Did you try with a newer version of the plugin?

Thanks for your response. I had give up use the  typing module plugin . Because ts runtime will check the all file within src.But my project with multiple entry, So i think it's can't work.

if only single entry, i think it will be work:

```js
compiler.hooks.afterPlugins.tap(pluginName, () => {
	tsCheckerHooks.serviceBeforeStart.tapPromise(pluginName, () => {
    // ...
  })
})
```
