### ISSUE TITLE
eslint check files that not included to build

### ISSUE THREAD

**Issue by khasanovbi** [TypeStrong/fork-ts-checker-webpack-plugin#554]
## Current behavior
eslint check files that not included to build. I have obsolete js files in folder but eslint checks them.
My config of plugin:
```js
    new ForkTsCheckerWebpackPlugin({
        typescript: {
            configFile: '../tsconfig.json',
            context: __dirname,
            diagnosticOptions: {
                semantic: true,
                syntactic: true,
            },
            mode: 'write-references',
        },
        eslint: {
            enabled: true,
            files: './**/*.{js,ts,tsx}', // required - same as command `eslint ./src/**/*.{ts,tsx,js,jsx} --ext .ts,.tsx,.js,.jsx`
            options: {
                fix: true,
            },
        },
    }),
```

## Expected behavior
At version of **fork-ts-checker-webpack-plugin**: 5.2.1 eslint doesn't check them. I'm expect same behavior at new versions.

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.0.8
 - **typescript**: 4.1.3
 - **eslint**: 7.17.0
 - **webpack**: 4.44.2
 - **os**: 20.04.1 LTS

**Comment by piotr-oles** [comment]
Sorry for the late reply. Could you provide a reproduction repository?

**Comment by piotr-oles** [comment]
Closing as there is no reproduction repository :)
