### ISSUE TITLE
eslint works well when start project but don't work when recompile for some files

### ISSUE THREAD

**Issue by debbydeng** [TypeStrong/fork-ts-checker-webpack-plugin#555]
### Current behavior
when start project, eslint works well, when i change some .vue file, some files are not be eslint, and no report errors.

**run start**
![image](https://user-images.githubusercontent.com/18655620/103529459-b0b0db80-4ec0-11eb-990a-01f81575abb0.png)

**recompile**
ignore the file in red box
![image](https://user-images.githubusercontent.com/18655620/103529626-f40b4a00-4ec0-11eb-8830-e811e5cf9528.png)

### webpack config
![image](https://user-images.githubusercontent.com/18655620/103529889-6e3bce80-4ec1-11eb-9d42-9f1dfb18893d.png)

### Expected behavior
all files should be eslint when recompile

Steps to reproduce the issue
when change a file to recompile

### Environment
fork-ts-checker-webpack-plugin: 6.0.8
typescript: 4.0.5
webpack: 4.44.2
os: macOS

Further
it seems when recompile, eslint only work with `./src/xx/*.{ts,tsx,js,jsx,vue}` not `./src/xx/xx/*.{ts,tsx,js,jsx,vue}`, and readme 
`eslint ./src/**/*.{ts,tsx,js,jsx} --ext .ts,.tsx,.js,.jsx`
seems wrong, it should be `eslint "./src/**/*.{ts,tsx,js,jsx}"`

**Comment by piotr-oles** [comment]
Sorry for the late reply - could you provide a reproduction repository?

**Comment by piotr-oles** [comment]
I released a fix regarding the ESLint watch - could you check if the latest version fixes your issue?
