### ISSUE TITLE
Syntactic errors are not ignored in node_modules

### ISSUE THREAD

**Issue by marinovich** [TypeStrong/fork-ts-checker-webpack-plugin#563]
## Current behavior
I've faced the issue of using syntactic diagnostic options

![image](https://user-images.githubusercontent.com/24976771/105707831-9351b900-5f24-11eb-8895-1a1d048610e6.png)

Although in tsconfig.json 

```json
{
  "compilerOptions": {
    ...
    "skipLibCheck": true,
    ...
  },
  "include": [
    "src"
  ],
  "exclude": ["node_modules/**/*.*"]
 }
```
in webpack.config.js

```js
new ForkTsCheckerWebpackPlugin({
  typescript: {
    diagnosticOptions: {
      semantic: true,
      syntactic: true,
    },
  },
}),
```

Without the option `syntactic` everything is OK

Should this check be ignored for `node_modules`?

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.0.7
 - **typescript**: 3.3.4000
 - **webpack**: 4.44.2
 - **os**: MacOS 10.14.6

**Comment by piotr-oles** [comment]
Could you try 
```json
{
  "compilerOptions": {
    ...
    "skipLibCheck": true,
    ...
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
 }
 ```
 ? Also, please try `tsc --watch --noEmit` - is it reporting some errors?

**Comment by marinovich** [comment]
Thank you for your response!
Unfortunately, changes to `tsconfig.json` did not help.

The result of `tsc --watch --noEmit` is the same errors:
```properties
[09:29:31] Starting compilation in watch mode...

node_modules/@draft-js-plugins/editor/lib/index.d.ts:8:1 - error TS1128: Declaration or statement expected.

8 export type { PluginEditorProps } from './Editor';
  ~~~~~~
node_modules/@draft-js-plugins/editor/lib/index.d.ts:8:13 - error TS1005: ';' expected.

8 export type { PluginEditorProps } from './Editor';
              ~
node_modules/@draft-js-plugins/editor/lib/index.d.ts:8:40 - error TS1005: ';' expected.

8 export type { PluginEditorProps } from './Editor';
                                         ~~~~~~~~~~
[09:30:00] Found 3 errors. Watching for file changes.
```

**Comment by piotr-oles** [comment]
I don't think I can help if TypeScript returns same errors. I think you should ask for help TypeScript team :)

**Comment by marinovich** [comment]
OK, got it. Thanks!

**Comment by RichieChoo** [comment]
keep `syntactic` be flase in ForkTsCheckerWebpackPlugin opts
