### ISSUE TITLE
Custom formatter

### ISSUE THREAD

**Issue by mpm-os** [TypeStrong/fork-ts-checker-webpack-plugin#564]
Is there a way to implement a custom formatter?

thanks!

**Comment by piotr-oles** [comment]
No :) Feel free to open PR to implement that

**Comment by ktalebian** [comment]
@piotr-oles v4 had customer formatter https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/v4.1.6 - how come this was removed in v6?

**Comment by piotr-oles** [comment]
I did a rewrite of the plugin and didn't re-implement this feature :)

**Comment by mpm-os** [comment]
I ended up extending the plugin class and adding tapping a hook to print the message I wanted. I don't mind trying a PR if you point me in the right direction (where to change, etc).

**Comment by piotr-oles** [comment]
Most of the code responsible for formatting is in the `src/formatter` directory. 
You would have to extend formatter options to accept custom function:
```diff
// FormatterFactory.ts
type NotConfigurableFormatterType = undefined | 'basic';
type ConfigurableFormatterType = 'codeframe';
+ type CustomFormatterType = Formatter;
- type FormatterType = NotConfigurableFormatterType | ConfigurableFormatterType;
+ type FormatterType = NotConfigurableFormatterType | ConfigurableFormatterType | CustomFormatterType;
// ....
function createFormatter(type?: FormatterType, options?: object): Formatter {
+  // custom formatter type
+  if (typeof type === 'function') {
+    return type;
+  }
  
  switch (type) {
    case 'basic':
    case undefined:
      return createBasicFormatter();

    case 'codeframe':
      return createCodeFrameFormatter(options);

    default:
      throw new Error(`Unknown "${type}" formatter. Available types are: basic, codeframe.`);
  }
}
```
There are also other places to update (like `options.json`, `FormatterConfiguration.ts`, `FormatterOptions.ts`).
Then I would like to ask you to write also E2E test. You can modify an existing one or add a new one. Let me know if you need more guidance. :)

**Comment by vanpipy** [comment]
Im looking forward to this feature :D. I will give you a hand if needed.

It looks to create a new type called `custom` and extend the scope of the `options` will be better.
