### ISSUE TITLE
Extra long "Issues checking in progress..." whitch finish with "memory leak" exception

### ISSUE THREAD

**Issue by mixalbl4-127** [TypeStrong/fork-ts-checker-webpack-plugin#569]
## Current behavior
It looks like this, but it was fixed: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/426

Make file: `Api.ts`

```typescript
/* eslint-disable */
/* tslint:disable */
import { HttpClient } from "./http-client";

export class Api<SecurityDataType = unknown> {
  constructor(private http: HttpClient<SecurityDataType>) {}

    abc1 = () => this.http.request();
    abc2 = () => this.http.request();
    abc3 = () => this.http.request();
}
```

and `http-client.ts`

```typescript
/* eslint-disable */
/* tslint:disable */

/** Overrided Promise type. Needs for additional typings of `.catch` callback */
type TPromise<ResolveType, RejectType = any> = Omit<Promise<ResolveType>, "then" | "catch"> & {
  then<TResult1 = ResolveType, TResult2 = never>(
    onfulfilled?: ((value: ResolveType) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: RejectType) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): TPromise<TResult1 | TResult2, RejectType>;
  catch<TResult = never>(
    onrejected?: ((reason: RejectType) => TResult | PromiseLike<TResult>) | undefined | null,
  ): TPromise<ResolveType | TResult, RejectType>;
};

export interface HttpResponse<D extends unknown, E extends unknown = unknown> extends Response {
  data: D;
  error: E;
}

export class HttpClient<SecurityDataType = unknown> {
  public request = <T = any, E = any>(): TPromise<HttpResponse<T, E>> => {
    return '' as any;
  };
}
```

try to compile, you will see that "Issues checking in progress..." process take extra long time ~15 sec.
I dont know why, but if you Copy-Paste `http-client.ts` to `Api.ts` directly this check take <1 sec.

This files make this lib https://github.com/acacode/swagger-typescript-api with ~1000 `this.http.request`, and each `this.http.request()` took ~7 sec of checking. When I do this in `intel i7` CPU, after ~30 min of compiling I got error about `memory leak`.

**Video:** https://user-images.githubusercontent.com/3511307/108701953-4a842480-7511-11eb-9924-7f3c0c60acd0.mp4

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.1.0
 - **typescript**: 3.9.9
 - **eslint**: 6.8.0
 - **webpack**: 4.46.0
 - **os**: Linux mint 18.3 KDE

**Comment by piotr-oles** [comment]
Could you check If `tsc --watch --noEmit` is working correctly?

**Comment by mixalbl4-127** [comment]
Ssory for delay. Same with `tsc --watch --noEmit`.

**Video**: https://user-images.githubusercontent.com/3511307/108986783-2eac8a00-769b-11eb-9f9e-27f914830c8d.mp4

@piotr-oles

**Comment by piotr-oles** [comment]
Then it's a TypeScript's issue - please report it on the TypeScript repo :)

**Comment by mylastore** [comment]
For a large project, it takes about 15 minutes for `Issues checking in progress...` to complete
Ubuntu 20
```
   "typescript": "4.2.4",
   "fork-ts-checker-webpack-plugin": "^6.2.1",
   "webpack": "5.33.2",
   "eslint": "7.24.0",
```

**Comment by piotr-oles** [comment]
Is it working faster with `tsc --watch --noEmit`? Have you tried disabling `eslint`?

**Comment by mylastore** [comment]
I disable eslint and is the save exactly about 15 minutes for `Issues checking in progress..` to complete. I try almost everything. Where do I add this flags `--watch --noEmit ` on webpack.config?

**Comment by piotr-oles** [comment]
You shouldn't run webpack, but `tsc` directly to see if there is an issue in the TypeScript itself :) So the command is as I said: `tsc --watch --noEmit`, or more exactly `./node_modules/.bin/tsc --watch --noEmit`

**Comment by mylastore** [comment]
@piotr-oles I run `tsc --watch --noEmit` and it does take about the same time about 15 minutes or so `Starting compilation in watch mode...`

**Comment by piotr-oles** [comment]
So it's an issue with TypeScript. You can try profile types resolution: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#profiling-types-resolution. You can also create a ticket in TypeScript, but I would suggest profiling first - maybe there is a one particular type that is causing the slowdown

**Comment by mylastore** [comment]
@piotr-oles I really appreciate you taking the time, so thanks. 

We found the solution to our issue and will post a link here for anyone that runs into this. [LINK](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-base-types-over-unions)
