### ISSUE TITLE
Where has resolveModuleNameModule and resolveTypeReferenceDirectiveModule moved to?

### ISSUE THREAD

**Issue by ktalebian** [TypeStrong/fork-ts-checker-webpack-plugin#571]
I'm using the v6 of this webpack plugin but I cannot figure out where to place `resolveModuleNameModule` and `resolveTypeReferenceDirectiveModule`. Where do these two parameters go now?

**Comment by piotr-oles** [comment]
I removed these options to simplify the codebase and configuration. If you use Yarn PnP, you don't have to configure this anymore because yarn patches typescript out of the box :)
