### ISSUE TITLE
Provide an option to invoke TypeScript in non-watch mode even when webpack is in watch mode

### ISSUE THREAD

**Issue by cnshenj** [TypeStrong/fork-ts-checker-webpack-plugin#572]
## Feature motivation

TypeScript has some strange behavior that regular build is much faster a watch-mode build (sometimes the watch-mode build is 30x slower). This slows down forked type checking significantly.

## Feature description

Provide an option to always invoke TypeScript in non-watch mode. This will make type checking time much more consistent and often shorter.
For example, with my project, `tsc` (complete build) is consistently completed within 60 seconds. `tsc -w` initial compilation takes about 9 minutes. Subsequent recompilation in watch mode time ranges from 1 second to several minutes. Even worse, if I change another file while type checking is still running, the webpack bundling process will be slowed down too.

## Feature implementation

`watch`: `"auto"` (follows webpack) or `"off"`

**Comment by piotr-oles** [comment]
I will release an alpha version with this implemented - I would like to ask you to test if this solves your issue :)

**Comment by cnshenj** [comment]
Sure, I'll be glad to try that out. Note: it is watch or incremental that causes this issue, so be sure to turn off both. In case you are interested, here is the TypeScript bug: [https://github.com/microsoft/TypeScript/issues/35729](https://github.com/microsoft/TypeScript/issues/35729).

I just found out with TS 3.9.7 our project can be built in 20 seconds (regular build, no watch, no incremental)! This means even if we use `fork-ts-checker-webpack-plugin` to start a full type checking pass, it is very acceptable, compared to the uncertainty in watch/incremental mode. 

Also, my initial proposal of the option may not be good. I bet you can come up with something better.

**Comment by piotr-oles** [comment]
The solution that I implemented works that way:
 - if you use `build: true` mode, then use `SolutionBuilder` API, regardless of webpack
 - if you run webpack in watch mode, then use `WatchProgram` API
 - otherwise, use `Program` API
 
For now, there is no configuration for that. If you would like to use `Program` API  also for watch mode in webpack, I can try to implement that with configuration options (that was the first implementation of the plugin, before `WatchProgram` API was available)

**Comment by cnshenj** [comment]
I think the Program API is what I need, and the whole purpose of the feature request is to enforce it, even when webpack is in watch mode.

The reason:
- `--build` implicitly enables incremental build, which is slow due to TS bug 35729.
- `WatchProgram` API is equivalent to TS watch mode, which is slow due to same TS bug 35729.

My current workaround is removing `fork-ts-checker-webpack-plugin`, running `tsc` in a separate task using `nodemon` to monitor file changes. It's not as convenient as `fork-ts-checker-webpack-plugin` because the bundling output and type checking output are in two different window, but at least both are fast.

**Comment by piotr-oles** [comment]
I found very interesting PR: https://github.com/microsoft/TypeScript/pull/42960. I will publish alpha version anyway, but I will wait for this PR before releasing this on the `latest` channel. Maybe it will solve the `WatchProgram` issue :)

**Comment by sokra** [comment]
> Maybe it will solve the `WatchProgram` issue :)

Yes that was the intent of this PR.

I figured that even this that improvement fork-ts-checker-webpack-plugin is a little bit slower compared to `tsc --watch` directly. Maybe that's because of the different Filesystem...

**Comment by piotr-oles** [comment]
I will profile the plugin again after releasing your PR :)

**Comment by cnshenj** [comment]
> > Maybe it will solve the `WatchProgram` issue :)
> 
> Yes that was the intent of this PR.
> 
> I figured that even this that improvement fork-ts-checker-webpack-plugin is a little bit slower compared to `tsc --watch` directly. Maybe that's because of the different Filesystem...

Do you have any idea how "slower" it would be. Currently, with my project, a non-watch build takes 20 seconds. `tsc --watch` takes 9 minutes! I didn't measure `fork-ts-checker-webpack-plugin`, but it is not only slow, it will also block webpack bundling if I make another file change while previous type checking is still in progress.

I'm hoping with a proper fix, `tsc --watch` will take just a little longer than non-watch build, while `fork-ts-checker-webpack-plugin` may add a little more. But those should be just the first pass, file changes should trigger a watch build pass that is much faster.

**Comment by sokra** [comment]
> > > Maybe it will solve the `WatchProgram` issue :)
> > 
> > Yes that was the intent of this PR.
> > 
> > I figured that even this that improvement fork-ts-checker-webpack-plugin is a little bit slower compared to `tsc --watch` directly. Maybe that's because of the different Filesystem...
> 
> Do you have any idea how "slower" it would be. Currently, with my project, a non-watch build takes 20 seconds. `tsc --watch` takes 9 minutes! I didn't measure `fork-ts-checker-webpack-plugin`, but it is not only slow, it will also block webpack bundling if I make another file change while previous type checking is still in progress.
> 
> I'm hoping with a proper fix, `tsc --watch` will take just a little longer than non-watch build, while `fork-ts-checker-webpack-plugin` may add a little more. But those should be just the first pass, file changes should trigger a watch build pass that is much faster.

I was talking about 10-20%, so it may take 25-30s. But it could also benefit from incremental mode so you only have to pay that on the first compile.

It may be worth trying out my typescript PR and check if that fixes your 9min issue. Clone it, `npm i`, `yarn gulp local`, and run `node .../typescript/built/local/tsc.js --watch` in your project folder. Leave a comment on the PR. Maybe add `"diagnostics": true` to your tsconfig to get timing info.

**Comment by piotr-oles** [comment]
@cnshenj did you tried @sokra's PR or the alpha version of the plugin?

**Comment by cnshenj** [comment]
@piotr-oles I haven't. As we discussed before, the fix I need is to make TypeScript run in *non*-watch mode, even when webpack is in watch mode. But according to what you described, the alpha version will make TypeScript run in watch mode when webpack is in watch mode.

Currently I use `nodemon` to monitor project changes and start a *full* TypeScript compilation when a change is detected. A full compilation pass only needs 20 seconds, compared to several minutes by incremental compilation in watch mode.

I also had some discussion with @sokra in the PR. I believe he made changes to address the specific scenario I described (modify several files and save at the same time). Now we are just waiting for the TypeScript team to incorporate the fix and release TypeScript 4.3.

**Comment by piotr-oles** [comment]
That makes sense, let's wait :)

**Comment by piotr-oles** [comment]
@cnshenj Could you try the latest TypeScript beta version? It contains @sokra's fix :)

**Comment by piotr-oles** [comment]
I will assume it fixed the problem. If not, I will re-open the issue :)
