### ISSUE TITLE
Run this plugin after webpack build

### ISSUE THREAD

**Issue by aspirisen** [TypeStrong/fork-ts-checker-webpack-plugin#577]
## Feature motivation

Decrease memory usage.

## Feature description

It looks like this plugin runs along with webpack build. That cause high memory usage at one time. It would be good if we could pass an argument to run checker after webpack frees its memory. 

Currently on CI I have 4gm memory limit, webpack during build takes 2.5+ gb memory and `fork-ts-checker-webpack-plugin` takes 1+ gb memory, and as they are run together they rich memory limit from time to time.

## Feature implementation

Add argument to run this plugin after webpack frees its memory, so on CI we could set it to true

**Comment by piotr-oles** [comment]
I understand your issue, but I don't want to extend the plugin unless there is a demand for it :) The idea of this plugin is to run in parallel with webpack so adding this feature seems to contradict it. I would suggest running `tsc --noEmit` after webpack build instead :)
