### ISSUE TITLE
ERROR：fork-ts-checker-webpack-plugin hooks are already in use

### ISSUE THREAD

**Issue by H-zf** [TypeStrong/fork-ts-checker-webpack-plugin#579]
vue
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')
plugins: [
            new webpack.DefinePlugin(
                {
                    'envStr': JSON.stringify(envStr)
                }
            ),
            new HardSourceWebpackPlugin(), // 缓存，每当程序包依赖性发生变化时，请记住清除缓存
            new OptimizeCSSAssetsPlugin(),
            new ProgressBarPlugin(),
            new ForkTsCheckerWebpackPlugin({
                memoryLimit: 4096
            })
        ],
Error: fork-ts-checker-webpack-plugin hooks are already in use

**Comment by piotr-oles** [comment]
Please use bug report template :)
And I will need reproduction repository to help you.
