### ISSUE TITLE
Doesn't work with extended tsconfig file.

### ISSUE THREAD

**Issue by markmcdermid** [TypeStrong/fork-ts-checker-webpack-plugin#58]
Hey, when I use "extends" in tsconfig, this plugin doesn't seem to pick it up and just gives `No type errors found`, however the extended tsconfig is definitely picked up in the ts-loader config. 

Do you know why this might be?

tsconfig.json
```
{
  "extends": "../../../tsconfig.json",
  "exclude": [
    "node_modules",
    "packages/frontend"
  ]
}

```

webpack.config.js
```
HappyPack({
      id: 'ts',
      threads: 2,
      loaders: [
        {
          path: 'babel-loader'
        },
        {
          path: 'ts-loader',
          query: {
            happyPackMode: true,
            configFile: path.resolve(__dirname, 'tsconfig.json')
          }
        }
      ]
    }),
    new ForkTsCheckerWebpackPlugin(
      {
        tslint: true,
        tsconfig: path.resolve(__dirname, 'tsconfig.json')
      }
    ),
```

**Comment by markmcdermid** [comment]
Oddly, it also doesn't lint anything when I refer to the extended tsconfig but does when I use the base one.

**Comment by ddrozdov** [comment]
Are there any plans to fix this or is there any workaround?

**Comment by ddrozdov** [comment]
Just checked the latest version 0.5.2 and it seems to be fixed now!
