### ISSUE TITLE
Display Typescript compilation errors in browser

### ISSUE THREAD

**Issue by EBruchet** [TypeStrong/fork-ts-checker-webpack-plugin#581]
## Feature motivation
Make it clearer to the user when there's been a TS compilation error instead of having to scan their terminal. This could possibly only be displayed if `async: false` has been specified?

## Feature description
I recognise this has been mentioned previously https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/530#issue-738881070, but it's not entirely clear why this shouldn't be a part of the plugin? The plugin can be used with `webpack-dev-middleware` instead of `webpack-dev-server` so in the case of the former no error messages are surfaced to the user in the browser which is very frustrating.

If there's an approach to using this plugin with `ts-loader` and `webpack-dev-middleware` that displays the TS compilation errors in the browser window without changing this plugin, any tips on how to get there would be appreciated.

**Comment by piotr-oles** [comment]
I think it should be possible to integrate with webpack-dev-middleware. There is a hook file that integrates with webpack-dev-server: src/hooks/interceptDoneToGetWebpackDevServerTap.ts - you could try edit the condition to handle case when tap.name === 'webpack-dev-middleware'. I checked source code of webpack-dev-middleware and they use this name to hook. Not sure if this will work OOTB but I think it's worth trying

**Comment by piotr-oles** [comment]
I checked it and `webpack-dev-middleware` doesn't provide any infrastructure to push errors to the browser. It's out of the scope of `webpack-dev-middleware`, therefore it will not implement it in this plugin :)
