### ISSUE TITLE
Shall we rename the master branch to main?

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/fork-ts-checker-webpack-plugin#582]
Hey @piotr-oles!

How would you feed about us renaming the `master` branch to `main`?

## Feature motivation

Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. GitHub is gradually renaming the default branch of their own repositories from `master` to `main`.

## Feature description

Renaming the branch.

## Feature implementation

Following the instructions here is super simple: https://github.com/github/renaming

I did this on [`ts-loader`](https://github.com/TypeStrong/ts-loader) today and it was super straightforward.  Renaming the branch and then copy-pasting the command to change my local branch and I was done.  Would recommend!

**Comment by piotr-oles** [comment]
Hi! We can do this, no problem :)
The only thing to keep in mind is that our semantic-release configuration points to the master branch (release.config.js), so we have to update it as well.

**Comment by johnnyreilly** [comment]
I'm happy to do this - I'll make sure I tackle `release.config.js` as well

**Comment by johnnyreilly** [comment]
okay let's tackle this!
