### ISSUE TITLE
Add TS check in Vue template

### ISSUE THREAD

**Issue by Edge00** [TypeStrong/fork-ts-checker-webpack-plugin#587]
## Feature motivation
fork-ts-checker-webpack-plugin can't find that property 'msg' does not exist on type '{ name: number; }'
![image](https://user-images.githubusercontent.com/23715779/114519742-481d8b80-9c73-11eb-8dc3-e1eaae9254fe.png)

```vue
<template>
  {{data.msg}}
</template>
<script lang="ts">
  import { defineComponent } from 'vue'
  export default defineComponent({
    setup() {
      return {
        data: { name: 100 }
      }
    }
  })
</script>
```
Which vetur can
![image](https://user-images.githubusercontent.com/23715779/114519615-29b79000-9c73-11eb-97c7-47169f178515.png)

I am not sure this is a bug or not implemented

**Comment by piotr-oles** [comment]
It's not implemented :) I'm open for contributions, I don't think I will have time to implement this in near future

**Comment by Edge00** [comment]
OK. Thanks for confirm!
