### ISSUE TITLE
Support auto fix for eslint on v3.1.1

### ISSUE THREAD

**Issue by DanielDantas** [TypeStrong/fork-ts-checker-webpack-plugin#588]
## Current behavior
On v3.1.1 createEslinter.getLintsForFile only returns the lint report object but it does not apply the auto fix to the files.
This happens because the plugin is not calling CLIEngine.outputFixes

Check this link for reference:
https://eslint.org/docs/developer-guide/nodejs-api
"Once you get a report object, it's up to you to determine how to output the results. Fixes will not be automatically applied to the files, even if you set fix: true when constructing the CLIEngine instance. To apply fixes to the files, call outputFixes."

## Expected behavior
support auto fix for eslint

## Steps to reproduce the issue

create a new plugin with providing eslint = true and eslintOptions with fix = true

Ex:
new ForkTsCheckerWebpackPlugin({
        .
        .
        .
        eslint: true,
        eslintOptions: { fix: true }
    })

## Issue reproduction repository
After this line:
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/04581f4a8cc999563e9ba1c63bfee7efb97e380f/src/createEslinter.ts#L27

we need: "eslint.CLIEngine.outputFixes(lints);"

## Environment
 - **fork-ts-checker-webpack-plugin**: 3.1.1
 - **typescript**: N/A
 - **eslint**: N/A
 - **webpack**: N/A
 - **os**: N/A

**Comment by piotr-oles** [comment]
Version 3 is no longer supported - in order to get eslint fix working, please update the plugin :)
