### ISSUE TITLE
Enable typescript's traceResolution option

### ISSUE THREAD

**Issue by hodavidhara** [TypeStrong/fork-ts-checker-webpack-plugin#59]
Is there a way to see the module resolution trace logs like when you run `tsc --traceResolution` but through this plugin? I'm running into a strange issue where my dev and prod builds compile fine, but my test build (using karma and karma-webpack) fails to compile with`TS2307: Cannot find module 'moment'.` All builds are using the same tsconfig file, and when I run `tsc --traceResolution` I can see typescript properly resolve the moment module, so I'm having a difficult time debugging why it is failing to compile only when being run through karma and karma-webpack.

If I could turn on the traceResolution flag and get those logs while running that build, I might get a little better insight.

**Comment by piotr-oles** [comment]
Hi @hodavidhara ,
Please try [fork-ts-checker-webpack-plugin@alpha](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/alpha) - I've published a new version that should resolve this issue 🚀You can set `"traceResolution": true` in your compilerOptions to see it in the console.
I know it was 3 years ago and you probably solved that issue, but I left this comment for the reference for others :)
