### ISSUE TITLE
Have console output to a file (not in the main terminal)

### ISSUE THREAD

**Issue by terpimost** [TypeStrong/fork-ts-checker-webpack-plugin#590]
## Feature motivation
Right now plugin outputs errors in the same console where the webpack build was imitated. But what if you don't want that?
In our team we record all webpack output in a file and leave the main console clean.

## Feature description
It would be nice to be able to specify a file to output or somebody could teach us how to do it?

## Feature implementation
I can't suggest anything here. But when I run parallel-webpack output of multiple processes goes into a single file (we direct it to do this way instead of console output), but TsChecker for some reason doesn't respect that and keeps writing to the main console.

**Comment by piotr-oles** [comment]
Are you redirecting the output using JavaScript code or are you using bash stream operator (like `webpack > output.txt`)?

**Comment by terpimost** [comment]
I'm using bash stream operator

**Comment by piotr-oles** [comment]
Then it's weird that it doesn't work - the plugin calls `console.log` which should write to the stdout 🤔

**Comment by terpimost** [comment]
I guess since I'm using parallel-webpack and a process is separate `console.log` is using the initial console where I started number of apps to run... For some reason parallel-webpack targets both write in the same file, while plugin doesn't.

**Comment by piotr-oles** [comment]
I will need a reproduction repository to help you with that :)
