### ISSUE TITLE
compile time lasts up to 5 min

### ISSUE THREAD

**Issue by mykolarositskyi** [TypeStrong/fork-ts-checker-webpack-plugin#610]
## Current behavior

This is a very little project with just some configuration, and I am experiencing compilation time around 2-5 min with a high CPU each time I run the build. Webpack builds projects for few seconds, but type checking is too long.
Here is some info from profile:

![image](https://user-images.githubusercontent.com/55023068/117565470-27055a80-b0ba-11eb-9246-de5ecf863b82.png)

## Expected behavior

Not so long compilation time.

## Steps to reproduce the issue

npm run start:local

## Issue reproduction repository

https://github.com/rositskyy/fts-reproduction-repo

The more files there, the longest compile lasts

## Environment
 - **fork-ts-checker-webpack-plugin**: ^6.2.6
 - **typescript**: ^4.2.4
 - **eslint**: 7.26.0
 - **webpack**: 5.36.2
 - **os**: macOS Catalina v10.15.7

**Comment by piotr-oles** [comment]
Hi! Could you test with the latest TypeScript beta version?

**Comment by mykolarositskyi** [comment]
@piotr-oles , Hi! Yes, it's fixed the problem! Thanks a lot for help!
