### ISSUE TITLE
Warnings treated as errors?

### ISSUE THREAD

**Issue by silkfire** [TypeStrong/fork-ts-checker-webpack-plugin#618]
## Current behavior
It seems like all warnings are treated as errors and printed out as such when building my project.

![image](https://user-images.githubusercontent.com/1554615/118893201-5316ac00-b902-11eb-98cb-239c169be810.png)

## Expected behavior
Only errors should be emitted or there should be an explicit setting to treat warnings as errors.

## Steps to reproduce the issue
Write a method without documenting its parameters' types:

![image](https://user-images.githubusercontent.com/1554615/118893112-367a7400-b902-11eb-98ae-8769faff9e33.png)

VSCode shows this only as a warning, and that's why I also expect `fork-ts-checker` not to pick it up by default.

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.2.10
 - **typescript**: 4.2.4
 - **eslint**: 7.26.0
 - **webpack**: 5.37.0
 - **os**: Windows 10

**Comment by piotr-oles** [comment]
Could you create a reproduction repository, please? :)

**Comment by silkfire** [comment]
I think it has to do with that VSCode displays TypeScript rules (e.g. `noUnusedParameters`, `noUnusedLocals`) configured in `tsconfig.json` as warnings when they're actually errors. Definitely confusing but I think I can live with that. Closing the issue.
