### ISSUE TITLE
No error detail overlay display in webpack v5

### ISSUE THREAD

**Issue by ananiy** [TypeStrong/fork-ts-checker-webpack-plugin#622]
## Current behavior
when using webpack v4:
![image](https://user-images.githubusercontent.com/33290601/121305063-b4dd9b00-c92f-11eb-8b5c-d8c8fffa16d8.png)

when using webpack v5:
![image](https://user-images.githubusercontent.com/33290601/121305136-d0e13c80-c92f-11eb-9e46-58211afdd7a7.png)

## Expected behavior
show normally

## Steps to reproduce the issue
here is the demo:
[demo.zip](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/files/6621559/demo.zip)

```bash
yarn
yarn start
```

update deps version to v4 show differents:
```json
{
    "webpack": "^4",
    "html-webpack-plugin": "^4",
    "ts-loader": "^4",
}
```

## Environment
 - **fork-ts-checker-webpack-plugin**: v6
 - **typescript**: 4.3.2
 - **eslint**: 7.28.0
 - **webpack**: 5
 - **os**: macos big sur 11.3

**Comment by kkuegler** [comment]
This seems to be due to the `"webpack-dev-server": "^3.11.2"` dependency, which does not play well with Webpack 5.
If you update to `"webpack-dev-server": "^4"` (and the corresponding webpack.config.js to `devServer: {}`) this works fine.

**Comment by ananiy** [comment]
thx a lot~
