### ISSUE TITLE
Display total error/warning count at the end of the error summary when in async mode 

### ISSUE THREAD

**Issue by mbalc** [TypeStrong/fork-ts-checker-webpack-plugin#635]
## Feature motivation
In projects where there are lots of errors that are kept to be fixed 'later', the number count is a great indicator for whether maintenance of the errors goes in the right direction - whether the count increases or decreases

We should make the error count as easy to access
However, when using `webpack` in watch/async mode, the error count is not accessible (comparing to sync mode, where errors are reported to `webpack` and are shown in total summary)

## Feature description

This is what I get when building the project single time, without 'watch mode' on:
![image](https://user-images.githubusercontent.com/11033790/127315628-05dd1406-bec7-41f1-8434-cdb488c41c9a.png)

I'd like to get a similar summary every time the project is checked against this plugin in async mode; now it looks like this (at least in `"fork-ts-checker-webpack-plugin": "^6.1.0"`):
![image](https://user-images.githubusercontent.com/11033790/127315846-5086f05b-8f24-4e1c-9d65-61e40d585778.png)

**Comment by piotr-oles** [comment]
Thanks for the idea, I created a PR to implement that :)
