### ISSUE TITLE
somethings about formate 

### ISSUE THREAD

**Issue by eynait1010** [TypeStrong/fork-ts-checker-webpack-plugin#651]
## Feature motivation

Thanks for your effort , I like fork-ts-checker-webpack-plugin which is must faster than other utils.
and i have something confused about:

Sometimes, I want to customize output using formatter,
however, There is always something in the output, such as

![download-8](https://user-images.githubusercontent.com/50448236/130983803-cd561f5f-769b-44ef-8f36-fc91a6118987.png)

 and the path isn't absolute path 

![download-5](https://user-images.githubusercontent.com/50448236/130984082-df1ffed8-c6fa-4a9d-b1a6-48552b9a08c2.png)
in this case, users cannot click the path to open the file in the editor, 
but if I output the absolute path in formatter, the information will be too redundant
I find out CRA can output absolute path, so I am confused about how they do , so I read their code
the reason is that in the old version like 4.x, the output is absolute path
![download-9](https://user-images.githubusercontent.com/50448236/130985003-5db2e9c5-7e82-4403-8f9b-41115689177a.png)

**Comment by piotr-oles** [comment]
I changed it to be compatible with webpack formatting. If you don't like it, you can pass your custom `formatter` function :)

**Comment by lake2** [comment]
same issue +1, I pass my custom formatter function, but it only affect the content, not the path.

```js
        new ForkTsCheckerWebpackPlugin({
            devServer: false, 
            typescript: {
                configFile: path.resolve('tsconfig.json'),
                configOverwrite: {
                    compilerOptions: {
                        noUnusedLocals: true,
                    },
                },
            },
            formatter: issue => {
                return '123';
            },
        }),
```

![image](https://user-images.githubusercontent.com/6293752/180417294-aad08e38-75c1-413e-8b11-ad8490e81da7.png)
