### ISSUE TITLE
Update dep

### ISSUE THREAD

**Issue by jimmywarting** [TypeStrong/fork-ts-checker-webpack-plugin#654]
Could you update all (dev)Dep to keep everything up to date?

**Comment by johnnyreilly** [comment]
Fancy submitting a pull request? Open source is easier when people help ❤️

**Comment by jimmywarting** [comment]
> Fancy submitting a pull request?

...not really, sry

latest chalk is written in ESM-only you don't have `"type": "module"` in package.json

means: you need to 
- also become ESM only
- or set the minium required node version to 12.20 (if it isn't already) and import chalk lazy using `import('chalk')`

... The rest of all the other packages don't seems to be as much breaking...
