### ISSUE TITLE
How to emit .d.ts and .d.ts.map files?

### ISSUE THREAD

**Issue by facinick** [TypeStrong/fork-ts-checker-webpack-plugin#663]
I cannot use ts-loader to generate declaration files with this plugin as that'll cause double type checking.
How can I use this plugin and also have declaration files generated?

**Comment by facinick** [comment]
What I understand is this plugin cannot generate .d.ts files, so what is the use case of this plugin? A large library which needs to save time on all the typescript type checking will most likely want to export their types too! This plugin is not useful for libraries where we need to export types as well, but perhaps apps where it's the final product that doesn't need types exported

**Comment by piotr-oles** [comment]
We're open for contribution - if you think it's a useful feature, feel free to open a PR :)

**Comment by aprilandjan** [comment]
I searched the related issues [generate d.ts](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues?q=generate+d.ts), seems that many people wants this, and so do I, too.

**Comment by aprilandjan** [comment]
Thanks for your work! I'll try it immediately :)

**Comment by PierBJX** [comment]
@aprilandjan Did you succeed to make it work?

**Comment by aprilandjan** [comment]
@PierBJX sorry for the late reply. I've accomplish that with the `v6.5.0` version of the plugin, with `typescript.build` set to `true` and `typescript.mode` set to `write-dts`(in a project of `webpack v4` and `babel-loader`) Seems that both of these two options are needed, which is not documented clearly. but, so far, so good.

**Comment by PierBJX** [comment]
@aprilandjan No problem, I found the answer and I add a [comment](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/679#issuecomment-993657737) in the PR ;)
