### ISSUE TITLE
Checker runs when webpack uses filesystem cache

### ISSUE THREAD

**Issue by adriangodong** [TypeStrong/fork-ts-checker-webpack-plugin#675]
## Current behavior

Webpack 5 introduces a new filesystem cache. Vanilla ts-loader setup can use this cache and subsequent builds without change finished quickly. When ts-loader is set to transpileOnly and fork-ts-checker-webpack-plugin is added, subsequent build is bottlenecked on the plugin and will finish about the same time as without cache.

I've created a repository showing this issue: https://github.com/adriangodong/webpack-cache-filesystem

Webpack development configuration is using ts-loader on transpileOnly and fork-ts-checker-webpack-plugin added, while the production configuration is using ts-loader only.

## Expected behavior

When Webpack 5 filesystem cache hit, checker plugin should skip.

## Steps to reproduce the issue

Clone repository, run build multiple times.

## Issue reproduction repository

https://github.com/adriangodong/webpack-cache-filesystem

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.4.0
 - **typescript**: 4.5.2
 - **eslint**: n/a
 - **webpack**: 5.64.1
 - **os**: Windows, Mac

**Comment by piotr-oles** [comment]
I don't think we will support caching type-checking results (it's a little bit different than transpilation - type-checking results can depend on multiple files). There is already some kind of file-system caching you can use - it's `incremental: true` flag which emits `.tsbuildinfo` files :)

**Comment by adriangodong** [comment]
@piotr-oles Interesting, my initial ask is for the plugin to just skip, since if build output is from cache, there's no need to recheck typing. But, I did try using the incremental flag and it seems that we need to hack tsconfig so that it matches webpack build output for it to work. In my repo, the webpack output is `dist/main.js`, this doesn't match the default tsc output `[file].js`, so I have to modify tsconfig so that it will output to `dist/main.js` and the incremental flag starts working as expected (sub-1 second on subsequent builds with plugin running).

Check out this branch for the change: https://github.com/adriangodong/webpack-cache-filesystem/tree/incremental-flag
