### ISSUE TITLE
Process port closed after `yarn start`

### ISSUE THREAD

**Issue by jonaserhart** [TypeStrong/fork-ts-checker-webpack-plugin#682]
## Current behavior
when i try to `yarn build` my electron app, the build seems to succeed but afterwards I get this error:

```
$ node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 1969.
    at /workspaces/gitclient/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 1979.
    at /workspaces/gitclient/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}
```

## Expected behavior
My electron app starts as expected

## Steps to reproduce the issue
start the dev-container in the provided repository in vs code.
try to run `yarn start` in the root directory

## Issue reproduction repository
[Repository](https://github.com/jonaserhart/docker-env-electron)

## Environment

docker container provided in repository

Maybe I'm missing something important, i don't know, could anyone help me?

**Comment by piotr-oles** [comment]
Hi! Could you try with v7.0.0?

**Comment by piotr-oles** [comment]
Ok, I tested it and for some reason, `yarn start` script starts 2 webpack compilations - 1 as a single run and 1 as a watch run. This plugin uses `async` mode by default when it detects that it's a watch run. To fix the issue, you can set `async: false` in the plugin options.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/8374473/152700846-8a62dd4f-9888-450f-8a29-e5581976bb61.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/8374473/152700855-49cf1506-f976-4168-bf55-3a06a1bdf914.png">
