### ISSUE TITLE
Are there any optimization tips?

### ISSUE THREAD

**Issue by MichaelKapustey** [TypeStrong/fork-ts-checker-webpack-plugin#684]
I started to analyze webpack build and got next results (on dev machine, Intel(R) Core(TM) i7-1185G7):  
General output time took 1 min, 12.42 secs, 
ForkTsCheckerWebpackPlugin took 57.37 secs
This looks like the best place to start some optimizations, but I was not able to find anything surfing over the internet or reading through your readme files.
While it doesn't look very bad for local development, I often need to run this for 20+ packages in ci job with limited resources. It may take an hour to bundle everything. So reducing typecheck step for each package for 10 seconds would make a difference. 
I'm using node 12, webpack 4, fork-ts-checker-webpack-plugin 5.2.1. Tried 6.5.0 and it appeared to be 15 seconds slower. 

So, do you have any tips on how to speed up typechecking in a CI job? I

**Comment by piotr-oles** [comment]
The plugin overhead is negligible and you should look for tips to optimize TypeScript :)
I can recommend this page: https://github.com/microsoft/TypeScript/wiki/Performance
