### ISSUE TITLE
config async with false will block the webpack-hot-middleware hot reload

### ISSUE THREAD

**Issue by JonathonChen** [TypeStrong/fork-ts-checker-webpack-plugin#687]
## Current behavior
By using `fork-ts-checker-webpack-plugin` with the config '`async=false`' and `webpack-hot-middleware` together, when I modify my js or ts file,  the webpack compiling was blocked. 
![image](https://user-images.githubusercontent.com/20022758/147815287-7bce1789-872f-4b7b-8abc-b016f3b887bd.png)
![image](https://user-images.githubusercontent.com/20022758/147815297-fd0cfbee-26ac-4211-8d7e-3af7bf78934f.png)

Here are three ways I have tried to fix this:
1. don't use the hot-reload and it works well
2. change the `async=false` to `async=true` and it works well
3. I try to change the order of `new webpack.HotModuleReplacementPlugin()` and `new ForkTsCheckerWebpackPlugin({ formatter: 'codeframe', async: false })` but it doesn't work

**But the two methods that can fix this problem aren't suitable for my projects because we have a lot of projects using hot-reload and we need the type-check block the webpack compile synchronously.**

## Expected behavior

when I modify my js or ts file, the page can sucessfully reload and the webpack compile can bundle well.

## Steps to reproduce the issue

1、using `webpack-hot-middleware` and config the entries
![image](https://user-images.githubusercontent.com/20022758/147815231-c505bcae-d4d5-46f4-ae29-d502d88ec56a.png)
![image](https://user-images.githubusercontent.com/20022758/147815486-16e2e10c-3462-49ab-96a1-d87da4687788.png)
2、config the `async=true`
![image](https://user-images.githubusercontent.com/20022758/147815511-87116fce-aa4d-4efa-ade8-9d78cfa64514.png)

## Issue reproduction repository

 Using `zoom` or other tools to debug this bug.
 I neeeeeeeeeeeed your help!!!!!!!!(I don't know how to debug this kind of problems since the webpack is a big black box for me)
## Environment
 - **fork-ts-checker-webpack-plugin**:  4.1.6(due to the minimum node verison is 8.12.0 in our team)
 - **typescript**: 3.9.10
 - **webpack**: 4.46.0
 - **webpack-dev-server**: 3.11.3
 - **webpack-hot-middleware**: 2.25.1
 - **os**: macOS

**Comment by piotr-oles** [comment]
I'm not sure I understand what's the issue :) Why can't you use the async: true mode? This mode is designed to not block webpack emit, so it solves the issue you have, right? 
It's an expected behavior that async: false will block the emit.

**Comment by JonathonChen** [comment]
> I'm not sure I understand what's the issue :) Why can't you use the async: true mode? This mode is designed to not block webpack emit, so it solves the issue you have, right? It's an expected behavior that async: false will block the emit.

We need the feature async: false to block the emit, so that guys using typescript in our team must fix the type check errors. By the way, I updated the awesome-typescript-loader to bable + fork-ts-checker-webpack-plugin and the awesome-typescript-loader will block the emit which is what we want.

**Comment by piotr-oles** [comment]
Ok, so you mean that for `async: false` the bundle is never emitted / it takes infinite time to compile?

**Comment by JonathonChen** [comment]
> Ok, so you mean that for `async: false` the bundle is never emitted / it takes infinite time to compile?

Yeah, it does act as you described.

**Comment by piotr-oles** [comment]
Could you try to create a reproduction repository?

**Comment by JonathonChen** [comment]
> Could you try to create a reproduction repository?
Check your email and if you have any questions, please don't hesitate to contact me!

![image](https://user-images.githubusercontent.com/20022758/148497430-d97b7d41-8abe-4108-a188-6de9a6827db7.png)

**Comment by piotr-oles** [comment]
This looks suspicious:

![image](https://user-images.githubusercontent.com/8374473/148619346-4903d8b8-7392-49d0-8645-11be5fa24cda.png)

I see that you use `@block/cli` package - is it some in-house solution for setup a webpack?

**Comment by JonathonChen** [comment]
> This looks suspicious:
> 
> ![image](https://user-images.githubusercontent.com/8374473/148619346-4903d8b8-7392-49d0-8645-11be5fa24cda.png)
> 
> I see that you use `@block/cli` package - is it some in-house solution for setup a webpack?

Yeah, it is the Cli pacakge for our team, you can debug from the `src/dev-server.js` and it use the command(see the pic below)
![image](https://user-images.githubusercontent.com/20022758/148646725-ef4afe72-3405-4887-8479-de534eeadf73.png)

**Comment by JonathonChen** [comment]
> `rc/dev-server.js` and it use the command(see the pic below)

Hi bro, do you have any good news about this?

**Comment by JonathonChen** [comment]
@piotr-oles Hi bro, do you have any good news about this?

**Comment by piotr-oles** [comment]
Sorry, but this is probably an issue in your setup in the internal package. If you create a repository that doesn't use this package and still has this error, I can try to help you. Otherwise, I can't afford to spent my free time debugging someone's code :)

**Comment by JonathonChen** [comment]
> Sorry, but this is probably an issue in your setup in the internal package. If you create a repository that doesn't use this package and still has this error, I can try to help you. Otherwise, I can't afford to spent my free time debugging someone's code :)

Thanks anyway, I will make it clear first and if it still has this error then I might need your help :)

**Comment by JonathonChen** [comment]
This is the reason of my in house package using two of the webpack middleware instaces which share the same webpack compiler instance and causing the loop locking waiting for the other one's waiting:)
