### ISSUE TITLE
[7.0.0-alpha.11] - typescript errors are reported twice

### ISSUE THREAD

**Issue by rodrigofariow** [TypeStrong/fork-ts-checker-webpack-plugin#694]
## Current behavior
After upgrading from 7.0.0-alpha.9 to 7.0.0-alpha.11 I got the following behavior:
![image](https://user-images.githubusercontent.com/22502084/150591323-6acb4956-0d2d-45d6-b3b5-1f2328116a52.png)

## Expected behavior
On 7.0.0-alpha.9 I get the following (**correct**):
![image](https://user-images.githubusercontent.com/22502084/150591754-6c0401fc-b364-4288-af1a-e4c40242534a.png)

## Environment
 - **fork-ts-checker-webpack-plugin**: 7.0.0-alpha.11
 - **typescript**: 4.5.5 
 - **webpack**: 5.67.0
 - **os**: mac OS 12.1

Thank you for your time! 🙏

**Comment by piotr-oles** [comment]
Hi! Thanks for the report :)
Could you create a reproduction repository?

**Comment by rodrigofariow** [comment]
Hi @piotr-oles !

I just tested with the latest version 7.0.0 and it works correctly for me now!
Can't tell for sure which alpha (after 7.0.0-alpha.11) fixed the issue though 😆 

Thanks!

**Comment by ifeltsweet** [comment]
This is happening to us too on v7.2.11. (We are using Serverless Framework with `serverless-offline` and `serverless-webpack` plugins.)

First run we get a single log, but when saving a file a recompile triggered by the watch will log twice.

**Comment by ifeltsweet** [comment]
I think this could be due to https://github.com/webpack/webpack/issues/15431
