### ISSUE TITLE
Error: Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by huineng** [TypeStrong/fork-ts-checker-webpack-plugin#706]
"fork-ts-checker-webpack-plugin": "^7.0.0"
"typescript": "^4.5.5",
"webpack": "^5.68.0",
"webpack-cli": "^4.9.2",

this morning i deleted my node-modules and package-lock.json to have a clean install.
Unfortunately i hit an error that traces back to this plugin as a start

can you help to determine what can be done to solve this ?

```
[webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /node_modules/ajv-keywords/dist/definitions/typeof.js
- /node_modules/ajv-keywords/dist/keywords/typeof.js
- /node_modules/ajv-keywords/dist/keywords/index.js
- /node_modules/ajv-keywords/dist/index.js
- /node_modules/schema-utils/dist/validate.js
- /node_modules/schema-utils/dist/index.js
- /node_modules/fork-ts-checker-webpack-plugin/lib/plugin.js
- /node_modules/fork-ts-checker-webpack-plugin/lib/index.js
```

thanks

**Comment by Pantura** [comment]
Bumped into this just the other day. Set version of ajv-keywords to 3.5.2 in your package.json. This should maybe be defined as peer dependency of schema-utils/fork-ts-checker. There's a mismatch of ajv and ajv-keywords and a breaking change between them.

**Comment by piotr-oles** [comment]
I googled this error and it seems to occur in many packages. Could you report this to `schema-utils` and `ajv-keywords`? (seems like some package doesn't follow semantic versioning or uses non-public API)
