### ISSUE TITLE
Multiple tsconfig seem not working

### ISSUE THREAD

**Issue by riflowth** [TypeStrong/fork-ts-checker-webpack-plugin#715]
## Current behavior
I have a project structure like the graph below, in child tsconfig *(in client/server folder)* they have separate `types` and `paths` mapping, but when the webpack has done the building, it gives me an error that relates to path mapping. e.g. `Cannot find module ... or its corresponding type declarations`.

If I use only `ts-loader` without `fork-ts-checker-webpack-plugin` it work fine.

```
project
|___ src
|   |___ client
|   |    |___ tsconfig.json
|   |___ server
|        |___ tsconfig.json
|___ tsconfig.json
|___ webpack.config.js
|___ package.json
```

*Sorry for my bad English*

## Environment
 - **fork-ts-checker-webpack-plugin**: ^7.2.1
 - **typescript**: ^4.5.4
 - **eslint**: ^8.6.0
 - **webpack**: ^5.65.0
 - **os**: Window 11

**Comment by piotr-oles** [comment]
I don't know if adding support to multiple tsconfig.json files will be supported in this plugin. This would require running multiple TypeScript instances - for each config file. This is contrary to what this plugin tries to achieve - improved type-checking speed. I would suggest creating a separate `tsconfig.all.json` file that defines project references to client and server and using that file in the plugin :)
