### ISSUE TITLE
Location issue is illegible on light background

### ISSUE THREAD

**Issue by nevnein** [TypeStrong/fork-ts-checker-webpack-plugin#718]
## Current behavior
On a terminal with a light background, the location of an issue is illegible, see attached image.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/12485857/157305376-eb7aca60-ae79-45d5-bd58-b09b5a522a1c.png">

## Expected behavior
The location should be legible regardless of the background.

I suggest removing `whiteBright` [here](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/b48f98a17162f280cfea20f3f752cca9d58afaf7/src/formatter/webpack-formatter.ts#L18), would a PR be accepted?

**Comment by piotr-oles** [comment]
Yes, please create a PR :)
