### ISSUE TITLE
Build hangs with yarn pnp

### ISSUE THREAD

**Issue by DiFuks** [TypeStrong/fork-ts-checker-webpack-plugin#719]
## Current behavior
When I run a build with yarn pnp (and `pnpEnableEsmLoader: true`) the process hangs

## Expected behavior
The process does not hang and completes successfully

## Steps to reproduce the issue
1. Install yarn 3 with pnp
2. Install webpack 5
3. Install fork-ts-checker
4. Run webpack build

## Issue reproduction repository

https://github.com/DiFuks/yarn-pnp-fork-ts-checker-stuck

fork-ts 6
`pnpEnableEsmLoader: true` in `.yarnrc.yml`
`webpack --mode=production` work
`webpack --mode=development` does not work
`webpack serve --mode=development` work

https://github.com/DiFuks/yarn-pnp-fork-ts-checker-stuck/tree/fork-ts-checker-7

fork-ts 7
`pnpEnableEsmLoader: true` in `.yarnrc.yml`
`webpack --mode=production`  does not work
`webpack --mode=development` does not work
`webpack serve --mode=development` does not work

https://github.com/DiFuks/yarn-pnp-fork-ts-checker-stuck/tree/pnp-enable-esm-loader-false

fork-ts 7
`pnpEnableEsmLoader: false` in `.yarnrc.yml`
`webpack --mode=production`  work
`webpack --mode=development` work
`webpack serve --mode=development` work

## Environment
 - **fork-ts-checker-webpack-plugin**: ^6.5.0
 - **typescript**: ^4.6.2
 - **eslint**: -
 - **webpack**: ^5.70.0
 - **os**: MacOS 12.2

**Comment by ncrohn** [comment]
I am also running into this issue. I tried the steps outlined and confirmed setting `pnpEnableEsmLoader` to `false` lets the plugin run properly.

**Comment by DiFuks** [comment]
Here is the information about the problem. I close this issue. https://github.com/yarnpkg/berry/issues/4157#issuecomment-1053558695
