### ISSUE TITLE
`generateTrace` does not work with newer TypeScript versions

### ISSUE THREAD

**Issue by mkantor** [TypeStrong/fork-ts-checker-webpack-plugin#722]
## Current behavior

[The README describes how to profile slow type-checking by setting `generateTrace` in `tsconfig.json`](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#profiling-types-resolution). However this doesn't work with recent TypeScript versions.

## Expected behavior

When building with `"generateTrace": "./traces"` in `tsconfig.json`, trace files should be created in `./traces` as stated in the README.

## Steps to reproduce the issue

1. Set up a project with a recent version of TypeScript (I'm using 4.6.2, but I'm nearly certain this problem exists as far back as 4.2.x).
2. Set  up a `tsconfig.json` with `"generateTrace": "{folderName}"` as [described in the README](](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#profiling-types-resolution)).
3. Do a build.
4. Observe that no trace files were created.

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.2.12
 - **typescript**: 4.6.2
 - **eslint**: 7.32.0
 - **webpack**: 4.46.0
 - **os**: macOS 12.0.1

**Comment by mkantor** [comment]
I think this comes down to relying on internal TypeScript APIs which have changed.

For example:
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/b5a38c11dd568575f41a2eb24ba6fd33dd866d78/src/typescript/worker/lib/tracing.ts#L15

Since https://github.com/microsoft/TypeScript/pull/42323 it seems that `typescript.tracing` is `undefined` until `typescript.startTracing` is called, but `startTracingIfNeeded` is written to never call `startTracing` unless `tracing` is truthy:
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/b5a38c11dd568575f41a2eb24ba6fd33dd866d78/src/typescript/worker/lib/tracing.ts#L18-L24

**Comment by mkantor** [comment]
Also https://github.com/microsoft/TypeScript/pull/43354 removed `getTypeCatalog`, but it's relied upon here in `stopTracingIfNeeded`:
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/b5a38c11dd568575f41a2eb24ba6fd33dd866d78/src/typescript/worker/lib/tracing.ts#L32

**Comment by mkantor** [comment]
Separately, if there was some kind of warning about tracing being skipped even though `generateTrace` was set it would have helped me understand what was going on much more quickly. Such a warning would be useful for folks using older versions of TypeScript as well (even once this issue is resolved).

**Comment by piotr-oles** [comment]
@mkantor given that you already know where is the issue and how to solve it, would you mind creating a PR?

**Comment by mkantor** [comment]
Should `generateTrace` be supported for various TypeScript versions? I think I know how to address it for TypeScript 4.6.x, but am not sure about past/future releases, and would be worried that a fix which works with my setup might break things for others.

Relatedly, are there any tests that run against different TypeScript versions?

**Comment by piotr-oles** [comment]
Sorry for the late response. I think it's enough to support it for TypeScript 4.6.x+ - this feature is a minor one.
We have e2e tests that run on different versions of typescript - check the `tests/e2e` directory. So basically you would have to create a new test that uses `generateTrace: './traces'` in tsconfig.json, run a webpack build, and check if trace files exist :)
