### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by tjx666** [TypeStrong/fork-ts-checker-webpack-plugin#723]
## Current behavior

After multple time rebuild, throw this warning:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/41773861/158026603-2b2170c2-1deb-4f1a-aa63-9dd68e872385.png">

After I remove this extension, no this issue.

I can confirm version 6.3.3 no this issue.

## Expected behavior

No this warning.

## Steps to reproduce the issue

1. clone repository: git@github.com:tjx666/awesome-chrome-extension-boilerplate.git
2. checkout to `fork-ts-checker-webpack-plugin-issue` branch
3. install dependencies by `pnpm install`
4. `pnpm start`
5. open `src/background/index.ts`, modify this file multiple times to triiger rebuild, about 6 times
6. you will see this warning

## Environment
 - **fork-ts-checker-webpack-plugin**: 7.2.1
 - **typescript**: 4.6.2
 - **eslint**: 8.11.0
 - **webpack**: 5.70.0
 - **os**: MacOS 12.2.1

**Comment by galaxy-s10** [comment]
![image](https://user-images.githubusercontent.com/61055341/160278991-f18b65ec-1b18-4e6b-8683-3982096aa034.png)

> I have the same problem，version is ^7.2.1
