### ISSUE TITLE
[HELP] Issues with re-renders

### ISSUE THREAD

**Issue by Bringordie** [TypeStrong/fork-ts-checker-webpack-plugin#741]
Hello,

We have a setup using yarn-workspace with babel.
When we add ForkTsCheckerWebpackPlugin out of the box to our webpack with just:
`new ForkTsCheckerWebpackPlugin({
            typescript: {
                build: true,
                memoryLimit: 4096,
            },
        }),`
        
We experience a (delayed) refresh once a file is changed. Meaning that we save, the hot reload makes a refresh instantly and add our changes, and then 3-5++ seconds later we get another refresh made by ForkTsCheckerWebpackPlugin.
Saving a component 3 times would then just que all of these refreshes, so that over a period of time all of those refreshes would go through.

We have tried to add 
`mode:  'readonly'` which works exactly how we want. But sadly if we change another workspace we recieve no errors when there are errors.  We've also tried with `write-tsbuildinfo` but with no luck.

Surely there is a way to have ForkTsCheckerWebpackPlugin typecheck without forcing rerenders that works across workspaces?

**Comment by piotr-oles** [comment]
Could you create a reproduction repository?

**Comment by Bringordie** [comment]
https://github.com/Bringordie/fork-ts-checker-webpack-plugin-741
