### ISSUE TITLE
[Question] Do I need this plugin? tsc vs eslint

### ISSUE THREAD

**Issue by uiii** [TypeStrong/fork-ts-checker-webpack-plugin#743]
Hi there,
I am building my custom webpack config and thinking if I need this plugin. Area about linting is quite new and confusing to me. I am using `babel-loader` everything works fine, only thing I am missing is errors & warnings checking (types, unused variables, ...). I found this and `eslint-webpack-plugin` (when inspecting CRA webpack). As I see both plugins/tools (`tsc`, `eslint`) can do similar things. E.g. to check unused variables can do both of them. The question is can `eslint` check all `tsc` does? If yes I don't see a reason to use this plugin. Can you clarify this to me, please? Thanks

**Comment by piotr-oles** [comment]
This plugin uses TypeScript to find semantic errors. An example of semantic error is something like: const x: number = "string". If you use typescript, I would recommend using this plugin or running tsc--noEmit as a part of lint stage in CI pipeline

**Comment by uiii** [comment]
eslint can't check semantic errors?

**Comment by piotr-oles** [comment]
it depends how you define semantic errors, but eslint can't check type-related semantic errors (assigning / passing wrong type)

**Comment by uiii** [comment]
Ah, ok, so it is clear, this plugin has its place. Thanks for the clarification.
