### ISSUE TITLE
No warnings displayed

### ISSUE THREAD

**Issue by rsereir** [TypeStrong/fork-ts-checker-webpack-plugin#746]
## Current behavior
Some eslint/TS warnings are displayed in my production build command but not present 

## Expected behavior
I want to display all warnings displayed in my `yarn build` to my terminal on dev server hot reload.
I have trying [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) configuration in my webpack config but it seems does not work.

## Environment
- **NextJs project**
- **nextjs**: 12.1
 - **fork-ts-checker-webpack-plugin**: ^7.2.11
 - **typescript**: ^4.4.4
 - **eslint**: ^7.12.1
 - **webpack**: nextjs webpack
 - **os**: MacOS

**Comment by piotr-oles** [comment]
Hi! Thanks for the report. Could you provide a reproduction repository? And could you send an example of warning that is missing?
