### ISSUE TITLE
When type in my package.json is module, using this plugin causes me to re-execute using the Node API file of Webpack.

### ISSUE THREAD

**Issue by cmw-big** [TypeStrong/fork-ts-checker-webpack-plugin#748]
## Current behavior
re-execut using the node api file of webpack.

## Expected behavior
no re-execut
## Steps to reproduce the issue
set the package.json type to module

## Environment
 - **fork-ts-checker-webpack-plugin**: [7.2.11]
 - **typescript**: [4.7.2]
 - **eslint**: [8.16.0]
 - **webpack**: [^5.72.1]
 - **os**: [windows 11]

**Comment by piotr-oles** [comment]
Could you elaborate more and provide a reproduction repository? I don't know what exactly doesn't work :)
