### ISSUE TITLE
[ consult ]What the "code" property in the Issue means？

### ISSUE THREAD

**Issue by zongc1001** [TypeStrong/fork-ts-checker-webpack-plugin#754]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/32095921/176389201-99ae8239-fc17-4c9a-a47c-87416f886ce6.png">

**Comment by piotr-oles** [comment]
It's a TypeScript error code, like `TS1005`. I agree that it's not obvious, feel free to improve README.md :)
