### ISSUE TITLE
NodeJS API: `RpcExitError` on `compiler.close()`

### ISSUE THREAD

**Issue by AprilArcus** [TypeStrong/fork-ts-checker-webpack-plugin#774]
## Current behavior
ForkTSCheckerPlugin prints this error as soon as I call `.close()` on the [compiler instance](https://webpack.js.org/api/node/#compiler-instance) via the NodeJS API, which I must do (and await) in order to avoid corrupting the [filesystem cache](https://webpack.js.org/configuration/cache/) due to https://github.com/webpack/webpack-cli/issues/2918.

```
RpcExitError: Process 460624 exited [SIGTERM]
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript.
```

## Expected behavior
ForkTsCheckerWebpackPlugin should exit cleanly.

## Environment
 - **fork-ts-checker-webpack-plugin**: 7.2.13
 - **typescript**: 4.6.3
 - **webpack**: 5.74.0
 - **os**: macOS 12.5.0

**Comment by AprilArcus** [comment]
This error is also emitted when terminating webpack dev server.

**Comment by piotr-oles** [comment]
Hi! Feel free to create PR to fix it :)

**Comment by piotr-oles** [comment]
I can't reproduce it with the latest version of the plugin - is it still an issue?

<img width="858" alt="image" src="https://user-images.githubusercontent.com/8374473/222986641-6df3512b-b77f-4bd6-b9d8-e8369cc55bd0.png">

**Comment by piotr-oles** [comment]
I'm closing for now, but if you create repository where I can reproduce the bug, I will re-open the issue :)
