### ISSUE TITLE
RangeError: maximum call stack size exceeded

### ISSUE THREAD

**Issue by clyan** [TypeStrong/fork-ts-checker-webpack-plugin#776]
In my project, "RangeError: maximum call stack size exceeded" is still reported when exclude:["node_modules"] has been configured in the tsconfig.json file, but when I add include:["src/**/ *" ], the error miraculously disappeared, although the problem is solved, but I don't know why the exclude didn't take effect

## Environment
 - **fork-ts-checker-webpack-plugin**: 7.2.13
 - **typescript**: 4.7.4
 - **eslint**: 8.18.0
 - **webpack**: 5.74.0
 - **os**: window10

**Comment by piotr-oles** [comment]
Please create an issue with reproduction repository. Otherwise, I can't help you :)
