### ISSUE TITLE
webpack Build fails, and succeeds next time

### ISSUE THREAD

**Issue by lockiechen** [TypeStrong/fork-ts-checker-webpack-plugin#777]
## Environment
 - **fork-ts-checker-webpack-plugin**: [version from the `package.json`]
 - **typescript**: [version from the `package.json`]
 - **eslint**: [version from the `package.json`]
 - **webpack**: [version from the `package.json`]
 - **os**: [e.g. Ubuntu 19.04]

**Comment by piotr-oles** [comment]
Please feel the template, I will not be able to help you otherwise
