### ISSUE TITLE
Upgrading from 6.4 to 7.x? No errors ever reported

### ISSUE THREAD

**Issue by crashmstr** [TypeStrong/fork-ts-checker-webpack-plugin#779]
Trying to update from 6.4 to 7.x, and after an hour of trying to replicate the "right" settings to match what I had, I've had no luck getting any ESLint errors to show up, and more than half the time don't even see any indication of any output from the plugin.

Reverting back down to 6.5 and my old configuration settings work fine.

An example code change to "test" if this is working is to change a `===` to a `==`. 6.4 and 6.5 with my existing configuration reports that in build or watch, using 7.1 or 7.2 never shows any errors.

Perhaps I'm missing something obvious, but I can't get there from just reading the current documentation.

```
    new ForkTsCheckerWebpackPlugin({
      eslint: {
        files: [
          'app/**/*.{ts,tsx}',
          'shared/**/*.{ts,tsx}',
        ],
        options: {
          cache: true,
          cacheLocation: path.resolve(__dirname, buildCache, '.eslintcache'),
        },
      },
      formatter: 'basic',
    }),
```

**Comment by petternordholm** [comment]
According to the docs, the ESLint feature is not supported on 7.x.x

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin under **Installation**

**Comment by crashmstr** [comment]
Wow, it was obvious.
Also, tragic.

**Comment by piotr-oles** [comment]
Yep :)
