### ISSUE TITLE
Type checking only imported modules

### ISSUE THREAD

**Issue by dglazkoff** [TypeStrong/fork-ts-checker-webpack-plugin#784]
I have test files that used jest as test library. jest was installed as dev depedencies. When I start production build using babel/preset-typescript and fork-ts-checker-webpack-plugin I get errors, that ts can not find jest. But my test files do not imported and do not execute. How can I say, that fork-ts-checker-webpack-plugin must not to type check not imported files in production build.

**Comment by piotr-oles** [comment]
Does `tsc --noEmit` command report type error?

**Comment by piotr-oles** [comment]
TypeScript is designed to operate on a project basis, using a list of files rather than a dependency graph for type-checking. It is not something that can be altered in this plugin. However, you can utilize the configOverwrite.exclude option to exclude test files in the plugin :)

**Comment by mikevoets** [comment]
If anyone is wondering how to do this, this is what I did:

```js
// webpack.development.config.js

const tsConfig = require('tsconfig.json');

const webpackConfig = generateWebpackConfig({
  plugins: [
    new ForkTSCheckerWebpackPlugin({
      typescript: {
        configOverwrite: {
          exclude: [...tsConfig.exclude, '**/*.test.ts*'],
        },
      },
    })
  ],
});
```
