### ISSUE TITLE
Configuration has an unknown property 'resolveTypeReferenceDirectiveModule'.

### ISSUE THREAD

**Issue by dasler-fw** [TypeStrong/fork-ts-checker-webpack-plugin#799]
The first, pls create migration to new versions files, because im trying to update from 4 to 6, for example and cant find any help to that.

And for now, i cant understand how to change my highlighted options to new 6.5.0 version.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/33331165/219658507-9cdad749-2f20-4d74-888b-5c4a8556ea92.png">

I can't figure out where the parameters disappeared to after v 4. Would be thankful for every help!

**Comment by piotr-oles** [comment]
Yarn PnP is supported OOTB starting from 5.0.0 - you don't need these options anymore :)
