### ISSUE TITLE
error: debug failure. false expression

### ISSUE THREAD

**Issue by peter-resmed** [TypeStrong/fork-ts-checker-webpack-plugin#807]
## Current behavior
Gets error: debug failure. false expression and the type errors are not caught in runtime

## Expected behavior
No error and type errors should be caught

## Steps to reproduce the issue
npm run dev

## Issue reproduction repository
https://stackblitz.com/edit/webpack-webpack-js-org-sdj2xg?file=package.json

## Environment
 - **fork-ts-checker-webpack-plugin**: 8.0.0
 - **typescript**: 5.0.2
 - **eslint**: 8.36.0
 - **webpack**: 5.76.2
 - **os**: windows 10

**Comment by peter-resmed** [comment]
works fine until typescript 4.9.5

**Comment by christiango** [comment]
Is it possible this error is in ts-loader and not fork-ts-checker in your case? I'm seeing the same thing over there: https://github.com/TypeStrong/ts-loader/issues/1604

**Comment by peter-resmed** [comment]
I don't think so. I am not using ts-loader in my project.
