### ISSUE TITLE
.

### ISSUE THREAD

**Issue by umutfahriozkan** [TypeStrong/fork-ts-checker-webpack-plugin#817]
.

**Comment by TrueXPixells** [comment]
Possible same as https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/814

**Comment by desw0lf** [comment]
Change:
```
logger: {
    infrastructure: 'silent',
},
```
to:
```
logger: {
    log: (message) => console.log(message),
    error: (message) => console.error(message),
},
```
------
Or for people that are are using `create-react-app`, create a `fork-ts-checker.config.js` in root folder and populate with:
```
module.exports = {
  logger: {
    log: (message) => console.log(message),
    error: (message) => console.error(message),
  },
};
```

**Comment by piotr-oles** [comment]
You don't have to provide logger at all - it will use `console` object by default. It looks like an issue after upgrade, where we made a breaking change to logger config. You can see in README.md that now it can be either an object that implements log and error methods or 'webpack-infrastructure' string if you want to use webpack infrastructure logger instead :)
