### ISSUE TITLE
Does it respect @ts-nocheck ?

### ISSUE THREAD

**Issue by deser** [TypeStrong/fork-ts-checker-webpack-plugin#827]
I have a suspicion that it doesn't respect `@ts-nocheck` directive. Is this true?

**Comment by piotr-oles** [comment]
We don't have any specific code to ignore @ts-nocheck - this plugin simply runs typescript in a separate thread and integrates with webpack. All typescript features should be supported. I'm closing this issue, but if you have any reproduction repository where it doesn't work, post it here, I can take a look.
