### ISSUE TITLE
Invalid deploy key

### ISSUE THREAD

**Issue by piotr-oles** [TypeStrong/fork-ts-checker-webpack-plugin#83]
@etienne-dldc @smonteil NPM deploy key doesn't work again - please send me a new one

**Comment by etienne-dldc** [comment]
um... this is annoying, I think we should transfer ownership of the npm package to you so this issue stop happening, @smonteil this should do : https://docs.npmjs.com/cli/owner .

**Comment by piotr-oles** [comment]
@smonteil Thank you for the token :) I would be thankful for transferring NPM ownership. The repository still will be on the Realytics account :)

**Comment by johnnyreilly** [comment]
I'd just like to second the desire to add @piotr-oles as an owner of `fork-ts-checker-webpack-plugin`. FWIW, if you're concerned about losing control, it is not necessary to transfer the publishing rights entirely.  You can simply add him as another owner. See the npm docs here:

https://docs.npmjs.com/cli/owner

By way of example, [`ts-loader`](https://www.npmjs.com/package/ts-loader) has 3 owners.  

If you could add @piotr-oles as an owner it would make shipping new versions of the checker a much less difficult experience! 🌻
