### ISSUE TITLE
[QUESTION] Equivalent of eslint: {files: "pattern"} in ForkTsCheckerWebpackPlugin v9

### ISSUE THREAD

**Issue by rahulranjan-blitz** [TypeStrong/fork-ts-checker-webpack-plugin#844]
## Current behavior
I am currently upgrading my old webpack config from 2 years back. Earlier I had used ForkTsCheckerWebpackPlugin with {eslint: { files: './src/**/*.{ts, tsx, js, jsx}' } } as constructor argument. on v5.2.0
I wish to pass the same file pattern to be included for type checking but not sure which is the property/field to use, have checked the documentaion. Can someone point me out the field for this?

Thank you so much!

**Comment by piotr-oles** [comment]
Here you go: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin?tab=readme-ov-file#issues-options :)
