### ISSUE TITLE
[vue] Imports requires to omit .vue extension

### ISSUE THREAD

**Issue by Toilal** [TypeStrong/fork-ts-checker-webpack-plugin#88]
When running vue-loader with ts-loader without this plugin, I have to use `.vue` extension to perform imports. But when enabling this plugin, I have to omit them for build to pass.

See [this comparison](https://github.com/pragmasphere/vue-tree/compare/fork...no-fork) => Both branches builds with no error. 

It would be better embrace default import behavior, but I'm not sure how the underlying webpack configuration is involved ...

**Comment by RehanSaeed** [comment]
The `extensions` setting in Webpack configuration should be used to determine whether to add or omit `.vue`.
