### ISSUE TITLE
Typescript 2.7.1 compatibility

### ISSUE THREAD

**Issue by mchaov** [TypeStrong/fork-ts-checker-webpack-plugin#95]
Builds are filing with latest typescript.

![image](https://user-images.githubusercontent.com/12296991/35682346-0cd28dfc-0769-11e8-8771-31fc16c2c9b0.png)

**Comment by RehanSaeed** [comment]
I'm using 2.7.1 and not getting this error but am getting compile time errors with Vue.js.

**Comment by jvtrigueros** [comment]
I'm getting this error inside a `node:9` container, but for some reason I am not getting this on macOS.
