### ISSUE TITLE
Support overriding typescript version

### ISSUE THREAD

**Issue by Pajn** [TypeStrong/fork-ts-checker-webpack-plugin#99]
I need to be able to override the typescript version.
It would be great if compiler could be specified in options just as with ts-loader

**Comment by johnnyreilly** [comment]
Doesn't it just use the TypeScript version in the `package.json`? i.e. You can use this?

**Comment by Pajn** [comment]
It does, which works fine in most case.
My case is that I maintain tscomp which is similar to create-react-app. I would like to allow the user to override the typescript version with their own which complicates the matter a bit though.

**Comment by johnnyreilly** [comment]
@piotr-oles maybe worth plugging in https://probot.github.io/apps/stale/ ?  I've started using it on ts-loader.  Really pleased I did!
